### ISSUE TITLE
Suggestion: Unify honey types

### ISSUE THREAD

**Issue by Starfang42** [NillerMedDild/Enigmatica6#1001]
Looking through JEI, there appear to be three honey types:

Resourceful Bees honey: Received from multi-block centrifuge. Has a honey bucket version, received by the honey-bottle to honey bucket recipe. 

COFH honey: received either by processing a minecraft honeycomb in the centrifugal separator, or a honey block in the magma crucible. Only type of honey that the fluid encapsulator can turn into honey bottles, or the blast chiller can turn into honey blocks. 

Create Honey: Only received, as far as I can tell, by using create's drain with minecraft honey bottles. No notable uses. Oddly seems to be treated as water in a large number of recipes. 

It might make sense to unify these into one honey. 

There's also Catnip Honey, which is only produced by a particular type of comb. It has no uses by itself, from what I can tell, but has its own honey bottle/bucket/block. Could either be unified with the other honeys, or maybe used as an ingredient for unique (cat related?) recipes.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, we'll look into it :)

**Comment by Merlo17** [comment]
I would suggest keeping Create as the default one. It looks the best imo and is pretty cool when placing it in world

**Comment by MuteTiefling** [comment]
Certainly COFH honey should go, as it's pretty much just duplicated content. 

The Centrifugal Separator recipe would be removed as the Resourceful Bees centrifuges process vanilla combs. 
Magma Crucible recipe could be converted to output 

And while Create's honey is beautiful, it's also plagued by the whole 'this is actually water' thing that lets machines use it instead of water. Personally, I'd disable it and use Resourceful Bees' honey for everything. Should require the least amount of change too as we just need to review the Item Draining and Filling recipes from Create.

**Comment by NillerMedDild** [comment]
> And while Create's honey is beautiful, it's also plagued by the whole 'this is actually water' thing that lets machines use it instead of water. Personally, I'd disable it and use Resourceful Bees' honey for everything. Should require the least amount of change too as we just need to review the Item Draining and Filling recipes from Create.

very yes
