### ISSUE TITLE
Randomized Stone and Cobblestone Catalysts are not showing in JEI on Servers

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#1097]
**Modpack version**
0.3.10

**Describe the bug**
I think there's no way to get the embellishcraft blocks. I know the whole world stone gen was changed, however I wouldn't find a way to get those unless you already have some (saw 2 ways to generate it in JEI if you have at least one block). Could we have either stonecutter recipes or crafting recipes for those please :) they're pretty cool to build with. 
Thanks !

**Comment by NillerMedDild** [comment]
You need to make a cobble or stonegenerator with a block of iron or block of diamond under the place stone generates :) It's in JEI

**Comment by jinkhya** [comment]
You're talking about this? 
![image](https://user-images.githubusercontent.com/10158963/106016386-b5337300-60bf-11eb-80b8-2d8b18c3dc3b.png)

**Comment by NillerMedDild** [comment]
Almost, 2 tabs to the right.

**Comment by jinkhya** [comment]
so this? XD 
![image](https://user-images.githubusercontent.com/10158963/106016691-017eb300-60c0-11eb-8081-0fde39647c3a.png)

**Comment by soepie7** [comment]
What he means is; you have, like in the first image you sent, a way to get blocks other than cobblestone or stone if you place that block also below the generator. Now you may think this is pointless because you need at least one block, but; if you place an iron block under a cobble gen or diamond block under a stone gen, you get a random cobble or stone block as result. This way you can get all those blocks you need to make the specialized cobble or stone farms.

**Comment by NillerMedDild** [comment]
Oh I saw wrong, my bad xD soepie7 is correct!

**Comment by jinkhya** [comment]
Oh I see it's iron block for the cobblestone kinds gen, diamond block for stone kinds gen. JEI is only showing basalt for basalt, granite for granite, etc so there's no way to know about the iron/diamond blocks :) Unless it's somewhere in quest book and I missed it. Anyways thanks a lot !!! ^^

**Comment by MuteTiefling** [comment]
@jinkhya No, it should be showing in JEI like this: 

![image](https://user-images.githubusercontent.com/9543430/106031865-c7041e80-609d-11eb-8122-00db34ec0268.png)

There may be an actual issue here, so I'm going to re-open this. I note that it's also not showing in JEI on our Dev server, but shows fine in SP. Are you playing on a server by chance?

**Comment by jinkhya** [comment]
I am yes :)

**Comment by MuteTiefling** [comment]
Flaborta and Dravik have both confirmed it's an issue on E6 server too.

It does appear to just be an issue with showing in JEI, however. Diamond Blocks still work as a random catalyst...

**Comment by NillerMedDild** [comment]
The issue is the good old JEI server load issue, where recipes are loaded before tags. Will add a description to remedy this.
