### ISSUE TITLE
Mod Suggestion: Ex Nihilo: Sequentia

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1124]
**https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia/**

**Mod Description**
This mod adds hammers, seives, barrels, and a variety of other tools useful for creating vanilla resources from other vanilla resources - hammering cobblestone into gravel, or gravel into sand, sieving dirt to get seeds, etc, etc.

**Why would you like the mod added?**
Because it adds a large number of simple, early game ways to get basic resources, without needing to tackle the complexity of beekeeping, quarries, or heavy industry.

**Comment by NillerMedDild** [comment]
Maybe, but Sieves would most likely be gated and/or nerfed :)

**Comment by Angular-Angel** [comment]
What about them in particular? I'll admit, having such easy access to all the different plants makes them awfully strong. I would probably cut the drops for all the plants by a factor of like a hundred, but also add in drop potential for various mod plants at the same rate, maybe? So sieves become less a very easy way to get all the seeds, and more of an okay way to get SOME kind of seeds, as long as you're not too particular about which ones.

**Comment by TemperedFool** [comment]
Plant access is already very easy - ultimining grass alone will yield an almost annoying variety of seeds. Exploration (lots of chests in the world have seeds) & the market have it covered otherwise. I bet smarter people than I know of many other ways too!

Basic resources like gravel/sand/clay have a fair number of generation methods already, both tech and magic.

As you already mentioned, Bees/quarries/industry handle lots of ore/gem generation very well, and magic (Mineralis/Orechid to name two) can also cover it.

Personally the only interesting bits are the barrel transform stuff, and I'm not even sure that all is super unique. 

That all said, I don't personally have a huge problem with redundancy, but it's definitely redundant in a world gen pack imo. I would personally take a peek at Create and some of the magic options for handling these things ^_^

**Comment by MuteTiefling** [comment]
If there's anything in particular that you're looking for, recipes can always be tweaked.

What exactly are you hoping to solve by adding this? Is they a particular resource that's annoying to get?

**Comment by Angular-Angel** [comment]
I would actually prefer to cut down on how many seeds you get from grass - as you said, it's annoying, and it feels weird given that's not how most of the vanilla crops work. And mostly I just like the mod - it's nice and simple and fun to use. I mean, I plan to tackle the complexity of Create, Immersive Engineering, Beekeeping, and Botania eventually, but it's nice to have a simple early game source for this stuff.

**Comment by NillerMedDild** [comment]
We will not be adding this, unless it is needed for Expert, which I doubt :)
