### ISSUE TITLE
Suggestion: Fewer Seeds from grass

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1142]
**Description**
So, cutting grass can give you a ton of seeds, and in a ton of different kinds of plants, to the point where clearing an area of grass can become downright annoying. I would suggest that only the grains - wheat, barley, rye, and maybe rice - should drop from grass, and the rest should be found from villages, from chests, and from other sources.

**Why would you like this added/changed?**
Because it's annoying to deal with the seeds you get from clearcutting grass, and it makes it too easy to get seeds.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by r-mc2** [comment]
I think toning down some of the drop rates of seeds could be something, however, removing what seeds drop and turning it into a scavenger hunt for villages/dungeons could add further frustration than you'd solve. And while, true, there is the Market from FFBH, that's a big emerald investment that Niller's sneaky emerald world gen makes difficult early-game 😉 
And take Occultism for example, their Demon Seeds are basically required to start the mod although they're probably the most guilty of having too many seeds drop when you hit that % chance of getting a seed from broken grass.

Also there is always the trash slot in your inventory or void upgrades for the backpack the initial quest gives you 🙂 

Personally, I appreciate the seeds as I like having a big farm plot per veggie so making it harder to find seeds could maybe be something for expert if there's a desire to gate some mod with that seed's product.

**Comment by Angular-Angel** [comment]
Demon Seeds and Industrial Hemp are also good candidates to spawn from grass, as they are pretty much required to enter their respective mods, or at least to progress. For the most part though, you don't actually need all those fancy foods. And you can get a decent variety from the wild farmers delight crops anyway, or just find a village. So it doesn't make the game too much more difficult. Though, adding recipes for seeds from botania transmutation or the ex nihilo sieve would certainly be reasonable.

**Comment by Merlo17** [comment]
Here's my take on this, I would limit the amount of seeds you get from grass to 4/5 important variants, and then tweak the market so that other seeds are super cheap (possibly even paying wheat seeds themselves?)

**Comment by r-mc2** [comment]
> For the most part though, you don't actually need all those fancy foods.

Then should we just remove Simple Farming, Farmer's Delight, Spice of Life, and Cooking for Blockheads? Of course not. You're speaking from your personally preferred play style. That's not going to translate to how others wish to play. Some love making the kitchen and creating all the different foods. Pam's would have never gotten as much traction over the years if people didn't like having the option. And in the end isn't modded about more options? Why go in what feels like a backwards direction?

As for moving them to the Market... 🤔 Maybe if you provided the Market to players in one of the Welcome chapters and informed them of the change. And wheat seeds for other seeds sounds like a fair price if you go that route. Because right now there's the convenience factor to think about as well. Some of us like the idea of walking outside and Ultimining the tall grass and getting whatever you need. Adding the additional steps of hunting them down in villages, trading with villagers, or effectively gating them behind other mods removes that factor. Moving them to the Market is a bit on the side of less convenient too as we're going from "free from any tall grass" to "you gotta menu a bit and buy it", but it's not as bad as it at least has a search bar.

Now that's not to say either play style is "better" there's just what each player is looking for when they boot up a modded Minecraft world and balancing that I feel is one of the harder challenges in a "kitchen sink" like this pack. But I would caution on making things more difficult or shoehorning players into a single direction when trying to simplify other factors (at least before Expert mode is available 😉).

**Comment by msbrittgaming** [comment]
I am "some" lol , I have a big kitchen in my house with all the food and kitchen tools and I love it for roleplaying purposes. I do agree the seeds get out of hand, but maybe some reduced output rate is a nice middle ground.

**Comment by Angular-Angel** [comment]
I mean, vanilla gates all the advanced food behind villages, chests, zombie drops, and the like. It doesn't seem too unreasonable to do the same with some of the advanced mod foods, especially as you'd still have more varieties readily available than in vanilla. And I like collecting all the different foods and making a kitchen too, I just don't mind having to work for it. Like, I started Enigmatica with Enigmatica 2, with Pam's HarvestCraft, where you had to travel to all the different biomes to collect the different foods, and find fruit trees and collect their fruit so you could make your own, and I thought that was just fine. Getting everything from grass seems too easy, though. Like, getting wheat, rye, barley, and maybe demons dream and industrial hemp from grass, and then getting the rest from botania, chests, zombie drops, villages, and other sources seems perfectly workable.

**Comment by r-mc2** [comment]
I suppose my argument here then would be, "Why follow vanilla's lead on progression?"

Modded is all about making other paths and providing alternate routes of progression. If you enjoy exploring the world to find everything perhaps we look into adding seeds to chest loot for those who also enjoy needing to explore the world. But denying another play style altogether to satisfy one subset of players feels like a slight to the other players.

I suppose the concern would bring us back to the main topic of this suggestion, what do we do with all the extra seeds coming from tall grass? Maybe along with the backpack you're given early on in the Storage questline provide also a Void Filter pre-filled with all the seed types with the exception of the 6 or 7 you mentioned above? That way those who want to get it from tall grass can and those who want to explore the world can have the seeds vacuumed into their backpack and deleted so one still has the impetus to go find the seeds out in the world. (And from a balance perspective is there anything OP about granting the player a free void filter?)

Also on a personal note, I hate Botania 😆 please for the love of Notch do not gate anything behind their mana/alchemy transmutations 🙏

**Comment by Angular-Angel** [comment]
If NillerMedDild wants to creep up on the feature, perhaps starting with adding the mod seeds as zombie drops in the same way that carrots and potatoes are, and making sure they can be found in chests (Same way that vanilla seeds are), as Botania transmutations, and from anything else that gives vanilla advanced crops - and then reducing the drop rate for most of them from grass, could be a good experiment, and give us a base for further evaluation.

**Comment by NillerMedDild** [comment]
I decided not to remove any seeds from the pool. I see that this is an inconvenience, but I'd rather leave it be than confuse the casual farmers of Minecraft :P

I reduced the amount of Hemp Seeds that drop by a ton, give or take.

**Comment by NillerMedDild** [comment]
I had a change of heart after realising Simple Farming already offers a pretty good fix for this in the configs.

**Comment by NillerMedDild** [comment]
Not possible at this time it seems: https://github.com/cweckerl/simplefarming/issues/152
