### ISSUE TITLE
Hellish Zombee have no flowers

### ISSUE THREAD

**Issue by soepie7** [NillerMedDild/Enigmatica6#1189]
**Modpack version**
0.3.13

**Describe the bug**
Hellish Zombee have no flower according to JEI. From what I found in the files, I saw this:
All bees use either a specific block (like byg:soul_shroom) or "ALL". Hellish Zombee use "tag:forge:mushroom", and I suspect that this is just not a valid notation in this specific section of a bee .json.

**Comment by Ridanisaurus** [comment]
It seems to be similar to the issue we had with Blaze Bee only accepting `minecraft:nether_wart` instead of `forge:crops/nether_wart`. In a similar fashion, JEI shows the correct flower, but the Bee doesn't recognize it as a valid Bee Flower. I'm asking Epic Oreo and the guys over on their Discord to confirm whether they should only accept hardcoded input per design, or whether this is a bug they need to fix.

**Comment by Ridanisaurus** [comment]
Okay, somehow the obvious has completely skipped me on this one. The Forge Tags are fine, but the issue is that they don't exist on the block itself, which is what the Bee look for when placed in the world. The guys on RB Discord were quick to point out the errors of my ways :D I guess for this one I'll use `minecraft:brown_mushroom` to avoid adding the forge tag to every single mushroom block in the game as a work around, and then maybe look into adding these tags in the future throught KubeJS. I'll PR a fix shortly.

**Comment by NillerMedDild** [comment]
I'll add the block tags :)
