### ISSUE TITLE
replace Simple farming with Croptopia

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#1201]
Croptopia just dropped a forge version and personally i think it would be a good replacement to simple farming
Croptopia Also adds wayyyy more content than simple farming and thats why i think it should be in the pack
https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/screenshots
(i also remember inventory corruption from simple farming and alexs mobs so this will probably fix that)

**Comment by Ridanisaurus** [comment]
Personally, I don't see a point in replacing a food mod with another. I'll try to provide below my opinion in a cohesive list on this subject.
- Between Simple Farming, and Farmers Delight, we have a plethora of food types, recipes, and fun mechanics to provide diet variation to players.
- The textures of Simple Farming are FAR superior than the textures of Croptopia as they feel more flushed out, better shaded, and more Vanilla like.
- Simple Farming offers more than just food and recipes. It has some mechanics such as the brewing and fermentation for potion effects through alcohol.
- Simple Farming trees not only look good, but their logs are quite unique, and provide a good option for builders as an alternative log for detail work.
- ... I could keep on going with why I think this is a terrible mod switch for E6, but the most important of all the above is that it's still an Alpha, and it feels very rough in general. 

Maybe in the future if the above issues are addressed, and it actually offers something new and interesting instead of being yet another generic food mod (as if we don't have enough of these) it could be worth considering.
Anyways, this is just my input on this subject. The final decision will fall down to Niller of course.

**Comment by Merlo17** [comment]
Totally agree with everything Rid said. I've also played around with this for a bit and not only do I not see anything it offers that simple farming or delight don't (wayyyy more content seems very hyperbolic, did you have something in mind besides some specific foods?), but both the mods we have right now offer different mechanics and ideas over just simple crafting recipes. We'd lose content switching for this mod :P

**Comment by NillerMedDild** [comment]
I agree with Rid I'm afraid, thanks for the suggestion but it is a no.
