### ISSUE TITLE
The abyss chapter 2

### ISSUE THREAD

**Issue by Crackthebox** [NillerMedDild/Enigmatica6#1224]
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii

It ads a New cool dimension and a little lore too. I would love it being added to the modpack.

**Comment by Merlo17** [comment]
I've played around with this for a bit and I feel conflicted
One one hand the dimension is really cool and the textures look great, it seems like a fun adventure for those who are into that kind of stuff and it's totally relegated to its own dimension so people who don't want to bother with it can just simply ignore it and go on with their day.
On the other hand some stuff feels a bit... lacking in quality (for example many tooltips have weird spelling and the book itself is fairly lackluster. It also adds custom GUI, and I'm not sure if it can be disabled, I see no config files at first glance.
Some of the loot (if not most) is also pretty much duplicate content of other stuff already in the pack like trinkets and artifacts, so there's likely a lot of integration work to do there on our part. I haven't tested it but the CF page says it supports Tetra so that's nice at least.
Just a few first impressions, I would probably need to play more with it. It deserves some looking into for sure

**Comment by NillerMedDild** [comment]
Two reds flags I see: No issue tracker, and no visible source code.

**Comment by NillerMedDild** [comment]
And no configs for the GUI overhaul, this is a nope :)
