### ISSUE TITLE
Lootr Chests/barrels not appear in the Campsites added by Artifact's mod

### ISSUE THREAD

**Issue by koalalord9999** [NillerMedDild/Enigmatica6#1230]
**Modpack version** 3.13

**Describe the bug**
When you find a rare underground campsite, the barrels that spawn loot in them, do not be Lootr barrels (they exist, I seen in some other structures)

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by Merlo17** [comment]
They don't spawn in eidolon's structures either. As far as I can tell it's only vanilla structures.
I'll investigate and see if we can do something about this

**Comment by NillerMedDild** [comment]
This has been fixed in a recent update of Artifacts :)

Eidolon is still missing Lootr compat though, we need to tell @Noobandius :D

**Comment by noobanidus** [comment]
Eidolon was one of the first mods I made sure I had compat with. Do you have any screenshots of particular structures?

**Comment by Merlo17** [comment]
I do not but I can try and find the world where I noticed this, looking into it

**Comment by Merlo17** [comment]
...I feel real dumb right about now, I found the structure where I noticed this and the chest was an Artifacts Mimic... whoooooops
On the other I noticed that Apotheosis compat is missing (at least I think these structures are from apo?). That'd be nice since they're really common.
![2021-02-06_12 12 42](https://user-images.githubusercontent.com/62080872/107116588-a6de1780-6874-11eb-91d1-56efdf5bec02.png)

On an unrelated note, would it be possible to ERP the mimics to look like lootr chests? It kinda gives the whole mimic aspect away :P

**Comment by noobanidus** [comment]
Artifacts' latest release already has mimic skins in!

I've an open PR to add compatibility to Apotheosis but I believe the developer is quite busy at the minute.

**Comment by Merlo17** [comment]
Wonderful, thanks for the swift reply ^^

**Comment by noobanidus** [comment]
![](https://thumbs.gfycat.com/WeeGenuineJanenschia-size_restricted.gif)

**Comment by Merlo17** [comment]
On this note @noobanidus , Astral Sorcery structures don't seem to have compat either

**Comment by NillerMedDild** [comment]
He already made a PR for that, the AS dev just doesn't have time to merge it atm. See https://github.com/noobanidus/Lootr/issues/16 :)

**Comment by noobanidus** [comment]
@Merlo17 As far as I'm aware HellfirePVP is extremely snowed under right now. The patch exists for Astral Sorcery but I don't know when it will be merged. I've asked him once about it which is about the extent of what I'm willing to pester right now, so fingers crossed it'll be soon!
