### ISSUE TITLE
When Dungeons arise

### ISSUE THREAD

**Issue by Crackthebox** [NillerMedDild/Enigmatica6#1249]
https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise

It ads some structures that I loved living in or just seing in the world.

**Comment by TemperedFool** [comment]
The shader-rific glory shots look pretty ^_^

**Comment by NillerMedDild** [comment]
Looks very promising, will check it out it's marked as 1.16.5 compatible.

**Comment by Crackthebox** [comment]
I am glad

**Comment by Merlo17** [comment]
Minor red flag is the curseforge issue tracker :P

**Comment by theboo** [comment]
slightly less minor red flag is complete lack of any sort of config/toml... tho some of the dungeons are actually quite nice, you cant turn anything off or change spawn weight outside of commands, unless i am completely blind...

**Comment by TemperedFool** [comment]
Worth an issue on their GitHub I think. Maybe it'll be coming as they work on 1.16.x some more? Seems like the current release is pretty new.

**Comment by theboo** [comment]
except they dont have a github xD, only the built in curse tracker... but yes, maybe so

**Comment by TemperedFool** [comment]
Eeeew, no GitHub is probably a bigger 🚩

**Comment by Merlo17** [comment]
> slightly less minor red flag is complete lack of any sort of config/toml... tho some of the dungeons are actually quite nice, you cant turn anything off or change spawn weight outside of commands, unless i am completely blind...

maybe we can with TF magic?

**Comment by theboo** [comment]
they arent made as a normal structure... so dont show up in TF structure configs, and even if it does have datapack support, its not opensource and /gendata seems broken right now

**Comment by NillerMedDild** [comment]
Yikes, will mark as blocked.

**Comment by NillerMedDild** [comment]
Or rather, it will remain blocked until I see improvement in future updates.

**Comment by SQbuilder** [comment]
Update on the mod:

On the latest Release,
- There is now a config file with adjustable structure spawnrates.
- Structure generation now uses Forge's biome dictionary in order to be compatible with modded biomes.
- Multiple new dungeons / structures.
- Waystone compatibility (Waystones spawn in some structures)

On the latest Beta,
- Custom title screen is removed, as it was not configurable before
- Loot tables are more balanced
- (Arguably the most important) Items dropped due to structure generation are cleared in those chunks for better performance.

Other notes,
- I'd recommend testing with the latest beta, as it has performance boosting changes
- There is still no Github :(

**Comment by NillerMedDild** [comment]
I really want to add this, but I don't want the modpack to be have worse performance ._.
