### ISSUE TITLE
Silicon

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1257]
**Description**
add silicon from sand recipe's in crushers i.e. create/mek/thermal

**Why would you like this added/changed?**
material stonework factory gets stuck if it gets full wouldn't mind a different method of silicon that isn't place block down, get silicon

**Comment by Merlo17** [comment]
I'm not super sure what to make of this: the stoneworks factory is the only place in the pack where silicon comes from cobble, while everywhere else it comes from quartz.
I wonder if we should keep the stoneworks recipe at all, it feels a bit out of place doesn't it?

Otherwise, my idea is to make silicon available via crushing create limesand

**Comment by Toonlink264** [comment]
if you take out the silicon from the factory it loses literally all purpose for the work that goes into getting one

**Comment by Merlo17** [comment]
Does it? It's an all in one compact machine to make cobble, gravel, sand, glass and derivate products. Still very useful if you ask me. Compared to the other recipes in the pack it doesn't really make much sense that it can do silicon does it?

**Comment by MuteTiefling** [comment]
Yeah, that seems a little extreme. There's plenty of reason to still make the stonework factory.
