### ISSUE TITLE
Unify Vegetable storage blocks

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1260]
Farmer's Delight and Simple Farming have some overlapping content, namely some crops. I would keep Farmer's Delight variants because they have better textures and storage blocks already implemented. Should be as easy as making the Simple Farming ones unobtainable and hide them from JEI, all the recipes already use tags as far as I can tell and they both share tags

**Comment by r-mc2** [comment]
The only minor note I could think of for this would be making the Advancement from the mod unobtainable. But it's an Advancement, so not a huge loss except to those who really want to go after them, although it could be a point of frustration for someone looking at it and trying to figure out what the, for example, last 3 crops/fruits to get the "grow all crops" bit.

Just a thought, but would unifying them via tag be able to trick the Advancement? e.g. take the tomato, that's in both mods. Could you take the SF tomato's tag and apply it to FD's tomato and get the Advancement to still trigger? 🤔

**Comment by Merlo17** [comment]
As far as I can tell they're fully customizable with datapacks so that's a yes

**Comment by Thiana** [comment]
Crops/plants are often used for decoration so I'd vote against removal for that reason. Leaving them in only adds a line or two to jei.

**Comment by Merlo17** [comment]
Hm fair, but I also find it pretty confusing seeing duplicate plants for the same crop, you would choose one variant anyways. It's extremely niche for decoration at best I'd say.
I'll still wait for Niller to call on this though

**Comment by Thiana** [comment]
I'm not sure confusion is really a factor here since you said they share tags? Just think of them as different cultivars of the plant ;) And while you would choose a single variant for *automation*, for decoration the reverse is true. I often mix similar looking crops/flowers together to make more visually interesting builds. As another example, we often mix different types of stone bricks together in a wall for the same reason but noone is suggesting we remove every variant but one of them :)

**Comment by NillerMedDild** [comment]
I'm unsure tbh, will think on it.

**Comment by Ridanisaurus** [comment]
I'm gonna have to agree with Thiana on this one. While some food items are duplicates, they still have different textures, and different looking crops, which is extremly nice for decorative purposes. As long as they interchangeable in recipes, it shouldn't be an issue. 
This would be similar to having Red Sand, White Sand, Black Sand, and Regular Sand, they can all be processed interchangeably, but they do give builders options to decorate with, and use in their palette. I mean same case can be made for Scoria, Limestone, Slate ..etc. They are all blocks that just added for decorative purposes. If the issue is the naming of the crops, then we can easily change the names to add more interest like instead of having Onion for both, we can change one to be Shallots for example.

**Comment by Merlo17** [comment]
I like changing the names, it will feel much less confusing imo.

**Comment by NillerMedDild** [comment]
Changing names could make recipes using tags less clear though - A recipe wants onions, yet shallots are acceptable. Very minor, but potentially confusing xD

**Comment by Ridanisaurus** [comment]
Agreed. I personally don't mind the name duplication, not all your onions look the same :D 
By the way, brace yourself @Merlo17 Abnormal Mods add quite a bit of duplicate food as well.

**Comment by Merlo17** [comment]
Hurray redundancy! Something more to check I guess :P

**Comment by NillerMedDild** [comment]
My brain head settled on noes.

**Comment by boneskull** [comment]
What about the storage blocks?  

For example, 9 potatoes pack into a Quark _Potato Crate_, a Thermal _Crate of Potatoes_, or a Farmer's Delight _Potato Crate_.  I have a RFTools Crafter packing these, and which one I get seems completely random.  

Given they don't seem to share tags, (e.g., `forge:storage_blocks/potato` or something), it's tedious to automate _unpacking_.  I can't create a RS recipe to take any one of these and create 9 potatoes; I'd have to make 3 separate ones, and RS is dumb about "duplicate" recipes afaict.

Other storage blocks--e.g., IE's _Block of Steel_ can be created by way of a stonecutter.  This doesn't make sense for vegetables, so maybe a recipe where crafting each crate produces a different one: Quark crafts Thermal, Thermal crafts Farmer's Delight, and Farmer's Delight crafts Quark.

**Comment by Ridanisaurus** [comment]
This seems to be an issue that more and more players are encountered. I was asked to add a unified output for this through EE not long ago. It could be worth looking into having only 1 output for the automation purposes. Either that, or having them feed into a Compacting Drawer instead of RFTools Crafter. 
https://github.com/Ridanisaurus/EmendatusEnigmatica/issues/50

**Comment by boneskull** [comment]
Is that guaranteed a certain output?
