### ISSUE TITLE
YUNG's Better Portals

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#1272]
https://www.curseforge.com/minecraft/mc-mods/yungs-better-portals

**Mod description**
This mod aims to reinvent the vanilla Nether portal system. Instead of creating a dumb ol' obsidian rectangle and lighting it on fire, Nether portals now come in the form of Dimensional Rifts, which you'll find scattered deep underground

**Why would you like the mod added?**
This mod would add more exploration and a bit more challenge to the Nether (and potentially other dimensions). Having to find a way into the nether...and then a different way out would add a bit of suspense and the need for more prep to the nether other than just dump some water on some lava and go get all the things.  It also seems it may be able to be used for other dim portals as well, so undergarden and whatever other dims are added in the future.

**Comment by OneLemonyBoi** [comment]
I feel like it modifies the vanilla game too much to be in a Kitchen Sink Pack.

**Comment by Merlo17** [comment]
It's a cool idea but I don't really like it. We already offer tons of stuff to find while exploring, and we're gating some significant content behind the nether, namely anything that requires quartz (RS comes to mind). Doing this effectively forces you to find a portal before you can do any of that, and some players simply don't care about adventuring around the world and finding the portal. With unlucky worldgen, you could be stuck going around aimlessly for thousands of blocks (just look at the astral shrines and how annoying that can be).
It's also just a one time thing, since modded already has teleporters you can set up that would effectively negate the need to find a portal/move it to your place/find it for your way back.

**Comment by theboo** [comment]
Would be amazing in an adventure based pack, but yeah, I don't think it quite fits in a pack like e6

**Comment by Dracos99** [comment]
Maybe when we get to an expert pack and need some more gating :)

**Comment by Ridanisaurus** [comment]
Agreed, it changes the Vanilla mechanic of the Nether portal too much that it will be confusing as hell (pun intended) for new players to figure out what they should to access the dim.
Even in expert, it would say it's out of place. This would work perfectly in an adventure themed Modpack.

**Comment by NillerMedDild** [comment]
I agree with the wild pack of Coollaborators :P
