### ISSUE TITLE
Item Dup Exploit: Mimicubes drop mimicked items if you have the Octopus Leg lost trinket equipped.

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1281]
**Modpack version**
Enigmatica 6 0.3.9

**Describe the bug**
Item duplication exploit:

1. Obtain and equip the Octopus Leg (losttrinkets:octopus_leg) lost trinket, which causes attacking mobs to sometimes drop their weapon, aka the item in their main hand.
2. Find a Mimicube (alexsmobs:mimicube) in an End City in The End dimension
3. Hold the item you want to duplicate, and smack the Mimicube with it, causing them to mimic it. This works with any item, including backpacks and other container items.
4. Let the Mimicube hit you until the Octopus Leg causes it to drop the item. Pick up the duplicated item drop.

The simplest solution I could come up with was for Mimicubes to be blacklisted by the Octopus Leg trinket's effect.

I have not tested it, but you may also be able to duplicate armor using Mimicubes and the Pilfering enchantment on a fishing pole.

**Logs**
n/a

**Screenshots**
n/a

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I have decided to no longer allow Mimicubes to spawn, as the dupe potential is too high :(

**Comment by Elvarion** [comment]
Was about to report the "same" dupe, but in another variant. But found this issue already adressed.
Good thing they are getting removed since the way I found a dupe bug with them is via Astral Sorcery.
There is a perk called **Breaking Aim**, Whenever you deal damage to an entity you have a chance to disarm any worn items.
The execution if the dupe is the same as mouseas.
