### ISSUE TITLE
Crash when rendering Mimicube with Artifacts umbrella

### ISSUE THREAD

**Issue by real-chair** [NillerMedDild/Enigmatica6#1379]
Version 0.3.13

When fighting Mimicubes with an Umbrella equipped, you will be booted out of the game and unable to rejoin the world without crashing.

https://pastebin.com/KMt0cFqC

![image](https://user-images.githubusercontent.com/71352104/108861423-3269df00-75bd-11eb-994b-ba1bd6370b4e.png)
(screenshot of the crash window)

**Comment by Merlo17** [comment]
Might be related to https://github.com/NillerMedDild/Enigmatica6/issues/1281, we have disabled mimicubes because of similar issues to this one should be good

**Comment by r-mc2** [comment]
I think more similar to #1205, but fortunately the Artifacts mod author also fixed it shortly after.

A solution to try and fix this for SSP would be to edit your player .dat file and move your current coords to somewhere far enough away from the mimicube so it doesn't try to render, then change your game to peaceful and slowly wander back over. Once you're back you should be fine to move the difficulty back where you had it previously and unequip the umbrella so you don't risk it again.

It's more of a bandaid, but like Merlo said, it'll be fixed in the next version on both accounts.

**Comment by real-chair** [comment]
Awesome, thank you. I think I'll do something similar and just have my friend join the game and /kill all the mimicubes before his game actually loads them in.
