### ISSUE TITLE
[0.4.0] End cities not generating

### ISSUE THREAD

**Issue by algul** [NillerMedDild/Enigmatica6#1417]
**Modpack version**
[0,4.0]

**Describe the bug**
End cities are not generating or to be more precise are super extremely rare. Most likely all the new biomes just limit potential spawn rates. After hour of flying in creative I found 1 super small "city" with 0 chest, just 4 skulker boxes on pedestals at the top. My save folder is 600MB more just from flying around. End cities should be more common in my opinion. I cant' imagine how long would it take to find one with just a jetpack.

**Comment by Merlo17** [comment]
I've done some very rough testing and this doesn't appear to be true? In a fresh world using /locate I was easily able to locate 4 different end cities in the span of 1000ish blocks in each direction (so from -1000 to 1000), which seems very reasonable. We even made them a bit more common in 0.4 I believe, though not super common since they're still supposed to be a rare structure. @theboo you did the numbers on this one right?

**Comment by algul** [comment]
It maybe be just my perception, it really feels worst than vanilla. But that may just be because the world gen is much slower than vanilla.

**Comment by TemperedFool** [comment]
Pregenerating (/forge generate) might help with that a bit, although given that things are naturally spread out you'll need to generate a lot of chunks.
