### ISSUE TITLE
Non-functional "small" crafting recipe for Compact Crafting

### ISSUE THREAD

**Issue by Mendanbar** [NillerMedDild/Enigmatica6#1430]
**Modpack version**
0.4.0

**Describe the bug**
"Small" crafting recipe for Compact Crafting does not seem to work when using the Common Black Hole unit as a catalyst.  Nothing crashes, the game just doesn't seem to recognize the combination of blocks as valid for creating the machine. The recipe **_does_** function with the Tier 1 Dimensional Storage Stabilizer

**Logs**
N/A

**Screenshots**
![2021-02-26_00 39 17](https://user-images.githubusercontent.com/10580609/109278888-eb066d00-77cd-11eb-946b-587a93d1ed72.png)
![2021-02-26_00 39 35](https://user-images.githubusercontent.com/10580609/109278955-03768780-77ce-11eb-994d-cd77bf1a9925.png)
![2021-02-26_00 40 03](https://user-images.githubusercontent.com/10580609/109278968-0a9d9580-77ce-11eb-8c95-f69fabb26bff.png)

**With the tier 1 dimensional storage stabilizer:** 
![2021-02-26_01 07 49](https://user-images.githubusercontent.com/10580609/109279898-29e8f280-77cf-11eb-8771-cd3658856cea.png)
![2021-02-26_01 07 59](https://user-images.githubusercontent.com/10580609/109280092-6fa5bb00-77cf-11eb-9ff2-27c6c1a74d6e.png)

**Comment by Merlo17** [comment]
that's really weird, I tested those in dev and they were working. I'll look into that

**Comment by Mendanbar** [comment]
Did some more creative testing, and it seems the next tier up ("Normal" size), has the opposite problem.  I was able to build the 7x7x7 structure and use the Pity Black Hole Unit as a catalyst to start the miniaturization, but using the Tier 1 Dimensional Storage Stabilizer I couldn't get the miniaturization to start. Weird.

Also, according to the visual guides on the filed projectors, the largest workable miniaturization field is 9x9x9, which only supports crafting of the 7x7x7 ("Normal") machines and smaller.  I couldn't figure out any way to make a filed large enough to create the "Large", "Giant", and "Maximum" tiers of the devices.  There are a few videos of the older version of the mod on YT, and they all show the "Maximum" tier as being constructed with a much smaller cube... just with different items inside.  I think in E2E the maximum machine had a block of emerald in the center, for example.

**Comment by Merlo17** [comment]
I did some more testing in 0.4.1 and found some pretty weird behavior. Ironically, I get the exact opposite results as you did, the small one works with IF but doesn't with occultism and the normal one works with occultism but not with IF.
Something weird is going on here, but I'm not exactly sure what honestly.

As for the size issue, you are totally right, but the max appears to be 9x9x9. In my testing I tested everything up to 9x9 and then just assumed you could keep scaling up because it let me put the recipes in (and also because I was lazy and didn't want to build a bigger field. whoooops!)

I think we'll be taking a look at these recipes for next version and make them easier and more in line with the standard for e6 normal at least since they still do feel a bit out of place to me. I'll wait for Niller to call on this though. What I would do is keep them 7x7 at max probably using different items in the middle for the tiers and use a single catalyst that hopefully doesn't break

**Comment by NillerMedDild** [comment]
> I think we'll be taking a look at these recipes for next version and make them easier and more in line with the standard for e6 normal at least since they still do feel a bit out of place to me. I'll wait for Niller to call on this though. What I would do is keep them 7x7 at max probably using different items in the middle for the tiers and use a single catalyst that hopefully doesn't break

Yes please, they got a bit out of hand :)

**Comment by Mendanbar** [comment]
Awesome, thanks! Yeah 7x7x7 would be great, because in my testing the recipe would not accept the catalyst unless the field was one block larger than the assembled cube. Even with all the quirks I'm loving the addition of this mod.  Lot's of fun potential.
