### ISSUE TITLE
Ender cells reset energy levels

### ISSUE THREAD

**Issue by Cat656** [NillerMedDild/Enigmatica6#1445]
**Modpack version**
 0.4.0
**Describe the bug**
When the server restarts, the ender cells lose all the energy cells that have been placed in them, making them not work.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by BlueAgent** [comment]
Was also reported to Powah by someone else later on here: https://github.com/owmii/Powah/issues/158
I could not reproduce with just Powah alone though (see my comment with timestampped video).

**Comment by Cat656** [comment]
It's possible it has something to do with updating from 0.3.x to 0.4.0, and thus changing worlds. That's what I had done, before this bug started happening.

**Comment by BlueAgent** [comment]
Well, it could be due to my PR here https://github.com/owmii/Powah/pull/155.
Which fixed servers having channels 2-12 being the same channel, so you effectively only had two channels that you could use.
But... I made sure to keep the NBT reading and writing output the same, but I might have messed something up?

**Comment by BlueAgent** [comment]
Okay yep, it was definitely my PR that fixed 3-12 sharing the same channel as 2.
Should be fixed once https://github.com/owmii/Powah/pull/160 gets merged and released.
