### ISSUE TITLE
Immersive Engineering hammer and Enigmatic hammer usage problem

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#1449]
**Description**
The Enigmatic hammer can make plates out of ingots, but cannot activate multiblocks like the Coke Oven
The Immersive hammer can activate multiblocks, but cannot make plates out of ingots.

**Why would you like this added/changed?**
Both hammers should be able to do both of the things I listed. Or the immersive hammer should be allowed to make ingots into plates again (Not sure why this was changed? Maybe an oversight?)

**Screenshots if applicable.**
N/A

**Comment by Merlo17** [comment]
The enigmatic hammer isn't supposed to be a 1:1 replacement for the IE hammer, since that's also used as a wrench for the mod. Adding this functionality to the EE hammer seems really out of scope for the mod. I'll close this anyways since if you want to suggest this compat it's something for the EE repo itself and not really for the pack

**Comment by RevenantWendigo** [comment]
That's fair. I'm still curious why you can't make plates with the immersive hammer though. Seems really odd. (Unless you could never do that and I'm just crazy? I have only player with immersive a few times though so I can't say for sure).

**Comment by NillerMedDild** [comment]
We disabled the plate crafting in favor of using the EE native hammer :)

**Comment by RevenantWendigo** [comment]
I think that would be a great decision. Feels very weird needing two hammers to do one mod. (Even if one of the uses rarely comes up).
