### ISSUE TITLE
[0.4.1] Energy Genration rate for Thermo Generator does not seem to be in line with others

### ISSUE THREAD

**Issue by phytopius** [NillerMedDild/Enigmatica6#1455]
The Energy Generation rate for the Thermo Generator provided by the powah mod does seem lacking compared to others.
It increases in steps of 10 from 130 to 180.
The nitro Thermo generator (max level) produces 180fe/t  the basic solar panel (min level) produces 220fe/t

Content of the config file  thermo_gen.toml.
```
[Energy_Generation]
        #Range: 0 ~ 9000000000000000000
	starterGeneration = 120
	#Range: 0 ~ 9000000000000000000
	basicGeneration = 130
	#Range: 0 ~ 9000000000000000000
	hardenedGeneration = 140
	#Range: 0 ~ 9000000000000000000
	blazingGeneration = 150
	#Range: 0 ~ 9000000000000000000
	nioticGeneration = 160
	#Range: 0 ~ 9000000000000000000
	spiritedGeneration = 170
	#Range: 0 ~ 9000000000000000000
	nitroGeneration = 180
```

**Comment by TemperedFool** [comment]
@phytopius 

Thermo generator gets to work all night, while the solars don't, so still higher generation over the day. Might be lower than desired, but see: https://github.com/NillerMedDild/Enigmatica6/wiki/Powah

**Comment by phytopius** [comment]
Maybe I can't just take the config values for granted. 
Like described in your github link the power throughput changes depending on heatsource and coolant.
Maybe this is more a visual "issue" rather than a configuration problem.

**Comment by NillerMedDild** [comment]
The values in the config aren't RF/t, they're a magic value that is used to calculate output.

**Comment by hvdklauw** [comment]
The values in the config are FE/t which is the same as RF/t

I think the concern is valid, Nitro tier requires a netherstar, 2 redstone blocks, a blazing block and 20 million FE to create 16 nitro crystals (+ another 810.00 FE for the blazing crystal block) , of which you need 9 to upgrade a basic thermo to a nitro version. For a whopping gain of 50FE/t It's way cheaper to just spam basic ones.

Even with a nitro block under it (another 9 nitro crystals) the difference between the basic and nitro thermo is only 110 FE/t which is less then 1 basic thermo, so intead of upgrading and adding a block below it to make it better you are better off creating a shitload of basic ones.

The top tier solar generates 720FE/t costs 11 nitro crystals and works half the time (normally) So that would equal 360 FE/t on average. Which is still double what a top tier thermo does! 

Let's compare:

Powergen | Base FE | Averge FE Gain | Netherstar costs | FE gain per netherstar | Power spend
--------------|--------------|--------------|--------------|--------------|--------------
Basic thermo | 130FE/t | 0FE/t | 0 | ~ | 0 
Nitro thermo |  180FE/t | +50FE/t | 9/16 | 28,125 | 20.810.000 FE 
Nitro with nitro block | 396FE/t  | +266FE/t | 18/16 | 299,25 | 41.620.000 FE 


Why the hell would I spend netherstars and blazerods for upgrading if I can without spending power just put down 4 basic thermo's and be done?
Sure the cooling is a factor, but the same principle works there, setting up 4 basics generate more power then 1 nitro + nitroblock.

Instead of nerfing it so other powergen options stand a chance, you just nerfed it too far that it becomes totally useless to even upgrade.

I think putting the progressive upgrade back (Basic -> Hardened -> Blazing -> Niotic -> Spirited -> Nitro) and buffing them to give you more to gain then a 10Fe/t
You want it to be worthwile to spend the effort to upgrade

**Comment by hvdklauw** [comment]
Ok, just found out multiple thermo's actually don't work, you can only have 1, same for the solar panel
so wind generator/solar spam it is

**Comment by MuteTiefling** [comment]
Have you looked at the actual numbers in our wiki? Ignoring cooling makes the comparison moot since they don't work without cooling.
