### ISSUE TITLE
Valhesia structures not spawning

### ISSUE THREAD

**Issue by JaguarGunner** [NillerMedDild/Enigmatica6#1487]
modpack version is latest as of 3/1/21

While trying to look at the valhesia structures in a single player world and try to /locate all the structures. All the structures except for the player house say cannot find structures. I tried increasing the gen rate in the config and in The terra forge world customizer but still no luck.

Thanks for your time, its much appreciated.

**Comment by Merlo17** [comment]
/locate is bugged in terraforged and might not show the structures properly (case in point that screenshot lol)
![2021-02-13_23 59 15](https://user-images.githubusercontent.com/62080872/109493145-58472600-7a8c-11eb-8562-fbd39a4ae45d.png)

as for the structures, those can be made more common in defaultconfigs (or save folder/serverconfig for old worlds) but not in TF's menu for some reason

**Comment by Merlo17** [comment]
pretty sure all the valhesia ones should generate actually, but all the other ones have higher weights and don't spawn in every biome so they might feel rarer

**Comment by theboo** [comment]
I think what we need to do here is change the flatness settings on the other structures similar to the player house so these structures can generate in more locations... Maybe add some biomes as well. I'm pretty sure the main reason they aren't more common is that flatness setting though

**Comment by JaguarGunner** [comment]
okay sounds good, thank you guys. I just really like the valhesia structures, this really helps

**Comment by JaguarGunner** [comment]
I will try editing the valhesia structure spawn rate more and see if i can get them to generate

**Comment by theboo** [comment]
So ive done a boat load of testing in like 10 worlds including default(not terraforged) world type and i cant get anything but the player house to spawn... i do know for a fact that i saw castles early on when i was working on terraforged, but now there is nothing... i even crazy boosted the castle... valhesia hasnt updated since october so no clue what changed, ill do some more testing later this week. There are multiple issues on their tracker with people having issues getting their structures to generate.

**Comment by JaguarGunner** [comment]
alright sounds good, let me know how trouble shooting goes, thanks for your time in testing this :)

**Comment by JaguarGunner** [comment]
any news so far?

**Comment by SchwiftyGeez** [comment]
For what it's worth, I was testing this out too and couldn't get anything to generate besides the PlayerHouse either. I tried in both Terraforged and Default generation. But I don't think this specific issue actually has anything to do with the Valhelsia mod itself because I added it to another pack that didn't include it (TNP Limitless 3, 1.16.5) and using Terraforged generation I was able to find all of the Valhelsia structures without issue. I know it's a different pack with many differences from Enigmatica, but I just wanted to share that info in hopes that it might give some insight. 

I would guess that some other mod is interfering with the Valhelsia generation in some way.

Also, I noticed this same issue happening with the DungeonsPlus structures on the Enigmatica pack.

**Comment by theboo** [comment]
Hmmm... I'll have to look at their mod list..

**Comment by JaguarGunner** [comment]
okay thanks for the heads up you guys are awesome <3

**Comment by NillerMedDild** [comment]
Deleting your saves/worlds `serverconfig/valhelsia_structures-server.toml` and restarting should fix this issue :)

**Comment by JaguarGunner** [comment]
YAYYY thank you guys

**Comment by Mendanbar** [comment]
I tried the advice above (deleting toml and restarting the server) and flying around a bit into unloaded chunks.  I'm still only seeing player houses. 🤷‍♂️

**Comment by NillerMedDild** [comment]
Hmm, maybe it's something else we did then as well, hopefully 0.4.4 will do the trick for you.
