### ISSUE TITLE
Simply Jetpacks 2

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#1488]
https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2

**Mod description**
Tiered Jetpacks for Mekanism and Immersive Engineering (and Thermal Expansion (beta))

We have tiers for many aspects of the game and having the same Tiers for Jetpacks seem to be in line with that concept.

**Comment by CletusMAngo** [comment]
Imo the jetpacks from mekanism are really slow but i feel like these jetpacks are a bit OP thats just me tho

**Comment by kitkat498** [comment]
you have flying from pnc and jetpacks from mek

**Comment by Dracos99** [comment]
This is not a discussion of if flight is possible (i know there are multiple modes of flights both tech and magical), but a way to allow various levels of flight upgrades for those that dont want to get into things like Astral to move faster, ars to throw themselves through the air, or creative like angel ring. I am not sure if the speeds/consumption are configurable, but it does tie into and extend 3 mods in the pack with similar functionality around levels of performance.

**Comment by NillerMedDild** [comment]
I'd rather not add this to be honest, I think it's a bit on the bloat-y side.

**Comment by MuteTiefling** [comment]
Thermal style jetpack recipes are all broken since the mod still assumes 1.12 materials. 

Still feels like clutter with all the tiers for every mod. Thermal integration would have to be disabled entirely. Based on the recipes below, the Vanilla ones at the very least should be disabled too. They're way too cheap. 

Base recipes are very cheap. For instance, here's everything needed for a Diamond Jetpack (Tier 3).

![image](https://user-images.githubusercontent.com/9543430/113534637-47179a80-959f-11eb-81d8-9d2067b7b7c7.png)

Netherite (Tier 4) would be a minor road bump getting 14 Netherite ingots.

![image](https://user-images.githubusercontent.com/9543430/113534702-7af2c000-959f-11eb-9113-570e5766f0ea.png)

The Mekanism ones are a bit more reasonably priced, not to mention the infrastructure to get to them:

![image](https://user-images.githubusercontent.com/9543430/113535761-54825400-95a2-11eb-8097-33367f616114.png)

This still feels really easy and I'd have a tendency to want to disable higher tiers because they're very fast compared to other flight options. 

The Immersive ones feel kind of alright. They stop at tier 3 (non creative hover). But they're still blazing fast....

For Comparison:
|                  | Hover (m/s) | Flight (m/s) |
|------------------|-------------|--------------|
| Tier V Jet Boots | 10          | 24           |
| SJ Tier 1        | 10          |              |
| SJ Tier 2        | 27          |              |
| SJ Tier 3        | 50          |              |
| SJ Tier 4        | 85          |              |


So the tier 2 is roughly better than PNC's final flight tier, and just about any other form of flight in the pack. 

I can't get a good read on the starter mek jet pack, but it feels like it's about walking/running speed. The Antimatter one is pretty fast, but... antimatter. 

Unlike previous iterations of this mod, I see no options in the configs to tweak the speed/fuel cost/etc. 

Personally, I'm just not feeling it.

**Comment by TemperedFool** [comment]
I think to balance that you'd need to expert-fiy them, which really doesn't seem appropriate for the base pack.

**Comment by NillerMedDild** [comment]
I agree with Mute, I'll have a look at Iron Jetpacks instead. #1916
