### ISSUE TITLE
Unify Wheat Flour

### ISSUE THREAD

**Issue by alephic** [NillerMedDild/Enigmatica6#1576]
**Description**
Both Pneumaticcraft and Create add wheat flour, but only Pneumaticcraft flour is accepted in the sourdough recipe. It would be nice if Create flour would work in this recipe as well.

**Why would you like this added/changed?**
It seems unintuitive to have two incompatible types of flour in the game.

**Screenshots if applicable.**
N/A

**Comment by NillerMedDild** [comment]
We'll get on that :)

**Comment by Merlo17** [comment]
I would go as far as axing PNC flour all together tbh

**Comment by ochotonida** [comment]
I just noticed pedestals also adds flour. While it doesn't show up in JEI it still has a recipe. 
This would also be a good opportunity to unify Create's and Farmer's Delight's doughs. Farmer's Delight's dough is only used for bread, while Create's also has the slime ball recipe. I'd prefer to keep the dough from Farmer's Delight instead of the dough from Create though, since it's edible and has (in my opinion) the better texture.
