### ISSUE TITLE
Player reporting exit code 0 on mod launch (only this modpack)

### ISSUE THREAD

**Issue by miguetdev** [NillerMedDild/Enigmatica6#1579]
**Modpack version**
0.4.3

**Describe the bug**
User is unable to load launcher and receives an exit code 0 on pressing play from Minecraft Launcher. All other modpacks at 1.16.5 and using forge modloader 36.0.45 run without error. User was able to load modpack successfully with 0.4.0 and 0.4.2.

**Troubleshooting Performed**
- Updated Java
- Updated drivers
- Restarted PC
- Loaded Vanilla 1.16.5 minecraft world with no errors
- Reinstalled E6 to new profile, same error
- Updated and ran All of Fabric 1.16.5 no errors
- Swapped All of Fabric mod loader to 36.0.45 and loaded to menu successfully
- Swapped E6 modloader to 36.0.46 and loaded menu sucessfully. Can't join server due to mod version mismatch
- Swapped E6 modloader back to 36.0.45, exit code 0 in forge early load process
- Compared all versions, config, and launch options to other players

This user is the only one having this issue. All other modpacks with similar versions and modloaders load without error.

![profile](https://user-images.githubusercontent.com/1209079/110254347-d445e000-7f5c-11eb-9cf8-11508adafa6d.png)
![profileoptions](https://user-images.githubusercontent.com/1209079/110254349-d5770d00-7f5c-11eb-87bf-029b38f0a2a8.png)
![launchersettings](https://user-images.githubusercontent.com/1209079/110254351-d740d080-7f5c-11eb-9b4f-33d8c8c71fce.png)
![loadscreen-snapshot-before-fail](https://user-images.githubusercontent.com/1209079/110254979-89799780-7f5f-11eb-8650-842771364a64.png)

**Logs**
[latest (6).log](https://github.com/NillerMedDild/Enigmatica6/files/6097939/latest.6.log)

**Comment by miguetdev** [comment]
JVM Arguments:
-Xmx7616m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\<username>\Twitch\Minecraft\Instances\Enigmatica 6 - E6 - 1.16.5" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

Message @ohcanada

**Comment by NillerMedDild** [comment]
Thanks for the report, please try replacing the JVM arguments with these: 
`-version:1.8+ -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

That being said, in the log it appears that the install of Forge-1.16.5-36.0.45 was faulty. Deleting it from `Twitch\Minecraft\Install\versions\forge-36.0.45` and re-choosing it should fix it. All of Fabric would not have this issue because All of Fabric does not use Forge, it uses Fabric.
