### ISSUE TITLE
Unify rubber & latex

### ISSUE THREAD

**Issue by ochotonida** [NillerMedDild/Enigmatica6#1592]
**Description**
Thermal and Industrial Foregoing both add rubber & latex, but these can currently not be used interchangeably. These could be unified by tagging them or one of the two could be removed altogether.

**Comment by MuteTiefling** [comment]
Been thinking about this one a fair bit tonight and I'm of the opinion that the Arboreal Extractor is probably the more interesting of the two methods of getting raw latex. It would also be considerably less work to convert it over to producing IF latex, rather than converting all IF recipes over to Thermal latex. 

The latex processing machine can stay. It produces 1 tiny dry rubber per 100 mb of latex. Thermal could have a similar recipe implemented in the Still that produces the same quantities. Thermal's regular rubber would go away entirely. It's only an intermediary step for Cured Rubber anyway.

Finally for Cured Rubber, this would no longer be a Furnace recipe at all. The only way to obtain it would be the Induction Smelter recipe with 1 sulfur + 2 IF Dry Rubber = 4 Cured Rubber.

**Comment by NillerMedDild** [comment]
> 
> 
> Been thinking about this one a fair bit tonight and I'm of the opinion that the Arboreal Extractor is probably the more interesting of the two methods of getting raw latex. It would also be considerably less work to convert it over to producing IF latex, rather than converting all IF recipes over to Thermal latex.
> 
> The latex processing machine can stay. It produces 1 tiny dry rubber per 100 mb of latex. Thermal could have a similar recipe implemented in the Still that produces the same quantities. Thermal's regular rubber would go away entirely. It's only an intermediary step for Cured Rubber anyway. Could also just skip tiny dry rubber and do 900 mb to one dry rubber.
> 
> Finally for Cured Rubber, this would no longer be a Furnace recipe at all. The only way to obtain it would be the Induction Smelter recipe with 1 sulfur + 2 IF Dry Rubber = 4 Cured Rubber.

I agree with all of these points, but I also think the "easy" crafting recipes from Vines and Dandelions should stay, for the odd 4 Rubber for one Energy Cell.
