### ISSUE TITLE
Server crash with Integrated Tunnels

### ISSUE THREAD

**Issue by AlabasterAlibi** [NillerMedDild/Enigmatica6#1595]
Modpack Version:
0.4.2

Describe the bug:
Using Round Robin mode on an Energy Importer from Integrated Tunnels can induce a StackOverflowError and crash the server.

Steps to reproduce:
1. Place down a Mekanism Heat Generator, Thermal Series Redstone Furnace & Pulverizer, and a Refined Storage Controller on the four blocks adjacent to a central block.
2. Put a Logic Cable in this central block.
3. Add an Energy Importer to the cable facing the heat generator. Add a blank variable card to the "Import Energy" function.
4. Add Energy Interfaces to the three previous machines.
5. Not sure about this being necessary: wait until all machines are full of energy.
6. Finally, enable Round Robin on the Energy Importer. This should crash the server.

**Comment by Merlo17** [comment]
Would you mind sending the log too?

**Comment by AlabasterAlibi** [comment]
[crash-2021-03-08_17.11.26-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6104852/crash-2021-03-08_17.11.26-server.txt)
Turns out the client is a liar. It's actually a NoSuchMethodError.

**Comment by OneLemonyBoi** [comment]
ok so line of code in question is:
`    public long getMaximumQuantity() {
        return Integer.MAX_VALUE;
    }
`

**Comment by OneLemonyBoi** [comment]
Found issue, localize() doesnt use an integer, it uses a string. This is probably a typo by moddev.
[Override of Localize()](https://github.com/CyclopsMC/CommonCapabilities/blob/master-1.16/src/main/java/org/cyclops/commoncapabilities/ingredient/IngredientMatcherEnergy.java#L94)
[Original Localize()](https://github.com/CyclopsMC/CyclopsCore/blob/master-1.16/src/main/java/org/cyclops/cyclopscore/helper/L10NHelpers.java#L38)

**Comment by BlueAgent** [comment]
I don't think it's a typo.

The [first method](https://github.com/CyclopsMC/CommonCapabilities/blob/409033512468214c500bb2d79a03d57668e95524/src/main/java/org/cyclops/commoncapabilities/ingredient/IngredientMatcherEnergy.java#L93-L95) mentioned above is [implementing `String localize(T instance)` from `IIngredientMatcher`](https://github.com/CyclopsMC/CommonCapabilitiesAPI/blob/333edcb53ea72923a00f78c095df045356903b96/ingredient/IIngredientMatcher.java#L145)

The [second method](https://github.com/CyclopsMC/CyclopsCore/blob/08e3af0d01fe3337115761b2324c1e3754e3796b/src/main/java/org/cyclops/cyclopscore/helper/L10NHelpers.java#L38-L44) is called by the implementation of the [first method](https://github.com/CyclopsMC/CommonCapabilities/blob/409033512468214c500bb2d79a03d57668e95524/src/main/java/org/cyclops/commoncapabilities/ingredient/IngredientMatcherEnergy.java#L93-L95) and has the form:

```java
String localize(String key, Object... params)
```

Which is used correctly as (the varargs parameter will be a zero length Object array (implcit `new Object[0]`):

```java
L10NHelpers.localize("recipecomponent.minecraft.energy");
``` 

The real issue is, afaict, is that the [second method is marked as `@OnlyIn(Dist.CLIENT)`](https://github.com/CyclopsMC/CyclopsCore/blob/08e3af0d01fe3337115761b2324c1e3754e3796b/src/main/java/org/cyclops/cyclopscore/helper/L10NHelpers.java#L37) but it is being called on the server distribution (hence it is missing).

Also, no proper log was posted, and the crash report sent doesn't show the issue (NoSuchMethodError is mentioned but the crash report doesn't mention that???)
So I tried to reproduce it following the steps in the OP but could not do it (yes, I was using a dedicated server).
[debug.log](https://gist.github.com/BlueAgent/dfb4ed4ed50d012e877a2a762b760865)

**Comment by NillerMedDild** [comment]
The mod dev already fixed it \o/
