### ISSUE TITLE
Blame the Performant

### ISSUE THREAD

**Issue by Normal69** [NillerMedDild/Enigmatica6#1626]
Howdy?

Just two mods for easier running, if you haven't encountered them.
I would be happy if you can write anything bad about them too.

Blame, a really good log detail mod - you need only activate it when you are searching for problems:
https://www.curseforge.com/minecraft/mc-mods/blame

Performant, which improves performance:
https://www.curseforge.com/minecraft/mc-mods/performant

Have a nice day.

**Comment by Merlo17** [comment]
Blame looks interesting but I'll leave it up to the smarter people in here to look at it. Performant however was blocked because of a number of issues, such as https://github.com/NillerMedDild/Enigmatica6/issues/633, and also it being a bit unreliable and breaking stuff from other mods, mostly related to entities afaik. Since it is a server mod you can just add it on a server and try it yourself I guess, but it's probably not going to be in by default

**Comment by NillerMedDild** [comment]
No to both, I don't think Blame has any place in the pack, looks like it should be used for development/debugging only. Thanks for the suggestions though.
