### ISSUE TITLE
Make Tetra more usefull.

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1692]
**Before you start reading this, i want to say:**

* This is general concepts. Ideas to think of. Not a "please, add it now!!" and not essential for most of modpack players things.
* This enhancements can be done for expert mode, as it seems too much for common E6.
* This changes can completely revamp difficulty curve of the modpack.
* This will be hard to implement. I'm sure of it. But it can lead to something good imo.

**Description**
* **TOOLS**

I think modpack needs complete tool rebalancing around Tetra tools to make this mod more preferable in most cases of tool chosing.

For example in some other modpacks, other mods-own tools and vanila ones is 1 durability and only for crafting.
I've seen that thing realised with Tinkers construct, but i think it can work with Tetra too (with some balance changes to materials and their characteristics ofc, and with adding harder recipes for other modpacks OP tools)

Or maybe just rebalance Tetra materials at least.

* **(Expert)Other mods crafts**

If its even possible.
Maybe add custom recipes of some things on Tetra benches and forges to make them wrapped around Tetra, To make progress in modpack dependable on Tetra progression.

* **Use Tetra in Further Updates**
 
Using Tetra Hammers to obtain Dense ores from veins, for example. Or for prospecting. (not sure if its possible)

**Why would you like this added/changed?**

* Tetra requires much effort to do not so good tools.

* Tetra have almost no use in comparison to other modpack's mods tools, even vanilla ones is not more worse than their Tetra analogues. Not even mentioning other imbalance tools such as bores, hammers, excavators, disassemblers, PAXELs, AIOTS etc. 

* With Apotheosis, Tetra tools is more useless, since they cant be enchanted as good as any common tools.

* I cant see why i can use Tetra, except doing quests, after getting to first good tool. (in my case its Ref. Obsidian PAXEL from quest reward)

P.S Sorry for bad english, if i'm speaking not clear enough in some cases. Working on improving it.

**Comment by Merlo17** [comment]
There are a few things that concern be about focusing everything around Tetra

- for starters, players just don't seem to enjoy it that much. now clearly I can't prove this universally and it's still a matter of taste, but from interactions on discord it seems the majority of people (myself included) finds it clunky to use and overall just not really enjoyable. you could point to a number of different things that make the mod feel worse, and maybe one of them is tools not having enough functionality to make them worth it, but I don't think that's the only factor.
- tinker's will come eventually (it seems fairly close actually), and it's most likely going to be added to the pack. it's hard to judge how things will evolve when it comes out because we don't know how it will look like yet, but if (and it seems likely) we end up keeping both mods in the pack progression should be focused around both, so that's something we need to wait for before touching everything in tetra

**Comment by MuteTiefling** [comment]
I do think tetra could use another balance pass. The tools seem to break very fast compared to their counterparts (that could just be in my head, haven't done empirical testing). 

Enchantability stats could stand to go way up considering we can easily drop all the enchants on a traditional tool. And quite easily with eidolon, I should add.

If possible, lowering the break points for leveling them up would be a wonderful addition. Like, fewer mob kills needed to hone a sword, for instance. Especially since these stats are lost as parts are swapped. 

Consider raising the 'quality' stat. I've forgotten the name right now, but the one that determines how much you can add to a tool. There's a pretty big disparity between say...a leather handle wrap and a dragon sinew one. Bringing the lower tier stuff up a bit would help with building better tools early on. 

I think we might still have some high end materials that can't be added due to forge hammer level requirements. I haven't checked that, but it seems like these come up commonly in discord with no resolution. 

Things that we can't control but that could really use enhancements :

The material display in the manual is terrible with as many materials as we have. It shouldn't be extending off screen to the right like that. Breaking to more than two lines would be a great start. A filter would be another great addition. 

More _positive_ bonuses on tool parts. I think these were in the works, but I don't recall correctly.

**Comment by Merlo17** [comment]
Something like https://www.curseforge.com/minecraft/mc-mods/tetraits if it ever gets ported?

**Comment by MuteTiefling** [comment]
That would be nice yeah

**Comment by NillerMedDild** [comment]
Even if Tetraits gets ported it will not be added, the things it added are now vanilla Tetra. Tetra can be easily (I think) extended upon through mods, that's probably part 1 of 2 we need to do here.

So the plan for the 3rd rebalance/buff imo (feel free to come with other suggestions)
- Generate all JSONs for all Tetra materials, including ones we didn't add ourselves, through KubeJS. KJS has a json.write function that should serve this purpose. This will allow us to make changes based on modifiers, so buffing all durability by say, 50% would be a very simple action.
- Buff all durability by 50% 😄 
- Make a Tetra addon mod that introduces basic traits that we can add to most materials

**Comment by boneskull** [comment]
agree with everything here. as it stands, Tetra is too much stick and not enough carrot. I'd love to have a reason to use it, cause the idea is really great--but it all needs buffs. More than you think, probably. 🙂

**Comment by AdamNisbett** [comment]
For what it's worth - I've enjoyed Tetra a lot more than the Tinkers of the past (not sure if Tinkers will be updated with the new version to change my opinion) and the biggest thing keeping me from using it more is the fact that there's a huge imbalance in the enchantability of the tools.  I'm generally limited to just a few enchants on the tetra tools before the enchantability stat gets used up while with the various enchanting options provided by other mods, I can end up far outpacing a tetra tool.  The fact that enchants get wiped whenever a tool is upgraded is also a huge downside in comparison to enchants on other tools which can be stripped with PNC and reapplied to an upgraded tool. If trying to balance tetra against other mods, I'd recommend increasing the enchantability significantly (at least for some top tier materials), and either adding a method of removing enchants or preserving them when components are upgraded.  Not sure if those things can be done in the modpack or if it would need to be done by the mod, but just thought I'd share my thoughts, as I have enjoyed Tetra in general and would be kind of disappointed to see it replaced with Tinkers unless that mod has been notably changed for the better.

**Comment by Muuge** [comment]
As a temporary solution that'd be easy to implement via datapack: why not add some moderately hard to obtain, mid-game material that isn't locked by another mod's progression tree to be used in the socket/ misc upgrade slot for tetra tools that just has an insane amount of enchant-ability? 

If the tools had near limitless enchantability it should hypothetically allow players to get their tetra tools to be on par or close to on par to some of the alterantives.

**Comment by SQbuilder** [comment]
Im guessing it's still too early to tell if 1.16 Tinkers would replace/coexist with Tetra, as Tinkers is still in alpha. Has any testing been done comparing the weapons/gear of the two mods yet (to see if one is overtly over/underpowered compared to the other)?

**Comment by NillerMedDild** [comment]
First round of buffs is in the PR update ^, 20% more durability and magicCapacity for all materials.
