### ISSUE TITLE
PNC Minugun Tweak?

### ISSUE THREAD

**Issue by BlueStriker101** [NillerMedDild/Enigmatica6#1735]
**Description**
Discord name: Maxwell

I'm unsure if I am the only one to notice that the minigun from Pneumaticraft is... Just plain bad. I've been told that there are configs for it's damage as well as other aspects. I believe that at least the rate of which it damages should be upped, if possible. Its a minigun, it should behave like one to some extent. Other than that, if there's a way to improve or change the potion ammo, it would actually make it useful. I did some testing and I figured that the potion ammo would have at least a decent chance at applying potion effects *on top of regular bullet damage*, but that's not the case. Potion munitions do not affect mobs whatsoever unless the potion should decide to proc, which is extremely unreliable.

**Comment by MuteTiefling** [comment]
Couple things here: 

First, we're already boosting it next update. If more boosts are required, that can be arranged :D

Second, in your testing how was your minigun upgraded? Speed and Dispenser upgrades have a massive impact on the total damage per second. And I can say that even pre-buff explosive ammo can take care of the Wither pretty quickly. It's pretty nice for the Gaia fight too. 

Potion ammo is a bit of an odd beast since potions themselves are a bit... lacking compared to other options of damage. They are, however, great for other uses, like healing a friend, applying weakness, or other non damage debuffs. There's also no config to alter their damage, only their proc chance.
