### ISSUE TITLE
Powah thermo gens, wider range?

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1737]
Using water, with magma heat source, you get 156 fe/t from a basic thermo generator, but 216 from a nitro generator. Basically just making another lower tier generator is always going to be better than upgrading these things for using water coolant. I'd say maybe nerfing the lower tier ones so each tier up has a bigger boost, without buffing the nitro might be good? The low tier ones are basically free power, so 156 is still pretty high for chea basic power. Maybe starting around 40-50 would be better? (and not make other passive gens like waterwheels obsolete too)

With non-infinite coolants it's a different matter though, as the small difference becomes a large difference with the huge multipliers, but if the current nitro is kept the same and the others all get nerfed, it might not be much of an issue to change them? Otherwise the bonus from better coolants could be toned down a bit, while buffing the higher tiers base rate (along with nerfing the low tiers) could work, as long as you can change the coolant effectiveness for just the thermo generators without also needing to rebalance other cooled reactors.

**Comment by MuteTiefling** [comment]
Alright, so let's first define where I see these being used: As standalone power for a small automation out in the field. 

Could you do wireless instead? Yes. But if you want something that's independent of your main grid and capable of running small amount of machines, these are your guys. They're really nice on a server, for instance, if you're setting up a public space that needs a bit of FE. 

They're not intended to run a base, other than an early one. 

The range on these was intentionally narrowed, and with good reason. The low tier ones with only water generated absolutely useless amounts of power, while the upper tier could easily run most of a base without issue. The goal here was to make the lower tier options viable for early game, with the intent that the player move to better power sources, like a reactor, mid to late game. The upper tier variants still put out decent energy, but as noted above, they're more for specialized use cases than general power. 

As for the coolants, it's true I-C honey isn't renewable fast enough to run one right now, at least not without a looot of bees. That has been changed, however, and I-C bees are going to generate a lot more honey in the next update, effectively extending the life of these generators into early mid game. Ether Gas is also renewable, though it was never intended for these. That's why they're capped around where I-C Honey's multiplier ends. 

Changing the Coolants will also have an impact on Reactors, unfortunately. These were made to be slow late game power, but very efficient. You'll get a fair bit more energy out of a bar of uranium in a nitro reactor than you will with Mek's Fission, just at a lower rate. With the nerf to Ethylene, something else needed to fill the power gap to allow people to run the machinery necessary to get into Fission and Fusion. These reactors fill that gap nicely.
