### ISSUE TITLE
[0.4.3] some BetterEndForge plants missing some recipes

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1754]
**Modpack version**
0.4.3
**Describe the bug**
bushy_grass and blossom_berry_seed are missing the pink moss soil in botany pots. Pink moss isnt valid as a botany pot soil at all.

blue_vine_seed and glowing_pillar_seed only have insol recipies, but should be able to work in a pot or cloche from the looks of the plant (with end_mycelium/amber_moss soil respectively)

bulb_vine_seed also only has an insol recipe, but the plant grows upside-down, so maybe makes sense to only grow in insolator?

helix_tree_sapling uses plain dirt as soil in the cloche (it uses amber moss in the pot).

small_jellyshroom and umbrella_tree_sapling doesn't give logs and caps in the botany pot, but do in the cloche and insol. and the small_jellyshroom requires end stone instead of jungle_moss in the cloche

**Comment by MuteTiefling** [comment]
Regarding Blue Vines, vines were intentionally left off of botany pots and cloche due to there being no good render to apply. they looked rather terrible. Similar for the glowing pillar dudes.

Shrooms of all sorts were also intentionally done this way. Botany pots only get you the basic shroom, whereas cloches and insolators get you the big shroom outputs similar to a tree. 

The soils appear to all be oversights. Looking into this now.

**Comment by MuteTiefling** [comment]
Took a second look at blue vines and glowing pillars. They've been reclassified internally to render the 'top' as they grow. It's not wonderful, but it does make this purely decorative block more accessible.
