### ISSUE TITLE
[0.4.3] Repeated Server Crashes

### ISSUE THREAD

**Issue by BreadDisease** [NillerMedDild/Enigmatica6#1798]
Hello,

I've had multiple server crashes on the latest version [0.4.5]. I attached three of my crash logs. Hoping to hear if there's anything I can do to fix the issue.

Thanks

[crash-2021-03-23_17.58.32-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6193851/crash-2021-03-23_17.58.32-server.txt)
[crash-2021-03-23_21.56.29-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6193852/crash-2021-03-23_21.56.29-server.txt)
[crash-2021-03-23_22.03.15-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6193853/crash-2021-03-23_22.03.15-server.txt)

**Comment by NillerMedDild** [comment]
Huh, that's an odd one. It looks like the crash is caused by an anvil here : `Level spawn location: World: (377,70,-4401), Chunk: (at 9,4,15 in 23,-276; contains blocks 368,0,-4416 to 383,255,-4401), Region: (0,-9; contains chunks 0,-288 to 31,-257, blocks 0,0,-4608 to 511,255,-4097)`

You can remove the block at `377,70,-4401` to remedy the issue most likely. Updating to 0.4.5 may also help.

**Comment by Darkere** [comment]
:D That's the spawn. And the world is saved in ANVIL format.

From what I understand entities are being removed wrongly by something? Any ideas on that?

**Comment by BreadDisease** [comment]
`337, 70, -4401` is indeed the world spawn. I updated my server to 0.4.5. I'll update if I have any more crashes.

Thanks

**Comment by NillerMedDild** [comment]
Sounds good, I marked this as Awaiting Information so it'll auto-close in case you have no more crashes :)

**Comment by BreadDisease** [comment]
Haven't had any crashes since updating the server. Thanks guys
