### ISSUE TITLE
[0.4.5] Mod Conflict or bad update (RFTools/FtBChunks)

### ISSUE THREAD

**Issue by Syrasar** [NillerMedDild/Enigmatica6#1809]
0.4.5

**Describe the bug**
The RFtools Builder no longer works in Claimed chunks you get a break is cancelled displayed from the builder which worked fine pre update and works fine the momemt the FtBchunks Claim is removed 
Conclusion if no mod update happened something might be wrong with the fake player for the builder

**Comment by NoobGamerHD** [comment]
That's a well know thing, don't worry the fix is simple: add the builder to your team using FTB Chunks, i think you know where the "allies" button is located there, right? if so, just add it, it's called "rftools_builder", after you do that, i'm sure that the problem should be solved and the builder will be able to "grief" blocks in your claimed chunks.
