### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by Jan-aka-q0** [NillerMedDild/Enigmatica6#1829]
https://www.curseforge.com/minecraft/mc-mods/bpm

Blueprints is an all in one automation solution for Minecraft. It supports GUI based node programming so anyone can create powerful automated tasks without any prior programming knowledge. In a matter of seconds automate transfers between containers independent of each other, create mob grinder, and so much more! This mod is in a very early stage and will have many more bug fixes and features to come! (May overlap with ID but in my opinion this is better)

This mod will make automating everything way easier. It is sadly still in beta so it'll take some time before it can actually be used

https://www.youtube.com/watch?v=MVYv4rHcPow

**Comment by sciguyryan** [comment]
I love this mod. I absolutely adore it and have been using it in my personal pack.

But... it seems like it could outright invalidate most of the other automation options in the pack, completely. They are completely outclassed as it is virtually a one-size fits all option for automation.

Just my thoughts on it.

**Comment by MuteTiefling** [comment]
This is -really- cool. But way too powerful. 

Highlights:
* Limitless transfer of items, fluids, or energy (no more need for any sort of logistics)
* Limitless range
* Limitless internal storage (no more need for any storage, just put it in a buffer node)
* Zero cost. You build a single singularity and you're done. as long as it's chunk loaded you can automate everything from this one spot. No upkeep. Nothing. There's essentially no way this single block could be made expensive enough to warrant it's existence. 

Want to farm the Ender Dragon? No problem. It'll place the crystals to spawn her and then do 1000 damage per tick to anything in a 100 block radius. And of course, it could easily automate the creation of said crystals with a Ghast Spawner and an auto crafter from another mod. And setting all this up is trivial at best. 

But the worst part, I think, is that it completely takes away any satisfaction of automating anything routing pipes, finding throughput limits, etc. I've already seen complaints in the past of 'crafting simulator 9000' directed at AE2 and RS since you tend to just stare at the grid after a while setting up new patterns. This is that, but worse. You're in the singularity block all the time setting up new connections and you only ever look out for brief moments to click a block to set a new link.

**Comment by NillerMedDild** [comment]
Will not be added due to it's power level, thanks for the suggestion anyhow.
