### ISSUE TITLE
[0.4.7] Pedestal quests issue

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#1831]
**Modpack version**
0.4.7

**Describe the bug**
The quest give you a backwards linking tool for having a linking tool, this is pointless as you can turn the one into the other by simply sneak right clicking in the air.

I suggest you give us an upgrade tool instead which allows us to inspect the state of pedestal upgrades

**Comment by TemperedFool** [comment]
My probably-too-subtle thought was that I always want two anyway - one to live in my RS system for autocrafting purposes, and one to carry around. That was probably too cute without an explanation. 

Upgrade tool isn't a terrible idea - I'll think about it, since hopefully Niller will get a break and not have to put out 0.4.8 anytime soon...

**Comment by NillerMedDild** [comment]
>  I'll think about it, since hopefully Niller will get a break and not have to put out 0.4.8 anytime soon...

That did not age well :P

I changed it to the Upgrade Tool in-dev, hope that's alright Tempered :)

**Comment by NillerMedDild** [comment]
Scratch that, I changed it to 3-9 Gold Ingots so it doesn't complete the Upgrade Tool quest.

**Comment by TemperedFool** [comment]
Yeah, no issue. I may swap this for a loot box, but I'll just figure it out and do it in dev when I have a second.
