### ISSUE TITLE
More Wiki Entries

### ISSUE THREAD

**Issue by JeanRdSz** [NillerMedDild/Enigmatica6#1898]
I would love some questline involving some of the best ways to generate energy, not limited to the ones that is already in the specific mod questline

That works either as a guide, as suggestion or simply a tutorial for the players

**Comment by telemenar** [comment]
Having a meta section that is basically a list of mods with different common things:
Power Generation
Quarrying
Ore Generation
Spawners/Mob Farms
Enchanting Tools

Might actually be good idea or maybe I could just make a wiki page about it...

Wiki page would kinda be nice because it could be an easy response in the discord.

**Comment by ManiacRobertWasTaken** [comment]
Enigmatica Patchouli Book

**Comment by TemperedFool** [comment]
If we don't want to do hub quest pages for things like power, this does sound possibly appealing - but mostly if it can tie into the Wiki that Mute is already knocking out of the park. Not sure if patchouli can do that?

**Comment by Rodg88** [comment]
I think quests will be more accessible, as people playing the pack may not have/find the discord or the wiki, and even in discord we can say 'look at these quests' instead of linking to a page. otherwise the wiki is nice tho, maybe a link to the wiki in the quest book is a good solution?

**Comment by TemperedFool** [comment]
I'd want to see more than just links; it would be nice if a patchouli book can use content from a GitHub wiki.

I do agree that some hub quest pages may make sense, at least in my mind.

**Comment by MuteTiefling** [comment]
No trouble adding these to the wiki. That doesn't mean they can't also be represented in quests in some way, however. And indeed, some are. 

Powah gets it's own section. Mek gets quests dealing with Ethylene, Fission, and Fusion. Dynamos from Thermal are covered, at least in an introductory sense. The Mycelial Reactor is also covered in the Industrial Foregoing section.

So, short of a bit of a meta section with a short blurb, I'm not sure what else would fit in the quests for power. Its a limited medium for doing detailed walkthroughs, which is why I'm spending the time in the Wiki to begin with. That's much more conducive to a walk through for people who have no idea where to start. Similarly, for the rest, we can probably work in some blurbs to direct people more clearly to the various quarrying/oregen/spawners/enchanting.

I'll probably start work on the following in the wiki shortly: 

Quarrying
Ore Generation
Spawners/Mob Farms
Enchanting Tools

In addition to the following planned articles: 
IF plastic
Thermal Rubber
