### ISSUE TITLE
[0.4.8] insightful crystal recovers exp

### ISSUE THREAD

**Issue by Tyrokas** [NillerMedDild/Enigmatica6#1938]
**Modpack version**
0.4.8
**Describe the bug**
Unlocking slots from lost trinkets with exp (also works with enchanting items at the enchanting table) then right-clicking the item "insightful crystal" from Thermal Series
-> gives back the exact amount of exp back to the crystal
doesnt matter if the item is in the hotbar or not

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by mouseas** [comment]
Can confirm. Using the Insightful Crystal to absorb xp immediately after consuming xp puts the amount of consumed xp into the crystal. Basically refunds the cost 100%. Probably caused by using experience points interchangeably with levels.

E,g, if the calculation for experience points to add to the crystal is `expPointsBeforeAbsorbing - convertLevelsToExpPoints(levelAfterAbsorbing)` and the `expPointsBeforeAbsorbing` value is stale from before using xp for something, we'd see exactly this result.

**Comment by NillerMedDild** [comment]
Looks like the Insightful Crystal is under general investigation: https://discord.com/channels/399037120930512897/434101214548852746/824123479707484171
