### ISSUE TITLE
Bigger Reactors

### ISSUE THREAD

**Issue by RogueLogix** [NillerMedDild/Enigmatica6#1956]
**CurseForge Link:** https://www.curseforge.com/minecraft/mc-mods/biggerreactors

**Mod description**
Big Reactors 0.5.0, 6 years late.

**Why would you like the mod added?**
~~*Gimme all them points.*~~ 
In more seriousness, its a mod that a lot of ATM6 players really like, and the 0.5.0 coolant overhaul has been mostly completed with a beta on curseforge. While its not exactly ready to outright replace the current 0.4.3, its close enough that I thought I would open a new issue to re-examine ER2/BiR being added.

Obviously there is a competator in the form of Extreme Reactors 2. While I am biased here, BiR has some signifiant advantages over ER2 from a packmaker's perspective.

 - Phosphophyllite performs orders of magnitude better than ZeroCore2, so given the same limits causes significantly less lag during reactor/etc construction/deconstruction.
 - BiggerReactors has a far more extensive config, allowing for many of the magic values to be tweaked to your liking to best fit your modpack.

Oh, Rid also did the new textures for BiR, *soooooo.*

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by MuteTiefling** [comment]
I'd say Extreme Reactors isn't the only competition.

Remember we already have Powah reactors for early to mid game power. These cover most everyone's power needs with ease and allow people to step up into Mekanism fission and finally fusion.

Ignoring content overlap for a moment, what niche would these fill? Do they, like mekanism, create useful by-products? And by useful I mean by default and not just for more power. Does it present a new crafting mechanic in the form of custom fuel and byproducts? 

I'd be happy to take a look, myself. I'm just still a little on the fence, largely due to overlap without a sense of anything unique.

**Comment by RogueLogix** [comment]
BR/ER fill a different niche in gameplay. Powah reactors are all identical, and while mekanism's have more complicated fuel creation, the reactors themselves aren't very configurable (just pick a size and checkerboard). With big reactors it's main niche is configurable reactors/turbines and now heat exchangers too. Complex fuel cycles and meltdowns planned, but neither will be implemented for a while still.

**Comment by MuteTiefling** [comment]
JEI Integration is better than before but Cyanite Reprocessor has none. Might seem odd, but people search JEI by how to make something. Even if the name is obvious, it will be overlooked if they search recipes on Blutonium and come up empty handed. Fuel progression is unclear. How do you obtain ludicrite, or is that creative only without pack tweaks? Doesn't seem like it since it's used in default crafting recipes... What's liquid Obsidian for? Irradiated Steam? How do you obtain them? Is Sodium the only fluid for the heat exchanger?

No documentation on building the machines. What do the parts do, exactly? Lay out the rules for what does what and what goes where. Was able to muddle through and get a reactor/turbine setup doing 52k FE/t... but cannot figure out the heat exchanger at all. Like I've got 4 ports on this thing because it told me to, but they're all forced to 'input' mode and some of them are outputting stuff if I run steam into it?

No in game documentation on what any of the numbers mean, which means it's back to trial and error for the player. Build it, wait for it to stabilize, check numbers, shut it down and try again in a new configuration. But do I want to add more X? Remove a bit of Y? No clue, since I don't know what influences what. 

Confusing Turbine GUI. Rotor Efficiency always says 100% even when my flow rate was clearly causing power output to drop. No indication what Rotor Capacity is. Just have to kind of wing it till you're at 1800 rpm?

As for being 'dynamic' in game, this feels like it will largely become a 'solved' problem very quickly on how to run efficiently and generate high power. There's not much difference then between it and Mekanism other than an illusion of choice.  For example, at a glance I can't see why I'd ever use anything other than Electrum > Enderium > Ludicrite for turbine coils. And cost isn't really a justification. If you can build one of these, getting ore is no longer a challenge most likely. Seems to be the case with Moderator blocks too, but I don't exactly know what all of the numbers mean, which is confusing as a player and makes customizing it a guessing game from a dev standpoint.  Still, seems like Liquid Starlight or Enderium are best in class... And starlight is dead simple to obtain in large quantities early on.

I don't see any way to define new moderators/coils or alter their properties either. None of them are registered as JSON data packs. There's no reference to them in the bigreactors-common.json5 and no server config. Am I missing something? And as for the configs that I am seeing, I'm not seeing a whole lot to influence FE/t. We can cap the max sizes, sure. And we appear to be able to make them more or less efficient with the FuelUsageMultiplier. But that's it. 

I know I seem really critical of this. I want to like it. I really do. I'm yearning for a customizable reactor similar to NuclearCraft. This feels similar but it's sorely lacking in the player experience department. Yes, NuclearCraft needed an external calculator to really take a deep dive into it, but at least it was very clear in game how all the pieces went together. You could build yourself a decent reactor without external tools if you just sat down and learned the rules. It certainly wasn't perfect either though.

**Comment by RogueLogix** [comment]
The JEI integration is being worked on, some parts of it proved to be harder than expected, so they were left out of the first beta.

Documentation has been one of BR's largest problems for a loooooing time, and it is high on the priority list to get better documentation written. 0.5.0 is the version that has been waited on to actually go and write the documentation, as it introduces significant changes and new mechanics that aren't otherwise documented. As a prime example, the heat exchanger.

The turbine gui is a bit weird, but probably won't be changing, it makes sense when you know how the turbine is behaving.

Somehow, BR hasn't really been solved in the last 7 years, at least, not based on basically all of the reactors I see built. They usually are all built different for one method of thinking or another, even to this day. By contrast, Mekanism ones are almost always basically identical.

The moderator and coil values do need to be gone over, and the process for that has been started, but it's not done yet, so they are still as out of balance as they have been for the past number of years.

All of the moderators, coolants, and coils are registered as json data, one of the many things that isn't, documented is how to add/modify them. Similar for the config, there is a plethora of hidden by default config options, but how to use them and what they do isn't yet documented.

**Comment by MuteTiefling** [comment]
> All of the moderators, coolants, and coils are registered as json data, one of the many things that isn't, documented is how to add/modify them. Similar for the config, there is a plethora of hidden by default config options, but how to use them and what they do isn't yet documented.

I'm kinda used to these not being 'documented' per se, but I can always tease them out of a mod by extracting them from the data files. didn't see them last night, but I've found them now in the ebcr and ebest folders. Not being registered as recipes, however, does mean (and someone else can correct me on this) that we cannot inject them with a KJS script easily. Not like we've done with so many others, however. It pretty much requires us to re-write and override individual JSON files which is... less than ideal when making sweeping changes.

**Comment by ochotonida** [comment]
> Not being registered as recipes, however, does mean (and someone else can correct me on this) that we cannot inject them with a KJS script easily

I couldn't find it documented anywhere (lol), but you can actually still add and overwrite JSON files with kubeJS even if they're not recipes (see the advancements I did for the zoology challenge tasks for an example). Things like input/output replacements are still out of the question of course, and I don't think it's possible to properly remove files either (apart from replacing them with empty ones)

**Comment by MuteTiefling** [comment]
We can add json overrides, yes. But we have to do it as individual files. Can't write a script that can alter them all at once

**Comment by ochotonida** [comment]
That's actually what I meant, you can add/overwrite files with a script, pretty much identical to how custom recipes are done. The advancements I added had way too many conditions to write manually.

**Comment by MuteTiefling** [comment]
Alright. I'll take a look at how you did that. Have some other things in mind that would be helpful for.

**Comment by NillerMedDild** [comment]
> Alright. I'll take a look at how you did that. Have some other things in mind that would be helpful for.

Tetra? 😄

**Comment by MuteTiefling** [comment]
> > Alright. I'll take a look at how you did that. Have some other things in mind that would be helpful for.
> 
> Tetra? 😄

Was thinking more the random cobble gen >.> but it'd probably be huge for tetra too

**Comment by NillerMedDild** [comment]
Random Cobble Gen is made through loot tables, which should be supported by KubeJS

**Comment by NillerMedDild** [comment]
At the moment this is a maybe, JEI integration and additional documentation would help a lot. I'll mark this as blocked and re-evaluate when Bigger Reactors is a bit more fleshed out :)

**Comment by RogueLogix** [comment]
Closing as I've moved primary development to 1.17, will re-open for E7/E8 when applicable
