### ISSUE TITLE
The Weirding Gadget

### ISSUE THREAD

**Issue by SuperKnux** [NillerMedDild/Enigmatica6#1962]
---------------------------->

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/the-weirding-gadget
**Mod description**
This is like Chicken Chunks or FTB Utilities chunk loading, but makes it so after 7 days of the player being offline, the gadget turns off. This also works with multiple players.

**Why would you like the mod added?**
I feel this would be a great way to chunkload with not being able to be offline for too long. It probably has a config for setting the time, but I haven't checked yet.

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, but I'm afraid this is a no.
This will not be added because:
- We have a similar feature (FTB Chunks chunkloading turns off when the player goes offline)
- https://github.com/AtomicBlom/WeirdingGadget/issues/27
- The mod is not marked as 1.16.5 compatible (I know it probably is, it's just annoying to have to hack it into the pack)
