### ISSUE TITLE
Wither farm Wiki

### ISSUE THREAD

**Issue by JeanRdSz** [NillerMedDild/Enigmatica6#1993]
I was thinking, and would be really good if a tutorial in **how to do a Wither Boss farm** was added.

I don't think there's many ways to do this, as long Wither Builder isn't present in the modpack. So, just adding it to the wiki like Powah automation, is a good option.

**Comment by MuteTiefling** [comment]
There are actually a lot of ways to do this. 

Botania and Nature's Aura both have ways to place a block on another pre-defined block (for example, lay out the wither horizontally on hardened glass (heads) and rebar concrete (body) so they have two different blocks to target.

Create Deployers will build them too, since they can place through blocks (hardened glass containement chamber).

RFTools will straight up spawn them for you (covered in mob spawning article).

Then there's shenanigans with other builders like Modular Routers, PneumaticCraft Drones, RFTools Builder.

Killing is covered quite well already too and several of the methods listed will deal with the Wither without issue. Actually, writing this I realize I forgot one :D

I'm not against it, strictly speaking, but the how to section has largely been for more basic subjects. People stay away from things like Botania, Nature's Aura or PneumaticCraft because they don't understand the power systems well enough. So by giving tutorials for those basic subjects, it opens a whole mod to those folks who might have ignored it otherwise. 

Killing a wither is, on the other hand, a bit more of a limited subject. It's a challenge for players to put together everything they've learned from other mods, rather than a barrier to entry.

**Comment by JeanRdSz** [comment]
I've tried with modular routers, but for some reason the placer module doesn't work everywhere :/

**Comment by MuteTiefling** [comment]
That sounds like claimed chunks. You'd need to ally them
