### ISSUE TITLE
[ModpackVersion] Short_Bug_Description

### ISSUE THREAD

**Issue by Sabejikira** [NillerMedDild/Enigmatica6#2002]
**Modpack version**
Enigmatica6-0.4.8.zip
**Describe the bug**
I went to take out my diamond backpack magnet and I accidentally swapped it for an ultimate energy cube and it crashed the server.
**Logs**
Input Pastebin link to crash-report or `latest.log`, if applicable.
[crash-2021-04-16_19.52.08-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6328314/crash-2021-04-16_19.52.08-client.txt)

**Screenshots**

**Comment by P3pp3rF1y** [comment]
This is fixed in version 1.16.4-2.2.8.234 of  sophisticated backpacks - basically there was a bug there that allowed non upgrade items to be swapped into upgrade slots. The fix doesn't remove the incorrect item from the slot only prevents anything but upgrade from getting in there, but I am actually going to add a bit of code that will remove the invalid items from there when the backpack is loaded.
