### ISSUE TITLE
Can Heat pipes be made to function with Mekanism liquids?

### ISSUE THREAD

**Issue by AbsorbingSafe11** [NillerMedDild/Enigmatica6#2063]
**Description**
I was attempting to chill my Heat Frame (from PNC:R) and one of the the best for producing cold is Mekanism liquid Hydrogen. However, normal heat pipes from PNC:R  don't seem to work with the Mekansim liquids. (Compressed Iron Blocks work fine)

**Why would you like this added/changed?**
The guide book from PNC:R suggest that the heat pipes are the best way to transfer heat/cold and it would save quite a bit of compressed iron. (also the set-up should be viable in the expert mode for plastic production)

**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
In my tests, this does work with heat pipe, but not very efficiently.

When cooling with in world fluids, you actually want to use heat sinks. 

Place a machine, stick a heat sink on the machine, and then place the liquid (or solid) coolant against the fins. This transfers far more effectively. And of course, you can use heat pipe to get more heat sinks into that configuration. Imagine, for example, a rod of heat pipe going down into a pool of water with heat sinks on all sides.

**Comment by MuteTiefling** [comment]
One point to clarify, perhaps. Heat pipe is the best way to -move- heat/cold within a system without losing it. To move from a Vortex Tube to a Machine without having that vortex tube directly connected to the machine, you'd use Heat Pipe instead of Compressed Iron Blocks, for instance. 

But you're looking to move heat -out- of your system (by bringing the temp down). Heat sinks are the best way to do this, and they can be improved by adding extra cooling to them. Either with solid/liquid coolants in world, or with an Air Grate pointed at them.
