### ISSUE TITLE
Productive Bees seem to duplicate or spawn a LOT

### ISSUE THREAD

**Issue by kartoffelsaretasty** [NillerMedDild/Enigmatica6#216]
**Modpack version**
Issue first encountered in 0.2.5, persisted after updating to 0.2.8 and now 0.2.14 (skipped any versions inbetween)

**Issue**
Productive Bees spawns a lot of solitary bees which shouldn't ever be in a big group like that. Unsure whether it is a spawning or duplication issue.

Pictures:
https://i.imgur.com/smrpAao.png
https://i.imgur.com/HFmcnUA.jpeg

**Logs**
[latest_client.log](https://github.com/NillerMedDild/Enigmatica6/files/5147062/latest_client.log)
[latest_server.log](https://github.com/NillerMedDild/Enigmatica6/files/5147064/latest_server.log)

**Comment by NillerMedDild** [comment]
Yikes! I think the issue is that bees can reproduce on their own, I've suggested a config to disable that ability.

**Comment by NillerMedDild** [comment]
This issue should happen less and less now, a fix was made some time ago, but I believe old spawned bees aren't removed by the fix. So new worlds would not see this issue, as I understand it.

**Comment by Darkere** [comment]
When was the fixed version added? I think I've seen this too often since.

**Comment by NillerMedDild** [comment]
Can't remember tbh - The groups of bees were caused by bees leaving their hives and going off into into unloaded chunks, and then never dying. They should now die off after 10 minutes.

**Comment by Darkere** [comment]
Well. If they go into unloaded chunks they don't tick... and don't die.

**Comment by NillerMedDild** [comment]
@JaisDk I hope you don't mind the ping. We're experiencing the issue with groups of bees piling up in `productivebees-1.16.1-0.2.5`.

Darkere raised the point that entities in unloaded chunks don't tick. Could that be preventing your stray-bee fix from working?

**Comment by JaisDK** [comment]
Yea, they need to tick to die. I was hoping they would not make it to unloaded chunks in those 10 minutes, but I suppose I might have to lower it a little or make it configurable.
I could also look into keeping them around their spawn nest instead of running off.

**Comment by Darkere** [comment]
Let the Bee remember their spawn nest and "unlock" a new spawn when they die maybe? That way you could limit the number of bees that can spawn from one nest.

**Comment by JaisDK** [comment]
The way it works now is that each nest have up to three eggs, one being added everytime the inhabiting bee brings pollen. Once the nest has three eggs the parent bee will die and the eggs will start hatching in sequence. I'm guessing the first one to hatch will inhabit the nest if another nearby bees has not done so already.
The rest of the offspring will inhabit other nearby empty nests (if any) or otherwise fly around for 10 minutes until they die.

The purpose of this mechanic is to allow the spawning of so called cuckoo bees. They have a chance to spawn from eggs of a different bee type. This is mimicking nature where these bees will lay their eggs in the nests of other bee species and then have their offspring provide for by those bees (just like the cuckoo bird).

I think the best solution is to have the bees stay near the spawn nest so they will die instead of collecting outside the loaded area since they will also only spawn if that nest is loaded.

**Comment by AdamNisbett** [comment]
Hehe, not sure if this is related, but I've been using a spawned house structure (I think it's from the Valhelsia Structures mod) as a base and after adding a bunch of hives nearby I later returned to my house and discovered around 10 bees that had somehow gotten themselves stuck in the attic and it was like a swarm had infested the place.  Not sure how they got themselves in.

**Comment by JaisDK** [comment]
Bees have a tendency to fly through things like door and solid blocks (blame vanilla mc), but if your attick bees return regularly then one or more of the wood blocks in the construction might have been replaced with a bee nest. Bee nest placement should happen after structure generation, but I can't be sure all mods follow that.

**Comment by AdamNisbett** [comment]
Yeah, I think you must be right about one of the structure blocks being a nest as since posting I heard sounds of bees entering an leaving a nest when in the house (and the hives I'd placed were too far away to hear).  I didn't find any bees in the attic again though until shortly after noticing a swarm kinda like the one described in this initial post go by outside.  They managed to get themselves all into the attic too.
![AtticInfestation](https://user-images.githubusercontent.com/9061144/91988868-6c84b300-ecf5-11ea-8be4-3fbe1692d7ca.png)

**Comment by JaisDK** [comment]
It's not the worst thing to find in the attick :) What is strange though is that they have pollen. Do you have flowers up there?

It also looks like I need to take a look at preventing any solitary bee from entering whatever solitary nest they want. Crystalline and slime bees don't really belong in wood nests :p

**Comment by AdamNisbett** [comment]
Yeah, it actually made for an interesting but somewhat realistic problem.  I've heard people suggest termites for modded minecraft, so swarms of bees moving into an attic is along a similar pest control problem.

No, no flowers up there.  When they were going by it seemed like many were being pulled along by the swarm.  Is there any way there could be something that is causing bees to be linked with a leader and follow where he goes? So then if one bee enters the attic nest, the rest get pulled into the attic with their pollen from outdoors?

**Comment by JaisDK** [comment]
Child bees follow a parent bee just like cows, so most of them were probably not fully grown. In the newest release I've changed solitary bees so they don't follow an adult. The bee infestation you are having are not really solitary bees and will not die off on their own so you might have to find the nest :)
