### ISSUE TITLE
Mob Spawners wont work (cannot find and farm blazes for advancement) 

### ISSUE THREAD

**Issue by nakarumadra** [NillerMedDild/Enigmatica6#2258]
**Modpack version**
Enigmatica 6 0.4.13
(server issue)

**Describe the bug**
All vanilla mob spawners (like ones located in the nether or in dungeons) do not spawn any mobs

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![mob spawner](https://user-images.githubusercontent.com/12505342/119386582-5a84df00-bc8d-11eb-9930-cb0602e43f23.png)

**Comment by NillerMedDild** [comment]
Erhm, silly questions but: Is the server set to friendly difficulty, or is mob spawning off?

**Comment by nakarumadra** [comment]
> Erhm, silly questions but: Is the server set to friendly difficulty, or is mob spawning off?

Difficulty is set to normal, mobs in general do spawn though.

**Comment by NillerMedDild** [comment]
Cool, I'll try to reproduce it then, thanks.

**Comment by nakarumadra** [comment]
Here is a video I uploaded of the issue, it takes over 1 minute to spawn 1 mob at a time but i figured it should be much more (either in amount or in terms of frequency). https://www.youtube.com/watch?v=4kCPAQu7fmM
also my server is located at nakaru.enviromc.net if you want to see the test in game

**Comment by MuteTiefling** [comment]
Well, you haven't exactly got a lot of valid spawn spaces there with the walls and the light. This seems pretty normal to me.

**Comment by nakarumadra** [comment]
i thought mob spawners for the most part override passive mob spawn rules

**Comment by MuteTiefling** [comment]
Vanilla spawners still have spawn rules, and even though Apotheosis overrides some aspects, they still obey those criteria.

1) Hostile mobs need specific light levels
2) Passive mobs need grass to spawn on
3) Slime only spawn below a certain Y level 
4) For each spawn attempt, It checks x number of random blocks in the spawn radius. If those few blocks it checks are valid spawn spaces, it'll spawn, otherwise that attempt is lost.
5) Only X mobs of the same type are allowed in the spawn area before it stops spawning. These can easily be out of sight in those dungeons, behind walls, etc.

A spawner that only has a 5x5x5 area of air blocks to attempt to spawn in will spawn far fewer mobs than a spawner with the full area open. Any light sources will diminish or even halt spawning by reducing the number of valid spawnable areas.

As a test, take the spawners out (move them with silk touch or a cardboard box) and place them in a nice 11x7x11 open area with no light. How to they behave there?

**Comment by NillerMedDild** [comment]
Ahem, got a bit ahead of myself there, sorry :P
