### ISSUE TITLE
Pack Not Loading

### ISSUE THREAD

**Issue by Merthew** [NillerMedDild/Enigmatica6#2283]
**Modpack version**
![image](https://user-images.githubusercontent.com/23420800/119757655-413d8780-be73-11eb-8e7c-0eae537c40e3.png)

**Describe the bug**
The game never loads, it gets stuck either on this screen:
![image](https://user-images.githubusercontent.com/23420800/119757868-99748980-be73-11eb-956a-011a2a8928f5.png)

Or this one:
![image](https://user-images.githubusercontent.com/23420800/119758151-11db4a80-be74-11eb-8e37-4cbd96790bb4.png)

**Logs**
There was no crash so here is the latest.log file
https://pastebin.com/umpzeea9

**Comment by Dissssy** [comment]
try messing with or changing your java launch arguments, it looks like its getting stuck on one of the atlas things which ive seen certain java arguments make extremely slow before, im pretty sure it would load if you gave it enough time, but my solution was always just to use no jvm args

**Comment by Merthew** [comment]
> try messing with or changing your java launch arguments, it looks like its getting stuck on one of the atlas things which ive seen certain java arguments make extremely slow before, im pretty sure it would load if you gave it enough time, but my solution was always just to use no jvm args

I'm currently using CurseForge and it seems to set the jvm args automatically, Ill see if there is any way to change those, but I am not sure what to change them too. I know one of them is allocating memory and I'm pretty sure that has to stay.

**Comment by pm065** [comment]
> try messing with or changing your java launch arguments, it looks like its getting stuck on one of the atlas things which ive seen certain java arguments make extremely slow before, im pretty sure it would load if you gave it enough time, but my solution was always just to use no jvm args

No JVM arguments is not a good idea, but you can do what you want I guess.
The arguments I use are `-version:1.8+ -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -d64`, essentially the same as the E6 recommended args but without one extremely ill-advised one that makes the game unplayable and spawns a ton of memory leaks. @Merthew go to the Curse settings in the bottom left, click Minecraft, scroll down to 'additional arguments' and copy and paste these args in. Does it work?
Alternatively, use MultiMC which only has the problem of being a nightmare for pack devs to work since you can't add individual mods. It allows you to set JVM args per-instance and globally.

**Comment by Darkere** [comment]
The G1GC Garbage Collector always runs in the background (something like every second or so). What the argument does is disable scheduled Full Garbage Collection cycles that would run every minute causing lag spikes. This means that these are delayed until memory actually becomes full, and a full cycle is actually required. 

I guess I could see this causing issues if you are really struggling for memory (memory leaks?), but in general it will improve the experience.

**Comment by Merthew** [comment]
Alright, well I got it to load up once by reinstalling the JVM and going from there, I am currently generating a world so I haven't checked it again, but that may have fixed the issues.
