### ISSUE TITLE
JEI max columns set to 9, causing usability issues on large monitors

### ISSUE THREAD

**Issue by TheDeviantCrafter** [NillerMedDild/Enigmatica6#2346]
**Modpack version**
0.4.14

**Describe the bug**
In jei-client.toml, MaxColumns is set to 9. On 1080p monitors and GUI scale 3 this fills up most of the available space, but on a 1440p monitor it takes up half the space it could. This makes JEI take twice as long to navigate.

**Logs**
N/A

**Screenshots**
My standard UI scale of 3:
![image](https://user-images.githubusercontent.com/18755309/120741359-89cff300-c4ba-11eb-9ede-3d69e5a49975.png)

UI scale of 1 just for fun:
![image](https://user-images.githubusercontent.com/18755309/120741385-95231e80-c4ba-11eb-99dd-c982c1acdb48.png)

**Comment by NillerMedDild** [comment]
You are free to change that yourself, that config does not get overriden, nor does it come with the modpack :)

**Comment by theboo** [comment]
if anyone wants to know why the config default was changed to 9(it was 100 prior allowing it to just maximize space), read here:

https://github.com/mezz/JustEnoughItems/issues/2353

This also helps with issues in other mod's GUIs like ftbQuests and a few others at certain GUI scales where clicking something in a menu also clicked the item in jei behind it bringing up that item recipe instead of what u wanted
