### ISSUE TITLE
Astral Sorcery Vicio Attunement negates PneumaticCraft Boots Speed

### ISSUE THREAD

**Issue by TheAndrata** [NillerMedDild/Enigmatica6#2362]
**Modpack version**
0.4.14

**Describe the bug**
Just attuned myself to Vicio in Astral Sorcery and, as soon as the ritual completed, I no longer received any speed boost from my Pneumaticraft boots. I tried unequipping them and reequipping them and well as adjusting the boost given but nothing worked.

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it :)

**Comment by desht** [comment]
Speed boost from the boots?

Are you talking run speed here, or jet boots flight speed? Because it's the leggings which give a run speed boost, not the boots. And the boost mechanic is completely different for the two cases, so this is an important distinction.

**Comment by desht** [comment]
Also (assuming we're talking about run speed here), can you test if Vicio also interferes with the speed boost from the Botania sashes (Sojourner/Planestrider/Globetrotter)?

I ask since the sashes actually use the same mechanic as the Pneumatic Leggings to speed the player up.  I'm not sure how AS Vicio handles it, but certainly sounds like there's a conflict there.

**Comment by desht** [comment]
And another update!  I just added AS to my test dedicated server instance and gave myself Vicio attunement via commands.  It works absolutely fine with both the leggings run speed boost and jet boots flight (turns out tier 5 jet boots is a very fast way of building Vicio exp... :)

But I'm not seeing any problem here.  Works for me.

**Comment by TheAndrata** [comment]
Let me do a bit more testing and report back. I do have video of it as it happened while I was recording but I’ll close out my world and reopen and see if that solves it. It *feels* like my sojourner’s sash isn’t working either but I’ll test it out and see. 

Also good note on the fact that it’s the leggings that give speed, I definitely mixed the two up.

**Comment by TheAndrata** [comment]
Annnnd reloading the world solved it. Sorry to be a bother!
