### ISSUE TITLE
Server crashes upon player joining.

### ISSUE THREAD

**Issue by TheTripe** [NillerMedDild/Enigmatica6#2420]
**Modpack version**
0.4.14

**Describe the bug**
Server crashes upon joining. It's not consistent. I can usually join without a problem immediately after starting up the server, but it crashes if I leave and try to reconnect.

**Logs**
[crash-2021-06-15_17.45.34-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6659186/crash-2021-06-15_17.45.34-server.txt)

**Comment by Darkere** [comment]
This crash can happen when RS doesn't "like" some fluid tanks or their removal. If you are able to join disabling the fluid external storage and not using it in combination with that tank should get you going again. 

This will be fixed in 1.9.13, which would already be out if not for some issues on Curseforge's side.
