### ISSUE TITLE
[0.5.0] Igloo chests are still vanilla

### ISSUE THREAD

**Issue by surfacelevelspeck** [NillerMedDild/Enigmatica6#2484]
**Modpack Version:** 0.5.0

The chests in the underground area of igloos is still a vanilla chest, instead of a lootr chest.
![2021-06-20_17 11 00](https://user-images.githubusercontent.com/17912442/122689806-08cb6800-d1eb-11eb-88cb-13c3eac57069.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MVethana** [comment]
Not able to reproduce.

First 3 screenshots from Latest 0.5.0 Dev
https://user-images.githubusercontent.com/17278251/123114413-47d90380-d40d-11eb-9f18-671a2c84023e.png
https://user-images.githubusercontent.com/17278251/123114751-8a9adb80-d40d-11eb-9d48-47290a7bae1a.png
https://user-images.githubusercontent.com/17278251/123115329-07c65080-d40e-11eb-9857-75114887742b.png

This is from 0.5.0 master
https://user-images.githubusercontent.com/17278251/123117042-6b04b280-d40f-11eb-9816-4aef6b6f69b3.png

Doesn't really make sense for vanilla structures really since Lootr injects a structure processor. Was this a multiplayer server? Was it possible another player broke and replaced the chest. Do you have the seed and coords?

**Comment by yagoplx** [comment]
Wasn't able to reproduce this one either, checked a few igloos
