### ISSUE TITLE
Gravestone new mod not placing curios item slots back, removing items and corrupting player data

### ISSUE THREAD

**Issue by tincopper2** [NillerMedDild/Enigmatica6#2496]
**Modpack version**
0.5.0
**Describe the bug**
change in mod causing more problems than solutions
the new mod change is not helping any players using any curios items (eg backpack) and instead attempting to place curios items where they DO NOT belong (the inventory)

**Comment by theboo** [comment]
The current grave mod is a temp solution due to the previous one literally yeeting people's gear into oblivion on a regular basis with no way to restore at all, and no resolution from the mod dev in sight... We have another grave mod in the works coming soon that will work perfectly, including curios AND cosmetic curios :)

**Comment by yagoplx** [comment]
Turns out the curio situation can be problematic; but, there's something that you can do as a player (or ask server staff to do) if you lose your curios to this specific bug.

I'm here because I just had my curios (inculding my backpack full of stuff) go into a fire after breaking the grave. Fortunately, if you go through this, you'll need:
* Admin command permissions (eg. Open to LAN -> Enable Cheats)
* Your obituary

Sneak right click the obituary to get the restore inventory command for that death. If you lost your obituary and can't get it back, the death ID will not have been logged to the logs, so your items will remain lost. Which is what happened to me. What a bummer...

Btw, have you guys tried this one? https://www.curseforge.com/minecraft/mc-mods/corail-tombstone? It adds some non grave content so isn't as simple as you might have wanted.

**Comment by MuteTiefling** [comment]
We have something in the works.

**Comment by tincopper2** [comment]
> We have something in the works.

why did he set status to wont fix?

**Comment by Trostmm** [comment]
Cause they won't fix this particular issue w/ this mod, It'll probably be replaced w/ something else.
