### ISSUE TITLE
0.4.13 Wither builder bug[Industrial Foregoing]

### ISSUE THREAD

**Issue by TheOnlyMann** [NillerMedDild/Enigmatica6#2535]
**Modpack version**

**Describe the bug**
For some reason this happens: cant describe what exactly happening
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
https://youtu.be/n31oQYqgiZI

**Comment by TheOnlyMann** [comment]
as for some kind of explanation... it seems like the wither builder places the skulls wrong when the area is claimed...?
with no already placed skulls it'll try to place skulls, but only the sound plays, nothing changes
but, when you have some skulls already on top, it will spawn in a wither, without consuming the skull.

**Comment by NillerMedDild** [comment]
Please update to 0.5.0 and check if it still happens :)

**Comment by TheOnlyMann** [comment]
> Please update to 0.5.0 and check if it still happens :)

as the server uses 0.4.13, cant do that in my side. the bug itself is consistant in 0.4.13, so if anyone would test this bug out in the latest version that would be a good thing

**Comment by yagoplx** [comment]
Can reproduce in 0.5.0

But it only happens if you change FTB Teams from allies to private otherwise this doesn't happen. And yeah it doesn't consume the items. If you change the mode back to allies or public it will cease to happen.
![Screenshot_20210625_161303](https://user-images.githubusercontent.com/57966308/123474482-66d3c300-d5d0-11eb-85d5-3eb4c60c1201.png)

**Comment by NillerMedDild** [comment]
Actually that was a bad take from my side, please ignore support bot.
