### ISSUE TITLE
Tetra axes can't be used to craft sticks

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2551]
**Modpack version**
0.5.2

**Describe the bug**
Trying to use a Tetra axe with logs or planks to craft sticks does not work. This applies to both single- and double-headed axes.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/123547177-08d5e580-d760-11eb-83f4-39f902555403.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. We're aware of the issue, but aren't certain if we can do anything about it tbh.

@mickelus, could you add tags to tools to specify their type? `forge:tools` + `forge:tools/axe` for example

**Comment by mickelus** [comment]
Item tags are unfortunately not nbt aware, so I can't pass `forge:tools/axe`  as a tag if the item has an axe head module. I've got item predicates that are easy to use for testing that kind of stuff, is that something you can use in recipes?

**Comment by NillerMedDild** [comment]
Nope, we can't use item predicates I'm afraid :(

**Comment by mickelus** [comment]
I can help you set up workbench actions for turning logs and planks into sticks using an axe, if you'd like that as a workaround

**Comment by NillerMedDild** [comment]
No thanks, seeing as there's no JEI integration I don't think that would be used sadly :/ thanks anyway!

**Comment by ochotonida** [comment]
Farmer's Delight's tool ingredient serializer might be able to fix this, it matches any item with a specific tool type.
Instead of
```json
{
  "tag": "forge:tools/axe"
}
```
you'd just use
```json
{
  "type": "farmers_delight:tool",
  "tool": "axe"
}
```
This should even work with tools that use energy instead of durability. I'm not quite sure whether items like that would play nice with the recipe type though, looking at #2550.

**Comment by yagoplx** [comment]
Maybe we should also have an "uncertain fixability" label as well

**Comment by NillerMedDild** [comment]
fixed in-dev, recipe will be on the cutting board in the future :)

**Comment by ochotonida** [comment]
Did you check for conflicts :p? I believe Farmer's Delight already adds log -> stripped log recipes on the cutting board

**Comment by NillerMedDild** [comment]
It does indeed, for vanilla and Abnormal mods, I forgot to remove them initially ^^'

**Comment by NillerMedDild** [comment]
Damn, this doesn't work for Tetra tools still ^^' I guess a workbench recipe would be the way to go

**Comment by ochotonida** [comment]
The problem seems to be that you're still using a tag ingredient :p
https://github.com/NillerMedDild/Enigmatica6/blob/47b907718aceb2d6fd4c5384c929b0ef9629a944/kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/farmersdelight/cutting.js#L117
The ingredients for the other recipes in those scripts could probably be updated to use tool ingredients as well, apart from knives, since not all knives from all mods have the knife tool type.
That being said, replacing the log stripping recipes still doesn't seem like the greatest idea, since it's the only way to obtain Farmer's Delight's tree bark. (also I like me my easy stripped log recipes :0)

**Comment by NillerMedDild** [comment]
Ah I see, I tried with 'axe' initially, but that failed. Now I know it failed due to a typo in the mod name though :P

**Comment by NillerMedDild** [comment]
Hm, still doesn't work with `tool: "axe"`

Error:
```
[21:53:23] [WARN] Error creating recipe farmersdelight:kjs_4imfwzx2h49ki22ph1ty090j4[farmersdelight:cutting]: {"type":"farmersdelight:cutting","ingredients":[{"item":"minecraft:acacia_log","count":1}],"tool":"axe","result":[{"item":"minecraft:stripped_acacia_log","count":1},{"item":"farmersdelight:tree_bark","count":1}]}: com.google.gson.JsonSyntaxException: Expected tool to be a JsonObject, was "axe"

**Comment by NillerMedDild** [comment]
That does indeed work, thanks again ochotonida! It doesn't use durability on Tetra or Tinkers axes though, but I'll happily take that over not working at all.
