### ISSUE TITLE
[v0.5.2] Warped Gardens Generating on Land

### ISSUE THREAD

**Issue by GeoTerra** [NillerMedDild/Enigmatica6#2563]
**Modpack version**
v0.5.2

**Describe the bug**
It would seem that the pack is generating the Warped Garden structures on land. I've had several worlds like this since updating to 0.5.2. I even reinstalled to make sure it wasn't config tomfoolery.

Biomes Affected (Will update as I find more):
Blossom Highlands

**Comment by theboo** [comment]
That's the glass balls in the ocean right?

**Comment by Larandar** [comment]
I myself found some really close to land but none on land (close enough that the top get out of water)

**Comment by yagoplx** [comment]
Cannot reproduce as of 0.5.2
I searched a brand new world by teleporting randomly around and using /locate to find warped gardens, but couldn't find them on land ever. I also searched all quadrants (x,-y , -x,-y, etc), to no avail. 

So maybe this could be some kind of world seed weirdness (specific to some worlds, which would explain why the world i tested had none), or just luck

Some warped gardens generated at the beach but didn't go on land

![2021-06-28_15 14 25](https://user-images.githubusercontent.com/57966308/123698377-7b17fa00-d834-11eb-9791-df0657b3949a.png)

Having the top sticking out of the water seems common with these structures, few were fully submerged even on deep oceans so it's probably intentional
