### ISSUE TITLE
Mo' Structures (Forge)

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#2592]
---------------------------->

https://www.curseforge.com/minecraft/mc-mods/mo-structures-forge

"Our goal is to be the best structure mod in the Fabric ecosystem, NOW PORTED TO FORGE! Mo' Structures is carefully designed to bring interesting lore to your Minecraft World.  We focus on the RPG aspect of your world rather than an aesthetic one. This means we add Dungeons, Towers, Lore, and much more! Using loot tables, advancements, jigsaws, unused bosses in vanilla, and more, we are able to bring thousands of new experiences that will make this mod be a must-download for every mod gameplay."

It is a nice fabric structure mod ported to forge, it has a lot of unique structures that really add more flavor to mc.

![image](https://user-images.githubusercontent.com/56084328/124042862-c9b1c980-d9d7-11eb-998d-ea30ed1eb303.png)

![image](https://user-images.githubusercontent.com/56084328/124042871-cddde700-d9d7-11eb-9f69-d5f3c8b61be3.png)

**Comment by Tyler-Jarret** [comment]
I would put my two cents in for this mod. When playing Fabric packs it's always amazing to come across one of those villager trading towers. (Mostly because early game it helps with some insta-iron. I also like that it _is_ vanilla friendly. 

Regarding this modpack. Iirc it has a _lot_ of generation and structure mods to add diversity. Especially dungeon crawls (some of the most fun things to do).

If approved yay! If not, I will always see it added in other packs :p but I honestly love anything that can use vanilla assets in new ways and still make them feel _vanilla_ ya know?

**Comment by yagoplx** [comment]
The pack has repurposed structures and it does feel quite vanilla. We even already have ships generating in the pack like that, and jungle pyramids too. Maybe the content would clash and become redundant, you know what i'm trying to say?

**Comment by NillerMedDild** [comment]
It looks awesome, but we're already covered on the structure front I'd say :)
