### ISSUE TITLE
[Mod Suggestion] Ars Magica 3 (Mana and Artifice)

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#275]
This mod is still in alpha. I felt like I should post this to inform you of the return of Ars Magica (rebranded as Mana and Artifice) if you weren't aware, also to track the progress and stability of the mod to be added to the pack in the future; as there are rather few major magic mods for 1.16. 

A major update released the other day for the mod, and it _might_ be stable enough for testing, although it could be too early for that

https://manaandartifice.com/
(There is no Curseforge page for it (for now))

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I am keeping track of it :)

**Comment by NillerMedDild** [comment]
I've had a look and at the moment it's a no, I'll revisit it later.

**Comment by Ridanisaurus** [comment]
Got around to look into this mod, and to be honest, I think adding it would be some sort of a clutter as we already have Ars Nouveau. Of course I know it offers other things beside the spell crafting, but so does Ars Nouveau, where instead of the Golems we have the summons, and I can tell you that there are more summons coming, and more features are planned.
On top of that, the blocks, and items, of AM3/MA look godawful. A lot of custom 3D Models which do not fit in the Minecraft whatsoever, high resolution textures, and just overall it doesn't feel right. Of course, needless to say, this is my opinion and you know how critical I can be about non-standard 16x16 textures.

Just thought I would add my opinion on this matter (at least as of this stage) for whatever its worth.

**Comment by NillerMedDild** [comment]
That was my initial assessment as well :)

**Comment by Ridanisaurus** [comment]
I saw Dire play with it on Forgecraft in his last episode. I wanted to cry :D

**Comment by SQbuilder** [comment]
Hopefully model / texture changes will come around with more updates to AM3, as it is still in beta. There are more features planned if you follow development on the AM3 discord.

**Comment by NillerMedDild** [comment]
That I do :)
