### ISSUE TITLE
Uranium and Lead spawn chance

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#283]
**Modpack version**
E6 0.2.16

**Issue**
This topic has been raised multiple times on both E5 and E6. The spawn chance of both Lead and Uranium is very low. I think it would be worth looking increasing the spawn chance, especially in E5 now that Uranium is required for Uraninite.

**Comment by Merlo17** [comment]
E6 is also important since mekv10 uses uranium for its reactors, and players have lamented a lack of it to progress

**Comment by MaxNeedsSnacks** [comment]
Lead is also needed for some parts of the Reactor multiblocks, so it'd definitely be a good idea to up the spawns of both of these

**Comment by KrAzYGEEK32** [comment]
ive been playing on E5 these past few days, and in my opinion lead spawn is fine , i would even say its a bit much compared to its counterpart silver. I felt Tin was very rare to find (ive played pure EE ore gen)but as i said its my opinion and maybe my bad RNG, but please consider upping tin as well :P

**Comment by MuteTiefling** [comment]
Gonna play devil's advocate a bit on uranium.

There are basically 3 end game items that take antimatter pellets to make that will be made once, and a fourth that a player could potentially craft multiples of. That last one being the supermassive QIO drive... which, let's be honest you probably don't need more than one of.

Now, an antimatter pellet takes 10k uranium ingots. Obviously to even be running a fission reactor one must be making all of the same products required for 5x ore processing, so there's no reason not to also 5x your uranium. One pellet, then, is 2k ore.

Now, I've done a bit of testing with the Orechid and it generated about 1 uranium ore per hour. So viably farming Uranium this way is going to take a fair number of orechids. It's also gonna produce a lot of extra stuff. Sadly, it cannot be tweaked and doesn't produce fluorite, which is vital to fission, but fluorite is bountiful in the world anyway. 

Bees are probably going to be even worse, since they produce dust, meaning it cannot be multiplied by processing.

Running a digital miner in a new area netted me 25 uranium, 25 lead, and several stacks of fluorite. Targetting only uranium and lead means it's a very short process to plonk down, run, pick up, move, repeat, similar to farming ancient debris. 

Lastly, there's the IE Excavator that can pull up a couple thousand of a given ore if the appropriate node is located. One of these would be enough to get someone deep into fission by-products. Sadly, this doesn't get fluorite either (can that be tweaked maybe?) but it will get massive amounts of uranium faster than any other method.

So while it is somewhat rare, I don't think it's too rare. Players just need to be smart about acquisition and processing. Making the creative flight modifier, for instance, would require 6k uranium. There's obviously processing time in there, so a player could simply ship all this stuff back to base as they fly around collecting more with a digital miner. It only takes about a minute to run the miner filtered only for uranium and lead. At ~25 ore per stop, that's a couple hours of hunting. 

Rather than increasing the spawn rate in the ground of the overworld, I think it would be more interesting to add another route to get to it. That could be as simple as having it spawn in the nether or end dimensions. Or it could be to tweak bees to be able to produce more if the combs are processed differently. This might be getting too deep into 'expert' territory though, but running combs through a thermopneumatic processing plant or something to increase yield could be an interesting way to improve this

**Comment by MuteTiefling** [comment]
Just to add on to my previous comment. This morning I had zero progress in Immersive Engineering. It took me 30 minutes to locate a uranium deposit and another 2 hours to get an excavator going on it. It's set to produce roughly 22k ore. It's slow, but I can walk away from it while I set up a fission reactor now.

**Comment by NillerMedDild** [comment]
I appreciate the thoughts Mute, I have however chosen to increase the generation - I don't think finding ores naturally generate should be harder or very time consuming, just rare enough to make the mining trip fun. I will remember your ideas for expert mode though :)
