### ISSUE TITLE
You are unable to craft Percision Mechanisms in 0.5.7

### ISSUE THREAD

**Issue by KnyteGaming** [NillerMedDild/Enigmatica6#2835]
The precision Mechanism is one of the new Sequential craftings added in the new version of Create, it is needed to make mechanical arms. By default there is a recipe for it but it appears to be missing. I checked against a pack containing just create(and flywheel) and the recipe is there and works. The other two sequential crafting recipes work for making cogs, but the recipe for precision mechanisms doesn't work,

**Comment by Quezler** [comment]
came here to report the same issue, saw this open one so i'll attach my screenshots here instead of making a new one:

all the sequenced assembly recipes:
![Screen Shot 2021-07-29 at 11 20 40](https://user-images.githubusercontent.com/3179271/127466997-c31ac621-5b34-4f5a-b69c-65ef4c466e29.png)
the `precision mechanism` isn't there, and neither won't anything show up if you press `R` over it.

you can't craft the `mechanical arm` and the `rotation speed controller` without it: (no alternative recipes)
![Screen Shot 2021-07-29 at 11 21 13](https://user-images.githubusercontent.com/3179271/127467030-707fe87a-d9c6-45ac-8fcc-8fe47e5d3819.png)
(including the `extendo grip` & `potato cannon` one of the alternate usage tabs)

(sceenshots taken on a server with /mode expert, as well as having done that on the client itself)

**Comment by Quezler** [comment]
a piece of the puzzle may be there are no gold sheets, yet the [default recipe ](https://create.fandom.com/wiki/Precision_Mechanism) seems to require one, maybe that's why it silently fails?

![Screen Shot 2021-07-29 at 11 32 25](https://user-images.githubusercontent.com/3179271/127468589-d67c0f64-79e3-4814-8b55-ea17d6a76a78.png)

luckly in the latest changelog for this pack it mentions kubejs create now supporting custom sequenced assembly recipes, i suppose the default one will have to be overwritten, and a new recipe that doesn't use gold sheets to return in its place? https://www.curseforge.com/minecraft/mc-mods/kubejs-create (at the very bottom)

(`emendatusenigmatica:gold_plate` seems like the best possible candidate to replace create's gold sheets with)

**Comment by TemperedFool** [comment]
Way to not use tags, Create. I'll take a whack at this shortly, as I've already been playing with the KJS integration for it.

**Comment by TemperedFool** [comment]
I retract my "way to not use tags" comment; the issue is actually one of the outputs of the recipe (I think) so it couldn't have used a tag. So instead - way to introduce random failure to a recipe that should just work every time...
