### ISSUE TITLE
Pack Crash when loading or creating Worlds

### ISSUE THREAD

**Issue by Malavisto** [NillerMedDild/Enigmatica6#2930]
Modpack version - 0.5.9

The bug
Pack crashes when i try to load or create a world

Logs
https://pastebin.com/0BnPwXFq

Note - I am using Windows 11 home 64 bit not Windows 10 64-bit

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please provide your `BiomeIdFixer.json` file? It's found within any save, in the `biomeidfixer` folder.

**Comment by desagas** [comment]
Please check what version of Java your Minecraft profile is defaulting to/using, and let me know, so that I can see if there is a work around. Windows 11 may be doing something to what Java version is being used.

I will post it in the known bugs as soon as I can.

**Comment by desagas** [comment]
I can not currently fix this bug, sadly. My forge will not update, and when I try to build it as it was written originally, it fails as well, which means I can not even try to fix it. Once this is fixed, I am confident I know what is wrong, and I know how to fix it.

As a HOT FIX, please make sure you copy and paste an existing world folder into your instance of this pack, so that this "index exception out of bounds" does not happen when creating a new world. It should only happen when no worlds currently exist ... but should work when at least one other world has already been created or exists fully in the instance.

**Comment by Malavisto** [comment]
I am using Java version 16.0.2

[biomeidfixer.zip](https://github.com/NillerMedDild/Enigmatica6/files/6984356/biomeidfixer.zip) i could not sent the json file directly so i took the biomeidfixer folder and compressed it

**Comment by NillerMedDild** [comment]
Damn that json is corrupt af, delete it and you might be good to go.
If that doesn't work, try replacing it with this one:
[biomeidfixer.zip](https://github.com/NillerMedDild/Enigmatica6/files/6984381/biomeidfixer.zip)

**Comment by Malavisto** [comment]
i will try that

**Comment by Malavisto** [comment]
Switching the Json file seems to have allowed me to load into my world. I think my laptop shutting down during loading my world corrupted the json

**Comment by desagas** [comment]
I am happy your got it fixed. I might do some testing to see if the change from Java 8 to Java 16 does this often when updating. Fingers crossed it was a one off situation.
