### ISSUE TITLE
Add cat slippers (low drop rate) to cat kills

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#2993]
**Description**
Add a very very very low drop rate to cat kills giving you the curios cat slippers.

**Why would you like this added/changed?**
Cause the cat slippers are made from REAL cats, so thus, obviously, they should drop from their deaths.

**Screenshots if applicable.**
Dead cat pictured:
https://cdn.discordapp.com/attachments/726178356143456287/872605519788003338/2021-07-26_18.30.42.png

**Comment by TemperedFool** [comment]
I suspect we're not going to incentivize cat killing - if we did @Buuz135's mods would likely all stop working...

**Comment by NillerMedDild** [comment]
It's a good idea though... 😄

**Comment by DoomSquirter** [comment]
how bout a cat hospital/vet.  cats go in, cats come out but also drops cat balls and cat fetuses and somehow those gets used to make the cat slippers?  spay and neuter your pets ppl!

**Comment by NillerMedDild** [comment]
We're gonna take a page out of Mojang's book here and not incentivise killing animals :P

**Comment by ThePB** [comment]
> 
> 
> I suspect we're not going to incentivize cat killing - if we did @Buuz135's mods would likely all stop working...



> 
> 
> We're gonna take a page out of Mojang's book here and not incentivise killing animals :P

... So the Wasabee and some other bees are getting (or have gotten in 0.5.10, can't check) a recipe change? :P
(Or prehaps there's a way to get a cat spawn egg that doesn't involve a massacre?)

**Comment by TemperedFool** [comment]
@ThePB No, because these don't require spawn eggs. Please follow the quests or wiki (https://github.com/NillerMedDild/Enigmatica6/wiki/Working-with-Bees), which suggest using the Beepedia to look up these mutations, as JEI displays entity mutations as spawn eggs instead.

**Comment by ThePB** [comment]
> No, because these don't require spawn eggs.

Oh, they require an actual mob? That's good news. Now i need to find a place where to accomodate all these cats... I don't think there are enough shelves. Also, i can cry in a corner because i pretty much wasted a ton of time.

> Please follow the quests or wiki (https://github.com/NillerMedDild/Enigmatica6/wiki/Working-with-Bees), which suggest using the Beepedia to look up these mutations, as JEI displays entity mutations as spawn eggs instead.

I know you did rewrite some (if not all of the) quests, but ALL quests, except 1, only give JEI as a source of info. The only quest that directs to the Beepedia is a new one introduced in between 0.5.6 and 0.5.9 and involves crafted bees. Even the quest that gives the Beepedia item has no explanation of what it is, how to use it, or how it is useful over JEI (traits and avoiding confusion, apparently :D). The new one simply mentions to check the Beepedia **or** JEI and pay attention to spawn eggs and jarred bees - which i know you prepared a change for recently. And after having read for hours to try to understand the many, many mods and changes since the last time i played...

I don't think there's a mention of the spawn eggs problem anywhere in game. Even the wiki doesn't mention it or to use the Beepedia over JEI because of it, but honestly i only did a quick parse of it after your post here.

With no in-game guidance about the problem, the egg icon on the quest where it is mentioned the Beeper and Blaze bee, the fact that the Tier 3 Bees quest mentions "Entity and Item" mutation, the JEI bug (which is two-fold: my assumption was also due to the Entity to Entity category having 2 different kinds of "eggs" for "mutatee" and "mutated", with the mutatee following the block to item format, while the results being more "mob-like"!), and the fact that i still didn't have the possibility to check if any Entity to Entity mutation worked at all... i'm just happy to know i've got too many cats to feed now! Thanks for the info!
