### ISSUE TITLE
Refined Storage Processing Patterns behave weird

### ISSUE THREAD

**Issue by Rolnaro** [NillerMedDild/Enigmatica6#2999]
**Enigmatica6 0.5.9**

**Refined Storage Processing Pattern behaves weird**
When I try to make a processing pattern I can not fill items in the grid (left or right clicking with item does nothing) Choosing a recipe from JEI makes you able to create a pattern, but you can't exlude items (like flint in pulverizer) from the recipe which makes auto crafting fail because the extra items are being waited for.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6987881/latest.log)

**Screenshots**
![2021-08-15_11 26 53](https://user-images.githubusercontent.com/84525252/129474106-6e175642-44d6-465f-819d-0d835f584245.png)
Grid stays empty

Note: Crafting with fluids is also not working

**Comment by RobuxShooters** [comment]
You should be able to remove items filled in by JEI by Ctrl+Shift+Right-clicking on that particular item you want removed. Also, you should be able to drag and drop items from JEI into the Pattern Grid (the grid should turn green to tell you dragging and dropping is allowed).

It seems like your Grid is empty because your Pattern Grid is currently in Fluid mode. Try switching it back to Item mode.

**Comment by Rolnaro** [comment]
Omg, I never saw that. It was indeed the fluid mode... how did that turn on :\
The drag and drop or rightclick jei left click works fine.

Thank you so much, would never have seen that.
