### ISSUE TITLE
`requestify:crafting_emitter` not dropping anything when mined

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3016]
**Modpack version**

0.5.9

**Describe the bug**

if you mine it, nothing drops. (even with the pickaxe as the one probe suggests)

made a [pull](https://github.com/Buuz135/RS-Requestify/pull/22) to (hopefully) fix it that mimics a [previous](https://github.com/Buuz135/RS-Requestify/commit/4cc5041e0c8225db6569eccc28b311d388822552) commit for the requester.

**Screenshots**

![2021-08-16_14 29 00](https://user-images.githubusercontent.com/3179271/129563898-fbfac896-8ac1-4be5-8ef5-79c55ccc6482.png)

**Comment by 9bananas** [comment]
Hi! i don't know if this is a good idea, but i figured since it's directly related and the it's the same pack version (0.5.9), I'll report here instead of a opening a separate bug report:

the crafting emitter also doesn't like being switched from item to liquid: it crashed my server when i tried (no big deal, had backups @30min intervals). after it has been switched to liquid, ALL crafting emitters, newly placed or old, are set to liquid and can't be changed back, apparently...suuuper strange behavior.

the exact setup for reference (the pretty pipes have redstone upgrades):

![image](https://user-images.githubusercontent.com/56475713/130336997-31238de7-4b14-495e-82c6-9f55d698ab52.png)

**Comment by NillerMedDild** [comment]
That is fixed in version 0.5.11 :)

**Comment by 9bananas** [comment]
haha! two derps found each other i guess!

thanks for the quick reply, already updated the server! cheers!
