### ISSUE TITLE
Ore chunks tagged as valid for RB apiaries, causes problem when filtering by tags

### ISSUE THREAD

**Issue by TheKaldra** [NillerMedDild/Enigmatica6#3096]
### Modpack Version

0.5.11

### Describe your issue

Most(all?) ore chunks are tagged as valid for Resourceful Bees apiaries. This causes them to be filtered with most blocks in the game when filtering by tags. 

i.e. I use a dank for blocks and a sophisticated backpack for ores. When I use the advanced pickup upgrade with the backpack and filter by tags with a chunk in the filter, cobblestone(and most or all junk blocks) gets pulled into the backpack instead of the null.

Using a filter upgrade to then blacklist items such as cobblestone does not seem to work either as they still go into the backpack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Epic428** [comment]
TemperedFool should already be aware, but just for posterity, we released an update that strips our default tag down to just the apiary blocks (keeps it from crashing due to removal of files). Our hasCollision check covers probably 95-98% of blocks anyway. Only notable exception is glassential glass blocks - which we have our own substitute for in the way of honey glass.
