### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by me0me0me** [NillerMedDild/Enigmatica6#3122]
### Modpack Version

0.5.11

### Describe your issue

Using a valid item on Atum's Quern while it would also be valid to place (blaze rods notably) will both place the block and place the item into the grindstone duping the item.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I.. can't seem to find a Grindstone from Atum?

**Comment by me0me0me** [comment]
Sorry I was thinking of the Quern. Brainfart aside bug it seems it was some visual bug that was causing it to look like it was duping. Exiting the game completely seems to have fixed it

**Comment by MuteTiefling** [comment]
Cannot replicate in Dev, possibly already fixed by mod author.

https://streamable.com/wk7h4v

As shown in the video, when I right click, it does place the blaze rod still, and insert one into the quern, but 2 are extracted from my inventory. 

This feature of placing sticks and blaze rods does make this thing a little annoying to use, but it's also not needed for much considering there are better ways to perform these crafts that can be automated. The placement can also be prevented by putting a partial block on the face you're clicking, like a carpet.

**Comment by me0me0me** [comment]
It is explicitly with _**One**_ in hand

**Comment by MuteTiefling** [comment]
Ah, yep. OK can reproduce that now.
