### ISSUE TITLE
Impossible Quest-line

### ISSUE THREAD

**Issue by Gcat101** [NillerMedDild/Enigmatica6#3140]
### Modpack Version

0.4.14

### Describe your issue

Broken and impossible to complete quest in "storage" section.

Screenshots:
![Снимок экрана 2021-08-31 в 15 24 36](https://user-images.githubusercontent.com/79367505/131502425-d52f900f-b335-49a3-ae7d-fed2128cbe75.png)
![Снимок экрана 2021-08-31 в 15 24 30](https://user-images.githubusercontent.com/79367505/131502430-bf8daa8c-1549-41a3-8857-4d6c3048d749.png)
![Снимок экрана 2021-08-31 в 15 24 08](https://user-images.githubusercontent.com/79367505/131502439-ca225478-227a-435a-b59a-93a047ab7f72.png)

### Have you modified the modpack?

Yes

### User Modifications

I added a vanillatweaks texturepack and discord rich presence mod (https://www.curseforge.com/minecraft/mc-mods/discordrpc)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
This has been fixed for several months, please update :)

**Comment by Gcat101** [comment]
So I've updated and all of my quests are gone:
![Снимок экрана 2021-08-31 в 17 50 45](https://user-images.githubusercontent.com/79367505/131525037-e7e2748b-c610-4cc5-acc2-382c1eb622c2.png)
They don't seem to work when I try to re-do them.
Can I somehow fix it?

**Comment by NillerMedDild** [comment]
I totally forgot about that, sorry :/ when updating its very important to read the changelog so you know what to expect. I recommend you downgrade to the old pack version and load a backup.

**Comment by WorldTeacher** [comment]
> They don't seem to work when I try to re-do them.
> Can I somehow fix it?
You can somewhat fix them by going to  [Your Install folder]\saves\world\ftbquests
or dor the server [Server folder]\world\ftbquests
After that, you can re-collect the quests,
Another way would be to "cheat" the progress by enabling the FtbQuest Editing mode using `/ftbquests editing_mode` and manually editing each completed quest.
I've had the same Issue when upgrading from v0.4.14 to v0.5.something and it hasn't happened since.
hope I could help
