### ISSUE TITLE
Ritual of the Forest tree detection

### ISSUE THREAD

**Issue by Silenceaux** [NillerMedDild/Enigmatica6#3231]
### Modpack Version

0.5.11

### Describe your issue

The Ritual of the Forest (from Nature's Aura) will only detect tree growth if it uses a sunny blossom sapling from quark. JEI represents this accurately by showing only the sunny blossom sapling as an option for the ritual. Typical behaviour for this mod is for it to detect at least all vanilla trees (oak, birch, etc) if not all trees.

Vanilla tree growth (tested extensively with Birch, a little with oak) does not trigger the effect at all, even if the tree grows in a normal / vanilla similar style.

Issue first noticed in multiplayer, then tested in creative superflat. "Plains" biome according to JourneyMap.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
> Typical behaviour for this mod is for it to detect at least all vanilla trees (oak, birch, etc) if not all trees.

Incorrect, I'm afraid. Each ritual required specific trees. Mostly they needed Oak.

However, due to a few other mods that interfere with the way Oak and other vanilla trees generate, even when grown from saplings, these rituals would fail about 50% of the time.

We therefore opted to use the Quark trees as alternatives as those were not subject to misfires and are as easily obtained as any other sapling. 

https://github.com/NillerMedDild/Enigmatica6/pull/2816
