### ISSUE TITLE
Magic Feather is impossible to craft

### ISSUE THREAD

**Issue by Pyranis** [NillerMedDild/Enigmatica6#3409]
### Modpack Version

0.5.14

### Describe your issue.

The recipes to make the Magic Feather rely on using a Leaf Pile which only generate in Aspen and Deciduous Forests, neither of which generate in this modpack, or at least in the Terraforged world type.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
This is fixed in dev, byg updated their config .json at some point and we were still shipping the old file causing us to be missing something like 60 biomes from byg..

If you delete this file from configs/byg, it will refresh and these biomes will start showing up again.

https://github.com/NillerMedDild/Enigmatica6/blob/develop/config/byg/byg-biomes.json
