### ISSUE TITLE
Investigate Extreme Reactors

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#345]
https://www.curseforge.com/minecraft/mc-mods/extreme-reactors

**Comment by MuteTiefling** [comment]
https://github.com/ZeroNoRyouki/ExtremeReactors2-issues/issues/4

https://github.com/ZeroNoRyouki/ExtremeReactors2-issues/issues/3

Couple minor issues. I'm sure the redstone one could be fixed quickly enough. 

Overall, however, I don't see much point. Powah covers the basic nuclear reactor game just fine and brings some new mechanics to the table. Automating it's cooling requires a bit more effort than simply dumping a bucket in and walking away. 

Then there's documentation. There is none. What's a valid coolant? How do you build a reactor? I managed to stumble through building one in creative, largely because I've seen it done before... But I generally frown upon a mod that 100% leaves it up to tribal knowledge to actually use it.

**Comment by ZeroNoRyouki** [comment]
Hi there, thank you for letting me know of the issues you found. I've fixed them and new release should be out today.

Addressing your comments above, I know that ER is, as was Big Reactors, a bit on the easy side of thing. That's why since I ported BR from 1.7.10 I've tried to make it a bit more challenging in various way ending up with the current Reactors variants we have in 1.16.3 (a Basic starter one and a Reiforced one to buld as big as you want, each with it's own cavets, and two more variants planned). From what I can tell you from past interactions, players like it to be on the easy side, let's say.

As for the documentations that's one thing I want do add, I'm just waiting to see what the best in-game documentation mod for 1.16.3 turn out (I don't want to reinvent the wheel here). If you have suggestions, please let me know :)
And as you noted yourself, users already know how to build a Reactor or Turbine since 1.7.10

Not avaing a list of official valid coolants / moderators / turbine coils is something I'm doing on porpouse. That's why I've never added (and never will) a JEI plugin to show them for example. This is because:

- other mods can add their own blocks and fluids to act as coolants / moderators / reactants / coils / etc with their own characteristics

- I want the player to experiment with the mod, checking what work best in their pack to build the best Reactors or Turbine. In the past pack authors have given players new moderators (or removed somes) to adapt my mod around their pack theme

- the plan for 1.16.3 is to have a way for the player to simulate their Reactor layout in game so they could test out their ideas (and blocks/fluids their pack provide) in game but wihout having to build the actual Reactor itself. All the importan bits are already inplace in the code, so I don't thing it would take long to release it after I'm done with the Turbine

I'm always open to suggestions to make the mod better so feel free to throw them at me here or one the mod page on Curse Forge :)

**Comment by MuteTiefling** [comment]
Hey Zero, thanks for taking the time to respond.

If you're looking into a ready built framework for documentation, take a look at Patchouli. It's got a lot of really nice features, even allowing you to show holographic previews of basic structures to give people a clue where to start. Remember that not everyone's a pro and a new player isn't likely to trust a 10 year old video from 1.7.10 to be accurate anymore. Any documentation you can give will be a welcome improvement for me.

As for coolants, moderators, coils, and the like... I get where you're coming from but not even having a place to start just feels bad from my personal perspective as a player. I didn't even know there could be moderators and I certainly didn't know I could build a turbine. I sort of assumed that it may be possible since the gui sort of eluded to an active cooling mode but I didn't see any blocks that would make me think I could build a turbine for active cooling. Is that not yet implemented?

Considering the large number of possible combinations here, I have to say I don't feel particularly compelled to just start experimenting. Going through the list of coolants might not take long in many packs since there aren't a ton of options that even make sense (obviously not going to try things like lava or oil, for instance). But moderator blocks? There could be hundreds of possibilities. A simulator to test their properties could be interesting, but not even knowing what ones are potential moderators turns a fun experimentation session into a daunting chore.

**Comment by ZeroNoRyouki** [comment]
I've briefly took a look at Patchouli when it came out on 1.12.2. I'll check it again than, thank you for your suggestions

Yup the Turbine is not out yet for 1.16.3. I probably suffer from a "long time player" issue here, since Big Reactors and, then, Extreme Reactors, where pretty much know mods since 1.7.10 so I maybe taking some thing for granted. 
Moderators are usally metal or rare/expensive blocks that can be used to moderate the radiation and heat emitted from the fuel rods ad move it away from them. A common block like dirt or stone is probably not a moderator while a diamon block or enderium block will proabably be a good moderator

**Comment by MuteTiefling** [comment]
I think without giving too much away, moderators could simply be given a tooltip stating that they are one. That way you're not throwing away the chance for experimentation, but you also let people target their efforts. 

Thanks for listening though, and thanks for the quick fixes in general :D

**Comment by ZeroNoRyouki** [comment]
Yeah but the thing is moderators are not blocks of my mod and messing with other guys blocks is not seen well ^^;
And you will need to look at all the blocks in JEI to look for the tooltip anyway

**Comment by MuteTiefling** [comment]
Shouldn't be any harm in adding a tag automatically, and that would let the player search without looking at every block.

**Comment by ZeroNoRyouki** [comment]
I'll look into it

**Comment by NillerMedDild** [comment]
I'll leave it out for the time being, but will re-evaluate down the line.

**Comment by ZeroNoRyouki** [comment]
> Shouldn't be any harm in adding a tag automatically, and that would let the player search without looking at every block.

Hi, I've added an advanced tooltip for items and blocks that can be used as fuel or moderators in 2.0.6
