### ISSUE TITLE
Preview button overlapping customize button

### ISSUE THREAD

**Issue by Superslammer** [NillerMedDild/Enigmatica6#3500]
### Modpack Version

0.5.16

### Describe your issue.

When creating a survival world and then pressing the "More World Options..." button the "Preview" button overlaps with the "Customize" button

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Speiger** [comment]
Closed the issue because i can answer here.
Short answer is no i am not disabling the button, its placement is not perfect. Fully agree...
I am going to move it or implement a logic that constantly checks which screen and adjust it slightly.

That might be the best solution. Because more options screen is kinda annoying i wish they had layouts you could add yourself to and it would auto fit.

But yeah will be addressed with the next patch.
