### ISSUE TITLE
New TARDIS Mod

### ISSUE THREAD

**Issue by yoyotam3** [NillerMedDild/Enigmatica6#3570]
### URL

https://www.curseforge.com/minecraft/mc-mods/new-tardis-mod

### Why would you like the mod added?

As well as just being a cool mod in general, the New TARDIS mod is fairly stable and adds a space dimension with basic oxygen mechanics, making it a good holdover until Advanced Rocketry or any other space mods are sufficiently stable to be used.

**Comment by HeavyDeception** [comment]
Ok, I have been using this mod with the pack there is a rendering bug with The One Probe this can be fixed if you put the Tardis door on TOP's render black list. But I can't find the id for the door when placed

**Comment by 50ap5ud5** [comment]
> Ok, I have been using this mod with the pack there is a rendering bug with The One Probe this can be fixed if you put the Tardis door on TOP's render black list. But I can't find the id for the door when placed

The id you would need is `tardis:interior_door`.
See [its source code](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/1.16/src/main/java/net/tardis/mod/entity/TEntities.java#L23)  if you need more references or ask on the Tardis Mod discord if you need help with that mod specifically.

**Comment by HeavyDeception** [comment]
@50ap5ud5 Thank you the item has the ID of tardis:int_door and I was using that so again Thank you for your help.

**Comment by NillerMedDild** [comment]
I'm afraid we've landed on a no for this, it's a great mod but unfortunately not up to our usual standards when it comes to guidance/documentation (in-game) and textures. On top of that, it doesn't really have anything we *need* in E6.

**Comment by MaxFirestorm** [comment]
![Doctor Who - Rain](https://user-images.githubusercontent.com/11296552/141696168-cae769ff-c5b6-4523-9810-ed727631dab9.gif)

**Comment by BooBeerb** [comment]
sob

**Comment by theboo** [comment]
https://tenor.com/view/doctorwho-mattsmith-eleven-cry-sad-gif-5020632

**Comment by theboo** [comment]
![doctorwho-mattsmith](https://user-images.githubusercontent.com/3585761/141696680-0fe9e9c9-f3ad-4683-9b73-0d24d1d3ef4a.gif)

**Comment by 50ap5ud5** [comment]
> 
Just wondering, would you be willing to share what sort issues with the mod's documentation and textures your team felt was not up to standard, so that the mod may improve upon those aspects?

What are your usual standards for ingame documentation and textures?

**Comment by NillerMedDild** [comment]
Sure I'll give a brief explaination :)

The in-game documentation is hard to get an overview of, because of the layout of the book. I highly recommend that you use Patchouli for making in-game documentation, 
As someone who hasn't watched Dr. Who, I was quickly overwhelmed with information, both in-game and on the wiki. A concrete getting started guide would help a lot here.

As for the textures, they feel out of place in Minecraft, the styles clash. It's a bit immersion breaking.

**Comment by 50ap5ud5** [comment]
Thank you for the feedback NillerMed!

It's much appreciated to gain an insight into your thoughts and expectations.

## Documentation
To address your concerns about the "Getting Started" documentation, we already have extensive tutorial documentation on the wiki within [the Tutorials section ](https://tardis-mod.com/books/tutorials)of the wiki which covers what you may need in a "Getting Started" guide.

Upon review I agree that we could have added clearer indications across the mod towards this starting guide, cover more topics related to the operation of the mod and that the in-game book could be formatted better. 

In our latest version (1.5.2 as of writing), we have added a Table of Contents page and rearranged the navigation buttons to be easier to use. 
Documentation is something we've lacked time to do since the initial rewrite for 1.16 and we will continue to work on this aspect in the future.

On the other hand, I understand the mod owner intended our in-game manual to be more of in-universe guide to the Tardis only. The wording intends to suggest you were reading a set of notes created by a previous pilot of the craft, rather than a formal guide to the mod similar to what mods such as Immersive Engineering might do. 

The overall theme of the mod is meant to encourage the player to explore and discover things and develop their own solutions to the many problems they may encounter. The lack of concrete solutions to every problem is something the mod owner intentionally accounted for, to reflect on the trials of their life experiences and pass this on to the player. The Tardis Mod is more than just a Minecraft mod for the mod owner, but a form of personal expression.

Thanks for suggesting Patchouli too. It is a great API that we have considered using before, but the reason we don't want to use it is because it requires us to potentially add a hard dependency on that mod, which can limit the Tardis mod to specific Minecraft versions and potentially a specific Forge version for some time. 

Developing the in-game book feature has also allowed us to gain experience in developing such a feature and we feel that we learnt alot more from developing it ourselves than relying on a ready-made solution haha.

## Aesthetics
We can understand the jarring feeling of the textures, especially since in recent times, mods have tended to adopt an art-style closer to vanilla "Jappa" style.
This particular [art style by our main artist](http://arcanetimes.com/product-design) is preferred by the mod owner, so that is why the majority of the mod's art style conforms to this. We'll keep the feedback in mind and explore how we can further develop the existing art style.

We can understand how overwhelming the mod can look to first-time users. 
One thing we would like to stress is that you _don't need to know a lot about the Doctor Who TV show_ to be able to play the Tardis Mod! It's why the overall aesthetic of the mod departs from the designs seen on-screen and how we never mention named characters such as "The _[X]th Doctor's_ Tardis".

We'll see what we can do to make the learning curve smoother.

## Notes

We've heard that the content added by the current versions of the Tardis Mod was something that the modpack didn't need. 

Since the initial port to 1.16.5, we do plan to continue expanding the existing content, such as the number of playable Missions and adding features which may be useful to modded Minecraft players, such as a universal tool mode for our Sonic Screwdriver as part of an upgrade system.

We've always intended the Tardis Mod to be a "companion" in a sense to other mods; it's why many of our features include compatibility with systems such as Forge Energy and provide API hooks for other mods, which is something we felt was missing from other "Doctor Who" related Minecraft mods.

## Thanks

Thank you very much for consideration of the Tardis Mod and we hope this comment helps your team understand part of our perspective and some design decisions made for the Tardis mod. 

This is one of the first times that we've had the opportunity to engage with a modpack developed for the wider modded Minecraft community. 

It's been insightful to learn about some of the trends and preferences of the modded Minecraft userbase. Alot of users we've talked to really like Enigmatica and love using it alongside our mod! 

Looking forward to keeping in touch with Enigmatica in the future.

**Comment by Modeljun** [comment]
Hello there!Can i move to mcbbs?I will direct the download address to this side!

**Comment by NillerMedDild** [comment]
Depends, do you mean the modpack or the `New TARDIS mod`? Cause the latter I have no rights to 😄

**Comment by Modeljun** [comment]
I am trying to move the new tardis mod to another site, can I?

**Comment by MuteTiefling** [comment]
> I am trying to move the new tardis mod to another site, can I?

It's not our mod. We can't give you permission.

**Comment by Modeljun** [comment]
MOD can add Cybermen?

**Comment by theboo** [comment]
You are in the wrong place friend, ask your questions here: https://gitlab.com/Spectre0987/TardisMod-1-14/-/issues
