### ISSUE TITLE
Desert Rabbit and Severing

### ISSUE THREAD

**Issue by StarBanger69** [NillerMedDild/Enigmatica6#3576]
### Modpack Version

0.5.17

### Describe your issue.

Desert Rabbits don't give a rabbits foot from the severing upgrade from tinkers construct. 

### Have you modified the modpack?

Yes

### User Modifications

I have updated farmers delight to the latest version. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Wishbone1977** [comment]
Don't know if it's related or not, but I've been trying to get a rabbit's foot for a while for the Tinker's Fortune upgrade. When a desert rabbit finally dropped a foot, it was a Lucky Rabbit's Foot from Apotheosis instead of a normal one. That might just be chance though, I don't know what they should drop under which circumstances.

**Comment by Quezler** [comment]
it might also not have dropped, but it will for either when 0.5.18 releases: (or when you add this file yourself)

https://github.com/NillerMedDild/Enigmatica6/blob/4a148d63b89e8b6f0f9e484cc9940ee9e4e8fe93/kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/tools/severing.js#L7
