### ISSUE TITLE
Framed Cube light bug

### ISSUE THREAD

**Issue by Rythm420** [NillerMedDild/Enigmatica6#3690]
### Modpack Version

0.5.12

### Describe your issue.

Whenever trying to make invisible light sources with Framed Cube from FramedBlocks with a glowstone dust it will not emit any light. Even when pressing F7 to see where mobs can spawn it shows that there is no light coming from the block. So it's not a visual bug.

### Have you modified the modpack?

Yes

### User Modifications

Optinfe+Optiforge (Doubt that will be the reason)

For below, LAN.
Don't hate on lan... Give it a chance :)

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Please update the modpack and see if the issue persists :)

**Comment by MuteTiefling** [comment]
I could have sworn you said you weren't using optifine in Discord. 

Anyway, this is working fine for me in dev. Before updating, please simply try without optifine and in a single player (closed to LAN) world. And again _we_ don't hate LAN, but the modded community offers no special support for it since, as I understand, it requires them to jump through hoops that aren't needed for supporting a dedicated server.

**Comment by Rythm420** [comment]
Alright I'll remove optifine then, and yea I did say I didn't have any extra mods so my bad 😅
