### ISSUE TITLE
Create recipes for some Thermal items

### ISSUE THREAD

**Issue by kosma** [NillerMedDild/Enigmatica6#3705]
### Describe your suggestion

Add Create recipes (basin+mixer) for:

* Hardened/Signalum/Lumium/Enderium Glass
* Cured Rubber

Glass is needed for e.g. Enderium Integral Components, or wither shielding.
Cured Rubber recipe is especially annoying because it's used for Pretty Fluid Pipes.

Some of those should probably be Superheated but I don't know enough about progressions to suggest which ones.

### Why would you like this added/changed?

Parity with other existing recipes, like Enderium. I am currently doing a no-RF playthrough and Thermal glass is completely unobtainable, while Cured Rubber is only obtainable via ARC.

**Comment by MuteTiefling** [comment]
Added the hardened glass recipes to tinkers construct. 

Added alt cured rubber recipe to Create.

For the record, the Blood Magic recipe for Cured Rubber does not require the ARC. JEI is a bit misleading there since you can recycle the orbs for the input material. Instead, you simply need a tier 1 orb made with a diamond in a tier 1 altar
