### ISSUE TITLE
Click Machine

### ISSUE THREAD

**Issue by YashTFEM** [NillerMedDild/Enigmatica6#3756]
### URL

https://www.curseforge.com/minecraft/mc-mods/click-machine#:~:text=Click%20Machine%20is%20a%20standalone,click%20both%20blocks%20and%20entities.

### Why would you like the mod added?

This will help in automation as it gives a sort of autoclicker that can use a item in its inventory. It allows you to set clicks to left and right click. And allows them to be shift left click or shift right click. The mods we have currently just aren't able to do some clicking functions for automation such as botania. And believe me. I've looked. Should be a relatively easy mod to integrate since it only adds one machine. Please consider my suggestion since this will be extremely helpful for us.

**Comment by MuteTiefling** [comment]
Create deployer covers this. Modular routers does most of it too.

What exactly are you looking to automate that you can't find a way?

**Comment by theboo** [comment]
ID also completely covers this

**Comment by Ridanisaurus** [comment]
I agree with the above, this is completely redundant.
Create Deployer is somewhat basic, and requires the player to get into Create in order to use it, and Integrated Dynamics solution requires logic programming, which is not the easiest to for new players.
However, Modular Router is pretty cheap, easy to setup, and it offers all the options Click Machine has, and even more.

**Comment by YashTFEM** [comment]
Alright. I went through your options and found a few buggy things, but managed to automate my base.
