### ISSUE TITLE
World Infinitely Stuck at Loading 100%

### ISSUE THREAD

**Issue by henwearingatie** [NillerMedDild/Enigmatica6#3924]
### Modpack Version

0.5.21

### Describe your issue.

Whenever I load into my main world it indefinitely loads into the world saying 100%, but never actually putting me into the world. This doesn't affect other worlds, just this one. Screenshot provided to shows the issue. Don't really know what to do, can't find any other fix online. Game never crashes it just "loads" infinitely.
Screenshot: https://i.imgur.com/LhpBHhi.png

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by henwearingatie** [comment]
Turns out it was an error with updating pack versions. I was playing on 0.5.21, however when I reverted back to the previous version I was playing on (0.5.6) it fixed it and I was able to load into the world. Is there anyway I can update to the newest version of this pack or do I just have to create a new world. Please help if possible!

**Comment by Darkere** [comment]
The most common freeze currently can be fixed by doing this: https://github.com/NillerMedDild/Enigmatica6/pull/3884/commits/50aa461416997c98ef11ea5039fb1e31d14472eb

However, directly upgrading from 5.6 is likely going to have other problems. While we don't intend any world breaking changes without changing major versions, they do happen when they run for a long time. It is recommended to stay up to date, as we cannot possibly test all upgrade paths.
