### ISSUE TITLE
[Expert] Dirt Ball/Mud Block Conflict

### ISSUE THREAD

**Issue by Soneuser** [NillerMedDild/Enigmatica6#3947]
### Modpack Version

E6E 0.5.21

### Describe your issue.

When trying to make the Kiln from Environmental, the recipe calls for an item that uses mud balls.

The Mud Balls recipe from Environmental shares a recipe with mud block from Oh The Biomes You Will Go

In a vanilla table, there is no option to change between them.

Attached is a ss from discord where it shows no ability to change between them.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report, but this is already fixed in dev.

If you're interested in play testing Expert, you should absolutely be using the dev branch. The 0.5.21 release is almost a month old at this point and that covers a lot of changes, bug fixes, and development in that time. 

https://github.com/NillerMedDild/Enigmatica6#testing
