### ISSUE TITLE
Resourceful bees beelancing

### ISSUE THREAD

**Issue by Dasavanth** [NillerMedDild/Enigmatica6#409]
**Modpack version**
0.3.0

**Issue**
i had to make a joke, im sorry (not really :D)
at the moment bees seem to only require flowers to breed, including bees like the wither bees. changing the breeding item to something rarer based on the rarity of bee would be more balanced. there was a discussion going on on the E6 channel so im mentioning it here. feel free to add more points to this

**Comment by NillerMedDild** [comment]
Sounds very reasonable, will have a look soon :)

**Comment by Dasavanth** [comment]
i also found that most resources bees like diamond and iron were spawning naturally, would be more balanced if that was disabled and only bare minimum types of bees would spawn

**Comment by Epic428** [comment]
Yeah our bees were meant to be overwritten. Because our mod is geared more towards pack devs and customization, we only provided the vanilla bees as a way to show off what capabilities the mod has.

Also as a side note: Niller, if you have any questions, issues or suggestions for the mod feel free to reach out to me directly here or on discord :)
