### ISSUE TITLE
Constructor and Destructors can be used to dupe in

### ISSUE THREAD

**Issue by lewggs** [NillerMedDild/Enigmatica6#413]
#### Steps to reproduce:
1.set up rf system
2.set up a constructor and destructor facing the same block, configuration isn't important, but they have to face the same block. 
3.set a block you have X of to be placed by constructor and watch the numbers go up X+1.every time the destructor breaks it again. 
...

# Version:

- Minecraft: 1.16.1
- Forge: Forge-1.16.1-32.0.108 
- Refined Storage: 1.9.2
-Refined Storage Addons: 0.7

Does this issue occur on a server? Yes

I've not seen this issue be reported on this repository or the rs repository, so i made a new one

**Comment by Darkere** [comment]
It wss reported. And fixed ages ago.. please update

**Comment by NillerMedDild** [comment]
E6 version 0.3.0 fixes this :) thanks for the report though.

**Comment by jpie726** [comment]
> It was reported. And fixed ages ago.. please update

1. Servers cant always update, otherwise much progress would be lost 90% of the time

2. This was not a useful answer as it did not mention which version it was fixed in

3. Where was it reported? As I have searched for "dupe" among all issues, open, closed, etc and found none mentioning this

4. Once again, not a useful answer as you didn't link where it was reported so that op could verify that there weren't any differences between the two situations
