### ISSUE TITLE
Mekanism Tools nerf

### ISSUE THREAD

**Issue by LvsrsRedDragon** [NillerMedDild/Enigmatica6#460]
**Modpack version**
0.3.0

**Issue**
Mekanism tools (swords, pickaxes, paxels, etc.) are way too overpowered. Bronze sword does 10 points of damage, osmium does 8 but has diamond level durability, obsidian has 12 points of damage... And paxels not only do more damage than swords, they are also faster. The biggest issue with it is it breaks the purpose of mods like Tetra, for an example (and also erases progression after diamond, since most of these tools are more powerful than netherite in some cases). 

Mekanism Tools' tools can have each and every attribute of theirs changed in the config file, so it shouldn't be hard (if maybe time consuming) to nerf them.

**Comment by NillerMedDild** [comment]
Thanks for the feedback, we'll get those values in line :D

**Comment by Rosencratz** [comment]
I always felt a similar sentiment, but more so just that tetra should be revalued. 
At the moment, a lot of materials in tetra are not really worth at all looking into since they're either too slow or no different to basic iron variants that you're better off not bothering. This is especially the case with spears, which have no real advantage compared to swords. 

Perhaps could just improve tetra instead? I'm always for making everything better rather than reeling stuff back in line.

**Comment by NillerMedDild** [comment]
I think a mix of both is the way to go :)
