### ISSUE TITLE
Quark Vertical Slabs

### ISSUE THREAD

**Issue by whatusernameisleft** [NillerMedDild/Enigmatica6#464]
**Modpack version**
Enigmatica 6 v3.0
forge-35.1.0

**Issue**
Quark vertical slabs don't have a recipe

**Comment by Ridanisaurus** [comment]
Quark Vertical Slabs are removed on purposes to avoid duplicates. You can create your own vertical slabs with BlockCarpentry. The slabs there can be placed vertically, and you can then assign whatever block you want as a texture to them.
This from the official release notes of 0.3.0:
`Quark: Disabled Vertical Slabs, since BlockCarpentry has those covered`

**Comment by whatusernameisleft** [comment]
Alright, thanks.
