### ISSUE TITLE
Mekanism Fission Reactor issues

### ISSUE THREAD

**Issue by ShawnGunnels** [NillerMedDild/Enigmatica6#474]
0.3.0

The nuclear waste from the fission reactor can be piped out but can not be put into any kind of tank or machine. Also even with hazmat suit and breaking the multiblock and dying I continue to take tick damage no matter where I am after I suffer from radiation damage.

**Comment by MuteTiefling** [comment]
Nuclear waste can only be piped into Radioactive Waste Barrels or the few machines that can re-process it (Isotopic Centrifuge and Solar Neutron Activator). Have you tried these? Note that these blocks will only accept it from certain sides as well, for the Solar Neutron Activator, this is from the bottom. The Centrifuge should accept it from any side on the lower half.

When piped into Waste Barrels it will slowly, but safely, dissipate. The rate is slow enough that for a moderate fuel burn rate you'll likely need 30-40 waste barrels to come close to dissipating it fast enough.

Radiation is not just in the area either, it's in you too, and a hazmat suit won't protect you if you're irradiated yourself. It doesn't persist through death, but if you're running back to your death point and thinking you can suit up quick and be fine, that is not the case. Get a Geiger Counter to measure the radiation in the area and a Dosimeter to check your own radiation level.


This radiation will take weeks of in game time to dissipate and it covers a very large area. You should see particle effects in the air to show that you're in an irradiated area, but the Geiger counter will tell you just how bad it is. 

If you have access to commands and would like to just step back and reset, use `/mek radiation removeAll`

Radiation particles:
![2020-12-03_23 32 04](https://user-images.githubusercontent.com/9543430/101122298-21ae5c00-35c0-11eb-8c24-0e5b6c7f3a18.png)

I'm surviving just fine in this horrible radiation, as long as I keep the suit on. Take it off and I die immediately. Since I respawn here, I'm re-dosed upon respawning as well. Not great.
