### ISSUE TITLE
Mekanism Infuser creating  Immersive steel dust

### ISSUE THREAD

**Issue by SilverhuntX** [NillerMedDild/Enigmatica6#48]
**Modpack version**
0.2.3

**Issue**
Metalurgic Infuser from Mekanism, produces immersive steel dust when infusing enriched Iron with coal, resulting in a large number of recipe conflicts, especially with RS autocrafting processes which don't have ore dictionary when crafting

![image](https://user-images.githubusercontent.com/40155662/88766204-f8696380-d1ba-11ea-9d54-c375f05d417b.png)

**Comment by KrAzYGEEK32** [comment]
similar issue with dusts from mekanism crusher, the gold and iron dust recipes now make grits of the respective type, i understand there are for unification, but just wanted to know why immersive Engineering is prioritized over mekanism(which would make peoples life a lot easier XD)

**Comment by NillerMedDild** [comment]
The intended product of all ore processing and the like is from Immersive Engineering. Immersive Engineering is prioritized because it contains the most ingredients, which makes the unification least weird. In an upcoming update, all ore processing inputs and outputs will be from a custom Enigmatica mod.

This is not a bug, it is intended :)
