### ISSUE TITLE
[Mod Suggestion] Mekanism Additions

### ISSUE THREAD

**Issue by DarkAngel22579** [NillerMedDild/Enigmatica6#572]
https://www.curseforge.com/minecraft/mc-mods/mekanism-additions

Mekanism Additions adds a tonne of plastic based building and lighting blocks which go great with modern/high tech builds.
The baby mobs can be annoying and intrusive, but could be disabled by default.
![2020-12-20_15 40 23](https://user-images.githubusercontent.com/74909944/102717368-caa3c900-42d9-11eb-82b7-8934345bc9ae.png)

**Comment by NillerMedDild** [comment]
No thanks, I don't think it adds much we don't already have similar versions of :)

**Comment by Sanguinely** [comment]
Still think this would be a great addition because as of right now HDPE pellets only have a very small use. It'd be nice to get glow panels and the blocks to use them instead of them being pretty useless trash items after you make the items you can make with them (which only requires a few, less than a stack) but just running ethylene you end up with 10s of 1000s of them

**Comment by NillerMedDild** [comment]
I'd rather make it useful in some other way, but duely noted :)
