### ISSUE TITLE
[Suggestion] Using Expanded Storage in place of Iron Chests

### ISSUE THREAD

**Issue by JeffersonDoan** [NillerMedDild/Enigmatica6#580]
**Modpack version**
E6 0.3.* (in to 0.4.0)

**Suggestion**
In the same spirit of replacing Extra Discs with ExtraStorage as noted in #528, perhaps [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge) could be considered to replace Iron Chests?

The same base functionality is kept but Expanded Storage adds a netherite chest, allows each tier of chest to be combined as a double chest both vertically and horizontally, and offers a full-block chest variant of each tier that does not have animation and can help with lighting updates for the client if many are used in a close space.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion

> allows each tier of chest to be combined as a double chest both vertically and horizontally
This worries me, double chests always seem to pull tricks on automation.

I don't see much point in making this replacement to be honest, but it would potentially introduce new bugs.

**Comment by JeffersonDoan** [comment]
> This worries me, double chests always seem to pull tricks on automation.

I see the double chest feature being used mostly for actual storage or possibly décor in some builds. I rarely see people using double chests for automation (given that most machines only take up one block.)

> I don't see much point in making this replacement to be honest

Totally fair. Figured I would cast the line and see if anything bit while changes were upcoming. :)

> but it would potentially introduce new bugs.

For what it's worth a group of friends and I have been using this mod in a small private pack for the last week and it has functioned wonderfully.

**Comment by Merlo17** [comment]
I will make one final push for this. I still think the mod is worth switching over to because it's basically iron chests with extra features as it is, like nicer GUI management and double chests. 
To add to that, max supports it and was pushing for it on discord, mentioning planned features like entirely custom chest tiers with jsons, barrels and shulker modules and possibly even more. The way I see it is Iron Chests is kinda set in stone and will stay that way, while Expanded Storage currently already provides the same functionalities Iron Chests has but has a lot of room and potential to expand in the future. 
According to max there's going to be a new forge release soon ironing out some bugs (including https://github.com/NinjaPhenix/ForgeMods/issues/11 this one I reported hopefully) and bringing the mod on par with the fabric one so that new features can be added. If it does come in time I think we should look into switching over.

**Comment by NillerMedDild** [comment]
I guess we can look into it, I'm still not very much for it though.

**Comment by Merlo17** [comment]
@MaxNeedsSnacks help me sell this :P

**Comment by MaxNeedsSnacks** [comment]
@NinjaPhenix help me sell this :P

**Comment by NinjaPhenix** [comment]
Well frankly the forge version of expanded storage has less features than the fabric version and I'm currently rewriting the mod to make updates easier for both mod loaders.

ATM the only real difference is my chests can be merged into double chests and it also provides "cursed chests" styles to, so tall chests and long chests. I also provide 3 different screen types, one that has a scroll bar, one that split into pages and one that like iron chests has all slots on 1 screen.

The chests also don't currently use item handler capabilities either so I'm not sure how well the mod will interact with a bunch of other mods ( although I've had no real complaints yet ). TBH I'm pretty sure iron chest don't use item handlers either.

I also am not sure when the next update will be out as I have university assignments as well as my final year project to work on.
