### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by kkbizz** [NillerMedDild/Enigmatica6#60]
**Modpack version**
Version 0.2.3

**Issue**
World is crashing after joining. Minimap loads and the game crashes. Crash logs refers to Immersive engineering wires.
**Logs**
https://pastebin.com/FzL4k02x

**Comment by NillerMedDild** [comment]
While it may not be the cause, I'd like to rule out old java, please follow below instructions and let me know if it still crashes :)

You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by kkbizz** [comment]
Same issue, now running java 1.8.0_261. 
Here is the crash log: https://pastebin.com/hGRiZewZ

**Comment by NillerMedDild** [comment]
Thank you, I'll investigate further :)

**Comment by NillerMedDild** [comment]
Found the issue reported here: https://github.com/BluSunrize/ImmersiveEngineering/issues/4111
Seems like it's fixed but not releases yet.

**Comment by kkbizz** [comment]
Thanks for letting me know, i will try to remove the wires so i can play again.

**Comment by NillerMedDild** [comment]
Good idea :)
