### ISSUE TITLE
Sophisticated Backpacks JEI dyed versions error

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#642]
**Modpack version**
0.3.2

**Issue**
Colored variants of Sophisticated Backpacks in JEI show an empty forge/dyes tag, but the craft works fine. Figure it's a minor issue since the craft works, but people may get confused.

**Logs**
https://i.imgur.com/rYdmoxe.png

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Issue somehow fixed itself :P might've been the mod dev that fixed it.

**Comment by P3pp3rF1y** [comment]
Actually this is not fixed yet, the issue is that event that syncs tags to client sometimes gets handled before JEI collects recipes and sometimes after. If it's before there are already correct tags on client and you won't see any issue, but if it's after it basically refreshes the tags and then JEI recipes have incorrect ones. SBP is not the only mod that suffers from this and proper fix will need to happen on forge or possibly JEI side. I was looking into this, but I couldn't see how I could fix that from my side.

**Comment by NillerMedDild** [comment]
Alright, thanks for the info :)
