### ISSUE TITLE
Quests: Occultism

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#659]

**Comment by Thiana** [comment]
I was having trouble harvesting the materials for this mod until I looked at it's code. The author has implemented the harvesting effect as a negative potion effect. This is a problem if you have the 'Magical Herbs' trinket equipped because it just silently fails which leaves you with minecraft wood/saplings and no idea why. So when you write the quest disabling the trinket might be worth a mention :)
