### ISSUE TITLE
Occultism Harvesting Bug

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#674]
Moved from #659 
> I was having trouble harvesting the materials for this mod until I looked at it's code. The author has implemented the harvesting effect as a negative potion effect. This is a problem if you have the 'Magical Herbs' trinket equipped because it just silently fails which leaves you with minecraft wood/saplings and no idea why. So when you write the quest disabling the trinket might be worth a mention :)

**Comment by NillerMedDild** [comment]
@Thiana I'm having issues reproducing this issue, could you provide steps please?

**Comment by Thiana** [comment]
1. Find an Occultism Grove (though you may be able to confirm it by cheating in and growing an Otherworld Sapling)
2. Consume a Demon's Dream Fruit -- This will apply a horrible screen effect and when you harvest an Otherworld tree you'll get Occultism logs instead of minecraft oak logs. If you harvest the leaves first you'll get Otherworld Saplings instead of minecraft Oak Saplings.
3. Grow/Find a new Occultism oak tree.
4. Enable the 'Magical Herbs' trinket.
5. Eat another Demon's Dream Fruit -- This now has no visible effect.
6. Harvest the tree. You'll get plain minecraft logs and saplings now instead of the Occultism ones.  No message about the Demon's Dream Fruit not working and if you didnt already know the fruit was supposed to give you the nasty effect, you'd be stuck having followed instructions without the expected results.

Actually now that I've written this up, I think I had two potion related trinkets on. There was a second one which was for nullifying nausea/fatigue effects. So that might be a more likely culprit. It was called 'Coffee Bean' I think?  I can check in my game in a few hours if that isnt a trinket.

**Comment by NillerMedDild** [comment]
Perfect, thanks!

**Comment by Thiana** [comment]
It is the 'Magical Herbs' trinket. A simpler way to test.

1. New world
2. /losttrinkets unlock @p all
3. Eat a Demon's Dream Fruit -- This gives you 'Third Eye II' and 'Hunger II' for 15? seconds. The 'Third Eye' one is the harvesting one (https://github.com/klikli-dev/occultism/blob/d57e79298c0c4a5d60d63d4152043a8cb2350891/src/main/java/com/github/klikli_dev/occultism/common/block/otherworld/IOtherworldBlock.java#L54).
4. Enable 'Magical Herbs' trinket -- The two effects are stripped instantly. If you have the trinket enabled before you eat the fruit, the harvesting effect never kicks in at all.

**Comment by NillerMedDild** [comment]
As of next version, Third Eye will be a beneficial effect, fixing this issue :D
