### ISSUE TITLE
Add/Remove Stone Generation with KubeJS

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#698]
https://mods.latvian.dev/books/kubejs/page/worldgenremoveeventjs

Remove:
- `minecraft:diorite`
- `minecraft:granite`

Add:
- `create:limestone` 
- `create:weather_limestone` 
- `create:scoria` 
- `create:gabbro` 
- `quark:marble` 
- `quark:jasper` 
- `quark:slate` 
- `byg:mossy_stone`?

**Comment by MaxFirestorm** [comment]
.....Just a thought but if you remove diorite, do you have plans to alter the material for the T2 Tetra hammer?

**Comment by NillerMedDild** [comment]
Already done #579 :)

**Comment by MaxFirestorm** [comment]
Thank you. Just wanted to make sure ^^;

**Comment by Aelphais** [comment]
If it isn't too much trouble, what is the reason for removing the vanilla stones?

**Comment by NillerMedDild** [comment]
I think it clutters the underground and makes for an ugly caving experience. Additionally, our ores cannot spawn in granite/diorite.

**Comment by Thiana** [comment]
I just spent ~45 min in spectator+nightvision with the new worldgen and while it looks lovely I think it may have caused a few problems.

(1) Occultism underground groves are now quite rare (saw four).
(2) I've seen one Quark Crystal Cavern and it was mangled by tetra worldgen.
(3) Eidolon underground structures are very common.
(4) Tetra worldgen is odd. It seems to come in large clusters with multiple structures largish chunk area but fairly rarely. If you find 1 structure, you've probably got another 5-10 nearby.
(5) Natural scoria seems to be a lot more common than the other rocks visually but that may be because the quark super caverns often are generated at it's level.


It could just be bad RNG but they are possible problems to be aware of.

**Comment by Aelphais** [comment]
I can't speak for the other issues, but Tetra structures only generate beneath cold biomes, but under cold biomes, they're fairly common. This is by design. Tetra's design, not E6.

**Comment by NillerMedDild** [comment]
Thanks Thiana, really nice with feedback like that before the release is out :D

1) I also saw extremely few of these, have nearly doubled the generation chance to 1 in 250 chunks from 1 in 400.
2) I increased Quark Crystal Cavern generation.
3) I did not change Eidolon underground structures, I found them to be alright. I did buff the Stray Tower though.
4) Answered by `Aelphais` above.
5) Oddly enough I see very little Natural Scoria :P
