### ISSUE TITLE
Suggestion: Compact Machines

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#735]
It would be nice if we could get a mod like [Just Another Void Dimension](https://www.curseforge.com/minecraft/mc-mods/just-another-void-dimension) and/or [Compact Machines 3](https://www.curseforge.com/minecraft/mc-mods/compact-machines) to use for our messy/laggy builds. Both are available for 1.16.4 though CM3 is still alpha.

Thanks.

**Comment by NillerMedDild** [comment]
Compact Machines will most likely be added in the future, not so sure about a void dimension.

**Comment by KangyKSLG** [comment]
I second both. Having a void dimension to put our factories in to avoid overworld lag would be awesome. Compact machines is a good alternative as well

**Comment by Merlo17** [comment]
Compact machines looks pretty stable from my (although pretty limited) testing, but we have to keep in mind tunnels are still not super done (item seems to work, but there's no fluid or energy yet).

That being said at this point the only real way to test it is including it imo, it might help their development too if we do spot bugs, I haven't seen anything major so that's good at least.

I also have the script for compacting recipes done already, if it does get added I can quickly make actual compacting recipes for the machines, copying the ones from CM2 or even custom ones if we want

**Comment by NillerMedDild** [comment]
Adding CM for 0.4.0 then :)

> I kinda like the void dimension too tbh, it doesn't really hurt anyone and it's nice for those people who would rather build in there not caring about the overworld to have more space for a base

I'd rather not and wait for RFTools Dimensions

**Comment by Merlo17** [comment]
Fair, forgot about dim. Don't forget https://www.curseforge.com/minecraft/mc-mods/compact-crafting!
