### ISSUE TITLE
Mod suggestion: Re-addition of AE2

### ISSUE THREAD

**Issue by DannyDan4** [NillerMedDild/Enigmatica6#761]
[https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
While this was removed in the past, and could be considered to have overlap with refined storage, I would love to see AE2 being re-added to the pack, as it was originally only seeming to have been removed due to it not being updated at the time of the 1.16.1-1.16.4 transition.
I keep running into scenarios that left me desiring the QOL features of AE2 over refined storage, while also disliking how absurdly overpowered refined storage is. Given the whole 'accidental re-addition' of certus to worldgen in issue #746, now would be a great time to add the mod in again!

**Comment by Quezler** [comment]
related: #362 #361 & https://github.com/NillerMedDild/Enigmatica6/issues/362#issuecomment-723473354

**Comment by Merlo17** [comment]
What QoL features do you find missing in RS? In my opinion at least, RS is far easier and more pleasant to use: no types on cells means all of them are viable and you don't need to mess with weird math, it's far more intuitive and understandable to new players, fluid storage and autocrafting is more advanced than it was in AE and is pretty fun to mess with, the new features like autocrafting straight from JEI are sooo convenient, not needing to setup processors/assemblers to autocraft is much more streamlined and intuitive, the in-world crafting mechanics AE had were fun but got pretty tedious after a while (so much that people made entire addons just to lazily have a way to get around them).

I can see channels being something cool that is missed and I partially agree on that, however for how fun they are to mess around with they are much harder for new players to get into, and for experienced players they get stale after a while when you figure out the optimal ways to manage them, so I'm completely fine without them (as a bonus, being able to place importers on machines you autocraft with without worrying about channels and getting rid of the need to pipe items back into an interface with an external pipe is very good imo).

Overall I can see RS being "overpowered", but that's always something that can be tweaked. I don't think it's an issue in E6 as it is a kitchen sink, "do whatever you feel like" pack and having RS early just enables you to mess around with fun stuff earlier if you want to (not to mention other fun options for item sorting if you don't want to use RS, like RFTools or even Pretty Pipes). In an eventual Expert Mode it will be much more balanced and hard to reach, so there's also no issue there. I don't know what issues you have with RS so it would be interesting to discuss.

As for having them both, I'd say it's an extreme waste of resource and would just add redundancy. I'm all for giving the player choice, but I'd say there's literally almost nothing AE does that RS doesn't or viceversa, so a choice has to be made, and I think RS is the right one, for all the reasons stated above, not to mention us being close to its development process thanks to Darkere, which has always proven helpful.

I also find what Quezler said very ironic, since the new AE textures are really nice imo, and also Rid made them so it's even funnier

I rest my case

**Comment by KangyKSLG** [comment]
I think this comes down to the age old problem of RS being very unfriendly on servers. RS was renowned fore causing lag. HOWEVER, after extensively using it in this pack it's been perfectly fine. The only thing I don't like is the wireless crafting grid range.
AE2 had an addon that added cross dimensional unlimited ranged portable grids.

If there could be a way to add this functionality to RS i'd be very happy to stick with it. Although I do like the aesthetics of AE2 having flat terminals

**Comment by Ridanisaurus** [comment]
The server-unfriendliness was long resolved. This was back in 1.12 days. Since then Darkere revamped the mod completely, and it's performing like a beast on servers now.

To be honest, without AE2 Addons, there is simply no point in adding it. RS has more features, more new player friendly, has the wireless crafting grid (the range is being boosted to make it even better than it currently is in the next update), it has extra storage disks ..etc.

**Comment by KangyKSLG** [comment]
> The server-unfriendliness was long resolved. This was back in 1.12 days. Since then Darkere helped revamping the mod completely, and it's performing like a beast on servers now.
> 
> To be honest, without AE2 Addons, there is simply no point in adding it. RS has more features, more new player friendly, has the wireless crafting grid (the range is being boosted to make it even better than it currently is in the next update), it has extra storage disks ..etc.

This is the point I was, unsuccessfully, trying to make haha

**Comment by NillerMedDild** [comment]
> Although I do like the aesthetics of AE2 having flat terminals 

Me too :P

But it is indeed going to be a no.

**Comment by LasmGratel** [comment]
It doesn't about what is easier to use or what is **YOUR** favorite.
First, AE/AE2 has long been the first choice for the majority of players. A lot of players are used to AE2,
and AE2 will have more submod support while RS will never have.

Also, AE2 storage components are less expensive than Refined Storage. According to the [ME Storage Math](https://ae-mod.info/ME-Storage-Math/) you can store 266240 items for a 64k component while RS can only store 64000 items.

Besides, I found that EmendatusEnigmatica's unification has made Certus Quartz totally useless except for crafting. That means I can't add AE2 in my server without careful tweaking.

**Comment by Larandar** [comment]
I understand the rational between not having both RS and AE2 in the back and I agree that it will match 99.99% of the players needs.

But since the point is discussed so many time, could a small place in the wiki for those that want to share their tweaked config and even a datapack with customized recipes to match the other mods be made? I'm not suggesting for the dev to maintain it, only for users to link a few gists or tips about the tweaking needed?

**Comment by NillerMedDild** [comment]
The thing is, if we put it up on our wiki we have to maintain it, as it appears as coming directly from the development team either way.

**Comment by Larandar** [comment]
Fair enough

**Comment by ruifung** [comment]
Personally, after having used RS while playing E6, I feel like RS lacks several useful features from AE2..

Like being able to set more then 9 items as filters.
Or being able to set filters on individual disks.

**Comment by TemperedFool** [comment]
> Like being able to set more then 9 items as filters.

Filters for what? If we're talking about importers and exporters, the advanced versions support more slots.

> Or being able to set filters on individual disks.

To be honest, with no type limitations (and the unintuitive space ramifications those come with), I'm not sure I see the point?

**Comment by Ridanisaurus** [comment]
You can also replace the concept of individual disks filtering with just a Storage Drawer, and have it connected as an external storage, or a bunch of them, and have the external storage connected to their storage controller

**Comment by ruifung** [comment]
> 
> 
> > Like being able to set more then 9 items as filters.
> 
> Filters for what? If we're talking about importers and exporters, the advanced versions support more slots.
> 
> > Or being able to set filters on individual disks.
> 
> To be honest, with no type limitations (and the unintuitive space ramifications those come with), I'm not sure I see the point?

For the filters, storage busses? drives(cells)? I've used that to make a general "trash bin storage bus" with a priority between bulk storage and mass storage.

As for the individual disk filtering, I like to organize my bulk storage disks that way, especially since the drives apparently don't keep their settings when moved (AE2's cell filters work when you move them between drives)

Usually because I want to put multiple *large* disks into one drive, and not have one source (i.e. sand generator) fill up *all* the disks in that drive.

The cell filtering solves that by limiting items per cell / disk filtering, instead of needing me to put one *drive* per source.

**Comment by Honhk** [comment]
External storage exists. That's all I have to say for that entire comment you mentioned without even considering the fact that you don't actually need sand in your RS drives, to begin with.

**Comment by ruifung** [comment]
> 
> 
> External storage exists. That's all I have to say for that entire comment you mentioned without even considering the fact that you don't actually need sand in your RS drives, to begin with.

Yes, of course external storage exists, but usually I'd like to migrate all my drawers into a small collection of drives rather then a giant roomful of them. (not to mention fluid storage, which usually involves large, mutiblock tanks compared to a drive with individually partitioned cells.)

Also, i've already had a few occurances where somehow the external storage stopped detecting the drawer controller slave for whatever reason until I broke/replaced it / power cycled the RS network.

Plus AE2 allowed for a more compact setups with the cable / multipart thing they have going on. Plus the facades.

**Comment by Honhk** [comment]
Well seeing as **most** of your issues with RS are very subjective and will not bother / even appear to exist to some people, I suppose we can declare this conversation over. Ultimately AE2 is also much laggier compared to RS once you do a lot of stuff with it.

**Comment by TemperedFool** [comment]
> Yes, of course external storage exists, but usually I'd like to migrate all my drawers into a small collection of drives rather then a giant roomful of them. (not to mention fluid storage, which usually involves large, mutiblock tanks compared to a drive with individually partitioned cells.)

This sort of partitioning in AE2 is really only needed because of types reducing storage on cells that have multiple types. With giant discs and no types, storing everything on disk (fluids too!) doesn't seem like an issue.

> Also, i've already had a few occurances where somehow the external storage stopped detecting the drawer controller slave for whatever reason until I broke/replaced it / power cycled the RS network.

Yeah, Storage Drawers are kinda a buggy mess. Might I suggest Black Hole Units, or one of the many other bulk storage options in the pack? Occultism's dimensional storage is a popular external storage target.

> Plus AE2 allowed for a more compact setups with the cable / multipart thing they have going on. Plus the facades.

Yeah, most of us familiar with AE2 miss both of these. Doesn't seem like a particularly compelling reason to switch though. We're also hopeful that the facades issue will be resolved eventually.

I will say personally that I, like every other 1.12 player, was a little skeptical about the choice of RS instead of AE2 when I first started playing E6; playing with it made me realize the choice doesn't actually matter all that much, and that the benefits (sweet, sweet fluid crafting for example) outweigh the losses.

I think everyone working on the pack understands that some people prefer AE2 - there are also a bunch of people that prefer RS! At the end of the day we're choosing one or the other, as having both basically just bloats the pack, and the choice made was RS.

I think at the end of the day it meets our needs more - one of those being to encourage you to build stuff that ISN'T just one mod doing everything. I think it's a feature, not a bug, that to achieve the type of storage system you're talking about you will likely need to branch outside of RS.

Hopefully this makes sense. TL;DR, we understand that some people prefer AE2, but so far I think no one has pointed out something you literally can't do within Enigmatica 6 as a pack, that AE2 would enable. I think it would take something of that scale to make us rethink this choice.
