### ISSUE TITLE
Bug: Fletching villagers cannot exist due to modified fletching tables

### ISSUE THREAD

**Issue by Sanguinely** [NillerMedDild/Enigmatica6#767]
**Modpack version**
0.3.4

**Issue**
Fletching tables have a gui when right clicked which is not vanilla, due to the modification villagers do not recognize fletching tables as a job block.

**Comment by telemenar** [comment]
I also ran into this issue.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found the bug reported here: https://github.com/Shadows-of-Fire/Apotheosis/issues/285

**Comment by theboo** [comment]
as far as i can tell, this issue is still only fixed in dev in apotheosis... they havent put out an update since october... still having the issue in e6 0.3.8(my kid was trying to make a fletcher lol)

**Comment by theboo** [comment]
still not fixed... apparently we can temp fix this by disabling the villager module in apotheosis.cfg, this will remove the nice wandering trader trades, but also disable the fancy fletching table. The fletcher is probably the 2nd most used villager after the librarian so it might be worth it until apo finally updates. (it was apparently fixed in apotheosis dev a month ago...)

**Comment by r-mc2** [comment]
Would disabling their module only remove the Apotheosis weapons/tools/armor that he sells or the trader entirely?
My only consideration would be the QoL changes you all made to give him Tetra items to alleviate those frustrations 😄

**Comment by NillerMedDild** [comment]
We didn't add that :P

**Comment by theboo** [comment]
the wandering trader itself is added by that pesky vanilla mod, he isnt going away anytime soon xD

**Comment by NillerMedDild** [comment]
I disabled it, and Fletching villagers now work just fine. Good idea ^^
