### ISSUE TITLE
Astral Sorcery resources not properly generating or crafting.

### ISSUE THREAD

**Issue by Ciege666** [NillerMedDild/Enigmatica6#782]
**Modpack version**
0.3.2

**Issues**
Iron Ore does not convert into Star Metal ore generated from crystal collector crafting.
Astral Sorcery marble cannot be chiseled into other chiseled variants.
Quark Marble can be chiseled into the various Astral Variants, but is considerably more rare than normal Astral Marble.
Astral Marble not generating in natural world generation except in Astral Temples and Shrines.

**Comment by TemperedFool** [comment]
I think I can help with all of these:

> **Modpack version**
> 
> 0.3.2
> 
> 
> 
> **Issues**
> 
> Iron Ore does not convert into Star Metal ore generated from crystal collector crafting.

You need to use Vanilla ore, not EE ore.
> 
> Astral Sorcery marble cannot be chiseled into other chiseled variants.

Known bug, fixed in 0.3.4.
> 
> Quark Marble can be chiseled into the various Astral Variants, but is considerably more rare than normal Astral Marble.

Same bug as above. Not sure what the intended generation rate is, but I agree it's pretty rare.

> 
> Astral Marble not generating in natural world generation except in Astral Temples and Shrines.

I think this is intended - otherwise they likely would have disabled the Quark stuff and left the Astral. I'd personally prefer the Astral stuff stay, but upping the gen rate of the Quark kind would be OK.

**Comment by NillerMedDild** [comment]
EE ore also works for making starmetal in 0.3.4 :) 
We are upping generation or marble in 0.3.5
