### ISSUE TITLE
{Suggestion} Minecraft abnormals

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#808]
These mods are amazingly done and they  were in e5 so it makes sense
https://www.curseforge.com/minecraft/mc-mods/abnormals-core
https://www.curseforge.com/minecraft/mc-mods/atmospheric
https://www.curseforge.com/minecraft/mc-mods/autumnity
https://www.curseforge.com/minecraft/mc-mods/berry-good
https://www.curseforge.com/minecraft/mc-mods/buzzier-bees
https://www.curseforge.com/minecraft/mc-mods/endergetic
https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage
https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by Thiana** [comment]
I should clarify my upvote here. I think these abnormal mods would fit nicely: 
https://www.curseforge.com/minecraft/mc-mods/abnormals-core
https://www.curseforge.com/minecraft/mc-mods/endergetic
https://www.curseforge.com/minecraft/mc-mods/endergetic
https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage
https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic

These ones are already covered by BYG or are trivial and don't add enough new content:
https://www.curseforge.com/minecraft/mc-mods/atmospheric
https://www.curseforge.com/minecraft/mc-mods/autumnity
https://www.curseforge.com/minecraft/mc-mods/berry-good
https://www.curseforge.com/minecraft/mc-mods/buzzier-bees

**Comment by Thiana** [comment]
That bot appears to need fixing.

**Comment by KrAzYGEEK32** [comment]
I have been playing with savage and ravage, it changes a lot of base game mechanics and has really sparse documentation. (Atm it's just a pdf file pinned in abnormals discord) please correct me if I'm wrong. Also, it altars creeper behaviour and "improves" the AI of pillagers. Please do a thorough review of it before adding it imo :D 
PS: the creeper changes are annoying af

**Comment by Merlo17** [comment]
I like Endergenic and Aquatic, but the pillager one also doesn't do much for me. In general I think they're cool mods to add to a "Vanilla+" style pack, but in a more advanced modpack like E6 I feel like they all do barely anything to change or add features, and instead they're just kinda "there". Sure, they don't hurt anyone, but if Niller wants to keep the mod count down I don't think these all do much for the pack. Otherwise Endergenic and Aquatic seem harmless enough

**Comment by Thiana** [comment]
I've not played S+R with the creeper functionality enabled. It is configurable and since I'd prefer to play without creepers entirely I disable any mod's 'improvements' of them. The only thing that really jumped out as a change to vanilla mechanics was changing the way you triggered the bad omen effect, though I'll admit I don't play  vanilla so I might have missed other vanilla mechanic changes.

**Comment by Dasavanth** [comment]
yea thats what i meant by reviewing the mod, i believe the creeper changes are on by default, so please disable them :D. btw i love the raid starting mechanic added by the mod tbf. makes sense and also give you control. i just wish changes are documented a bit more i guess.

**Comment by NillerMedDild** [comment]
While I agree that these mods are of very high quality, I don't think they fit into E6 at this time. They're perfect for vanilla+ packs, but they don't fill any particular role or function in E6.
