### ISSUE TITLE
Evilcraft 

### ISSUE THREAD

**Issue by Crackthebox** [NillerMedDild/Enigmatica6#814]
https://www.curseforge.com/minecraft/mc-mods/evilcraft

It has also just been ported. I remember it was in every pack back on 1.7.10

**Comment by Merlo17** [comment]
I have played around with it a bit in creative, it seems pretty fleshed out already and could be pretty fun for the pack. However, I think it needs a major texture makeover, since the whole mod is stuck in pre 1.14 and it looks awful next to the other items in the pack. Our good Rid won't be pleased with that for sure :P

**Comment by NillerMedDild** [comment]
I'd prefer not to add this, we have tons of magic mods already and it doesn't have any *really* cool content imo.
