### ISSUE TITLE
[Suggestion] Quest condense/cleanup

### ISSUE THREAD

**Issue by DocHuzz** [NillerMedDild/Enigmatica6#840]
**Modpack version**
0.3.5 Beta

**Issue**
Starting a new world (as one does when they update to a new version), it took no less than three minutes to go through and clear out checkmark tasks.  There are approximately 50 checkmark tasks (minus 'Advance Power Generation' and 'Fissile Fuel Production' which appear as though they should be unlocked but are unclickable) in the initial questbook that need to be cleared in order to properly start the modpack under 19 different headings.

After clearing out the checkmark tasks, I dumped my inventory and claimed all quests to receive 66 levels and 44 different items.  Due to the random nature of some of the rewards (delights) as well as some things giving the same items, there were actually more rewards given simply for the first 50 checkmark tasks.

I can certainly see that this is not meant to be a hardcore pack, but there does come a point that rewards become a wee bit too excessive and free.  Couple that with the sheer time waste of clicking a quest, a checkmark, clicking outside the screen 50 times, it does become somewhat tiresome.

May I recommend a simpler method of one quest that gives out the books for the various mods that you are going to give the player followed by individual introductory quests that are completed when the player crafts the starter item or encounters the starter condition?  As in the Botania line starts the first time you pluck a magical flower, you start Immersive Engineering when you craft the engineer's hammer, or you unlock the Thermal path when you mine copper or tin the first time.

These are just my 2 cents, mind you, not a demand or a criticism meant to insult.  

I did create a video if you'd like me to upload it showing how it goes and the result.

**Comment by Merlo17** [comment]
It's an interesting point, and a valid one for sure. My guess is most of them weren't from the initial checkmark quests for each chapter but rather from single chapters with heavy use of them, like mekanism's?
Anyways, I don't think you are intended to immediately claim all the rewards when you get in, but naturally go through them when you're doing the mods. Having the starting points be tied to a specific item in the mod could be the way to go for that, but in the end I'm not too sure it makes too much difference. I'd guess most players won't immediately claim every quest available to them anyways

**Comment by NillerMedDild** [comment]
I think we should change to give fewer rewards for clicking checkmarks, and change first quest in chapters to require the starting item where possible. 66 levels and 44 items is a bit much to have access to right away :P
Additionally I think we should change the direct level rewards with just xp, so they don't get you that high level.

**Comment by MuteTiefling** [comment]
Yeah, as Merlo mentioned, the intent was never to have someone go through and claim all the check mark quests as they start. Rather, the expectation is that you accept the first few checks as you start a quest section, thus giving  you the starting 'tools' and books as you're ready to begin that mod.

If all the books are given up front in one clump, you'll likely just dump them somewhere and forget they exist. By receiving only the relevant books/tools when you're starting the mod, you're more aware of what they go with.

I believe the majority of the 44 items you got there should have been Food (Farmer's Delight) and random helpful resources like clay and such (Scavenger's Delight). Anything beyond that would require some crafting of some sort. 

Also, regarding Mekanism's Advanced Power and Fissile Fuel Production lines, these are not meant to be open when you start. If you look in the quests you'll notice they have pre-requisites. 

I'll take a look over XP and entry level rewards as Niller suggested. One thing to remember with the XP rewards, however... you're -very- likely to die early on. If you claim them right as you start, you are most likely just throwing them away. Better to save those for a time when you're getting ready to enchant stuff.

**Comment by Merlo17** [comment]
To be fair, book rewards might become obsolete when the akashic tome is in, since it will have a recipe for a filled book with all the mods' books, so that's something to keep in mind at least

**Comment by MuteTiefling** [comment]
Mmhmm. Good point, though I vastly prefer having individual books over the Akashic tome. Not sure that I'm in the majority there though.

**Comment by DocHuzz** [comment]
Just as a quick reference, here is the quest reward screenshot.
![vlcsnap-2021-01-10-11h13m31s995](https://user-images.githubusercontent.com/4410570/104128372-33102400-5335-11eb-8dd4-42fbfd913c30.png)

**Comment by Merlo17** [comment]
That seems acceptable to me, since most of those are either wrenches, books (which you probably won't claim all at once) or items needed to start the respective mod chapters. Only a small handful seem to come from delights, I thought it'd be worse. I'll leave it up to Niller to decide though, so if he wants to streamline that a bit we'll go ahead ^^

**Comment by MuteTiefling** [comment]
So I've completed a first pass as shown here: 



Completely Free

Storage:
Plonk - farmer's delight (unchanged)
Find me - farmer's delight (unchanged)
pretty pipes start - scavenger's delight (removed)

Powah
about tiers : changed Powah loot box to XP

Mekanism 
Basic power : moved free energy cube to a sub quest
Material Processing : moved free personal chest to a sub quest

Industrial Foregoing
start quest: Moved acacia logs/saplings to a sub quest

PNC
F or C? - Farmer's delight (unchanged)
Logical path forward - Farmer's delight (unchanged)

Ars Nouveau
Auto-magically - Free carbuncle charm switched to Farmer's Delight

Resourceful bees - Yes, there are a lot of clicky quests here. The quest system is being used as documentation and there's just no great way to convey this information -and- tie it to a craft. Bunch of free xp here. 





A note on some of the other free items that you get when you claim the first quest: They're meant as a direct aid to getting started. 

For instance, the starting Nature's Aura quest gives you a pair of shears because you kinda need them to get going in the mod.

Ars Nouveau gives you the basic spell book for a similar reason. Yes, you could craft it, but since this is a new (and very awesome) mod, I really wanted to give people incentive to get into it. The book costs a lot of iron to craft, normally. This way, you can start messing with spells, one of the more interesting aspects of the mod, immediately. 

Blood Magic gives you some snares, again because they're required to start and it's just a tiny boost to get you over an otherwise boring mechanic. 

Botania gives you a free mortar and pestle. Which, is as vital to the mod as a wrench. I could have give the wand of the forest directly, but felt it was worth explaining how to get there through quests and to highlight it's importance in it's own quest, contrary to most other wrench type items.

Most of the rest of this is Books/wrenches. You've got some items in there from scavenger's delights which are now moved behind crafting quests. At this point, the only real things you'll get at the start are now Food, XP (less), Books, Basic Tools

This is now the extent of what you'll get after these changes, plus 36 levels:

![image](https://user-images.githubusercontent.com/9543430/104129727-6f468300-533b-11eb-8a30-a6e8bd0006dc.png)

So that's:

- 13 mod reference books
- 6 random meals
- 10 tools vital to starting the mod in question
- 1 small backpack
- 4 slime and 4 string to help getting started with Refined Storage (these are already super simple to craft anyway)
- 1 beginner spell book for Ars Nouveau that can act as a basic multitool and a weak sword to start out. 


As for changing the learning quests to unlock automatically upon an initial craft, rather than the current check box... I'm not opposed, but that's going to require some reworking of the quests and some extra thought. I personally want Documentation/Basic tools to be readily available to the player, which means the starting order of almost every chapter would need to be re-done to focus on some starting item, rather than the current 1-2 check mark quests in most of them.

**Comment by NillerMedDild** [comment]
> 
    14 mod reference books
    6 random meals
    10 tools vital to starting the mod in question
    1 small backpack
    4 slime and 4 string to help getting started with Refined Storage (these are already super simple to craft anyway)
    1 beginner spell book for Ars Nouveau that can act as a basic multitool and a weak sword to start out.
    16 snares, given for the reason stated above.

Very nice.

> As for changing the learning quests to unlock automatically upon an initial craft, rather than the current check box... I'm not opposed, but that's going to require some reworking of the quests and some extra thought. I personally want Documentation/Basic tools to be readily available to the player, which means the starting order of almost every chapter would need to be re-done to focus on some starting item, rather than the current 1-2 check mark quests in most of them.

Let's just keep them as-is, at least for now :)

**Comment by Merlo17** [comment]
It's probably one less book, since you actually spawn with modded for dummies. I just felt like being picky :P

**Comment by MuteTiefling** [comment]
> It's probably one less book, since you actually spawn with modded for dummies. I just felt like being picky :P

We might need to check that then. You for sure get one from a starter quest. If we start with it then the quest one should go.

**Comment by TemperedFool** [comment]
I don't THINK I got the modded for dummies book at login, in both 0.3.2 and 0.3.4, for what it's worth...

**Comment by NillerMedDild** [comment]
I replaced it with the quest book in 0.3.2 iirc

**Comment by Merlo17** [comment]
You'd be totally right, I just remembered how it used to be in the past and didn't bother checking in the latest version. My bad ^^
