### ISSUE TITLE
[Mod Suggestion] AE2, Woot and a few more...

### ISSUE THREAD

**Issue by IDKZAL** [NillerMedDild/Enigmatica6#845]
- [ ] https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2
- [ ] https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
- [ ] https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture
- [ ] https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions
- [ ] https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture-tiered-crystals
- [ ] https://www.curseforge.com/minecraft/mc-mods/industrial-agriculture
- [ ] https://www.curseforge.com/minecraft/mc-mods/common-capabilities
- [ ] https://www.curseforge.com/minecraft/mc-mods/flux-networks
- [ ] https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3
- [ ] https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation
- [ ] https://www.curseforge.com/minecraft/mc-mods/morph-o-tool
- [ ] https://www.curseforge.com/minecraft/mc-mods/not-enough-wands
- [ ] https://www.curseforge.com/minecraft/mc-mods/jei-integration
- [ ] https://www.curseforge.com/minecraft/mc-mods/woot
- [ ] https://www.curseforge.com/minecraft/mc-mods/faster-ladder-climbing
- [ ] https://www.curseforge.com/minecraft/mc-mods/trample-stopper
- [ ] https://www.curseforge.com/minecraft/mc-mods/extra-disks
- [ ] https://www.curseforge.com/minecraft/mc-mods/torcherino
- [ ] https://www.curseforge.com/minecraft/mc-mods/better-than-mending
- [ ] https://www.curseforge.com/minecraft/mc-mods/classic-combat

Just check the one you will add, I think you can do that if I'm not wrong.

Regards

**Comment by Darkere** [comment]
Please check the pack and this github before suggesting new mods. 90% of these have either been rejected before or are already in the pack.

**Comment by TemperedFool** [comment]
I'll leave editorial to the devs, but I will say that I miss Faster Ladder Climbing every time I get on a ladder...

**Comment by Merlo17** [comment]
For AE2 see https://github.com/NillerMedDild/Enigmatica6/issues/761
For ID see https://github.com/NillerMedDild/Enigmatica6/issues/678
For MA we have resourceful bees serving the same purpose
For Flux Networks see https://github.com/NillerMedDild/Enigmatica6/issues/646
For Reliquiary see https://github.com/NillerMedDild/Enigmatica5/issues/410
For woot see https://github.com/NillerMedDild/Enigmatica6/issues/590
Extra Disks already has an equivalent in the pack
Classic combat imo doesn't fit at all
Torcherino just seems kinda dumb and we have equivalents in the pack already
For MorphOTool see https://github.com/NillerMedDild/Enigmatica6/issues/817

The rest might be worth investingating or at least worth discussing, but yeah, that's why you really should check older issues before suggesting a lot of stuff like this :P We know about these big mods as well, so if they're not in yet there's likely a good reason why

**Comment by IDKZAL** [comment]
Thanks for letting me know.
What is the equivalent to Torcherino in this pack if may ask?

Regards

**Comment by Merlo17** [comment]
Well for spawners apotheosis can do that natively on vanilla spawners, while for the rest it seems to me like an astral horologium ritual could do?

**Comment by IDKZAL** [comment]
Torcherino speeds up Ticks for certain Blocks etc like Mekanism Machines or Spawners or pretty much anything that uses "ticks".
So that's why I asked, I haven't found anything like that in the pack yet.

**Comment by Merlo17** [comment]
Astral's horologium ritual does exactly that

**Comment by TemperedFool** [comment]
Also, I haven't spent a lot of time running servers (and just for personal use), but aren't high-end tick accelerators pretty server-hostile?

**Comment by MuteTiefling** [comment]
Yes, the are. And Torcherino takes things to the extreme by being both easy to craft and having high tiers that do a lot of acceleration.

This sort of stuff also tends to break some mods, so it's just not great in general.
