### ISSUE TITLE
[Sugestion] Balance Power Generation

### ISSUE THREAD

**Issue by ManiacRobert1** [NillerMedDild/Enigmatica6#861]
Yes, i know the pack it's a kitchen sink pack, but whole power system can be balanced.

Let's take as example powah reactors, a basic one can generate stupid amount of FE(6.5k/t) for small amounts of iron, redstone, coal, clay and lava.

If you don't use mekanism machines in crazy-mode as possible, you don't need another power-gen in your game progression.

Another example is gas-burning ethylene.

![image](https://user-images.githubusercontent.com/39351347/104329393-84671180-54f5-11eb-99b8-4795e26a356e.png)

That is my example of gas-burning generator, output from melon farm goes into thermal sawmill, 1 melon = 9 melon slice, 1 melon slice = 4 bio fuel => 1 melon block = 45 bio fuel(+ output of seeds), with that output you can generate 100krf/t with a small amount of effort, so, powah reactors / generators are 100% useless, fission is useless in basic shape for FE gen.

My sugestion about powah reactors is to buff with 30%-70% energy generation (10%-15% to nitro stage).
About mekanism gas-burning generators, should have almost same amount of energy production how was it in e2e.

And now, about Extreme / Bigger reactors.

Yes, i know, we have Powah, Mekanism, IF etc, but, there are some pros about that mods.

- Can be added Custom Liquids(i see on direwolf gameplay astral liquid).
- Cool CC: Tweaked community-made apps for reactors.
- In case of Extreme Reactors, the textures has been changed.
- Power output it's not that powerfull as mekanism or powah.
- Did I mention cool looking apps by community on the monitor?

**Comment by Darkere** [comment]
Agree that we do need to take a look to at least somewhat balance out power generation. 

That said I don't think big reactors fullfills any roles that aren't already filled by mekanism and powah apart from the variable internals. Those might be covered by another mod we are currently considering.

**Comment by MuteTiefling** [comment]
Just to put a few numbers out there, here are some of the bigger generators in the pack. 

| Energy Producer                       | Fuel Input                                 | Energy Output (MFE) | Rate (kFE/t) | Rate (FE/t) |
|---------------------------------------|--------------------------------------------|---------------------|--------------|-------------|
| Basic Fission + Basic Turbine (quest) | 8000 mB Fissile Fuel (8 uranium ingots)    | 228.28              | 570.91       | 570910      |
| Powah Reactor (Starter)               | 8 Uraninite (plus coal, redstone, dry ice) | 26.47               | 1.56         | 1560        |
| Powah Reactor (Basic)                 | 8 Uraninite (plus coal, redstone, dry ice) | 84.75               | 6.3          | 6300        |
| Powah Reactor (Hardened)              | 8 Uraninite (plus coal, redstone, dry ice) | 148.34              | 13           | 13000       |
| Powah Reactor (Blazing)               | 8 Uraninite (plus coal, redstone, dry ice) | 181.66              | 18           | 18000       |
| Powah Reactor (Niotic)                | 8 Uraninite (plus coal, redstone, dry ice) | 357.68              | 42           | 42000       |
| Powah Reactor (Spirited)              | 8 Uraninite (plus coal, redstone, dry ice) | 447.49              | 59           | 59000       |
| Powah Reactor (Nitro)                 | 8 Uraninite (plus coal, redstone, dry ice) | 572.35              | 84           | 84000       |
| Gas Burning Generator                 | 1 bucket of Ethylene                       | 11.26               | 72.19        | 72190       |
| Mycelial Reactor                      | All the things                             |                     | 25000        | 25000000    |
| Solar Panel (Starter)                 |                                            |                     | 0.005        | 5           |
| Solar Panel (Basic)                   |                                            |                     | 0.012        | 12          |
| Solar Panel (Hardened)                |                                            |                     | 0.04         | 40          |
| Solar Panel (Blazing)                 |                                            |                     | 0.09         | 90          |
| Solar Panel (Niotic)                  |                                            |                     | 0.22         | 220         |
| Solar Panel (Spirited)                |                                            |                     | 0.5          | 500         |
| Solar Panel (nitro)                   |                                            |                     | 1.2          | 1200        |
| Thermo Generator (Starter)            | water                                      |                     | 0.008        | 8           |
| Thermo Generator (Basic)              | water                                      |                     | 0.56         | 560         |
| Thermo Generator (Hardened)           | water                                      |                     | 1.44         | 1440        |
| Thermo Generator (Blazing)            | water                                      |                     | 3.2          | 3200        |
| Thermo Generator (Niotic)             | water                                      |                     | 7.2          | 7200        |
| Thermo Generator (Spirited)           | water                                      |                     | 16           | 16000       |
| Thermo Generator (Nitro)              | water                                      |                     | 38.4         | 38400       |
| Furnator (Nitro)                      | burnable fuel                              |                     | 4.8          | 4800        |
| Wind Generator                        |                                            |                     | 0.192        | 192         |
| Solar Generator                       |                                            |                     | 0.0218       | 21.8        |
| Advanced Solar Generator              |                                            |                     | 0.1308       | 130.8       |

I've left out Thermal entirely because it's just a straight 640 rf/t at best. the only thing that changes is efficiency. 

My first, and probably biggest issue with balancing of Powah against other things is the cost. Tiered crafts suck. 

I know, I know, free power is often made expensive in MC because it's boring and spamming it is bad. But it gets spammed anyway. But just compare the cost of a niotic solar panel to a mekanism Advanced generator. There's a lot more going into that Powah panel and just not a lot of gains. 

So I do feel the recipes on these should be reworked such that they're no longer tiered upgrades, similar to the reactors. I think the range of power could also be made narrower, with the low tier generating maybe around 100 rf/t and top tier finishing at 1k rf/t

On the topic of free power... Thermo Generators. Neat concept, but it's just an RTG that needs a slow trickle of water. I don't think these should be as good as they are. Yes, they're capped on output, so even though the nitro _can_ generate 38k/t, you can only extract 10k/t. That's still kinda silly compared to solars that run for half the day and only output 1.2k/t at the same tier. 


Next, the elephant in the room. Ethylene. Obviously we can nerf it into the ground. The GBG can not currently have it's rate reduced, however, so it can do 72k no matter how much we nerf ethylene. Reducing the amount of bio-fuel you get per crop could be a good start here, as well as increasing the cost of production. If you only get 5k net rf/t (or less) out of the production line, then it suddenly becomes a lot less interesting as permanent power. It instead becomes a nice way to buffer a backup, or as a portable energy source before getting to wireless stuff. A GBG and a tank of gas is a great way to power a digital miner before you can get entangloporters or Powah wireless stuff going. 

So, I'd say we keep energy density where its at. 1 bucket making 11.26 million RF. But try to tweak it so the production is much more costly. By comparison, LPG in a compression dynamo currently outputs a total of 18 million RF. But there's a fair bit more work that goes into producing that and, again, it's capped at 640rf/t. 

Powah Reactors seem... lackluster. You end up going through a lot of automation to actually supply coal/redstone/ice/uranium to keep them running. Is it on the same order as a mekanism fissile fuel? Probably not. But given work that is involved, and the relative rarity of uranium, it feels like they need a boost. 

I'm thinking a boost to energy density would be great for them.  Just let it run longer so you're not out hunting for uranium as often at early stages. I think narrowing the gap between tiers could be good here too. Maybe 5k-80k rather than the current 1.5k-72k. 

Finally, Mek Fission/Fusion.

The gadget patterns I set up for the quests for Fission will handle a burn rate of 20mb/t with water cooling, and that turbine will output 570k fe/t. That RF/t is strictly determined by the size of the turbine and the steam produced. A bigger turbine, while a little costly, isn't that difficult to put together. Neither is a bigger reactor to get better steam production. 

The main issue with fission is the waste management, which ultimately means running it constantly isn't possible. There's just no way to remove the waste fast enough, so you end up running out of room to store it. It's currently just a speed-bump/complicated crafting step to get to Fusion and the Mekasuit. Fusion just gets silly, as we all know. And in this pack there's just nowhere to spend it all. Sure, you can dump it into an SPS, but you're mostly done with that by the time you can even make a fusion reactor since there's not much use for antimatter. Having some custom replicator recipes for antimatter could be interesting, however. Even for a non-expert mode, as it could give people a legitimate reason to actually create a full processing chain and a dump for the power they generate. The question, then, is what do we add as recipes for nucleosynthesis? It currently costs 10 uranium ingots to make 1 mb of antimatter, so they would need to be really good to be interesting. 

Since Fission and Fusion are both ultimately tied to the turbine, I think that's the place to look to bringing them in line. I don't know if there's a simple dial we can tweak to reduce the RF:steam ratio. It seems like it would be a mess to try to balance otherwise since fusion can just produce such an ungodly amount of steam. 


Now... the thing that I think is probably most important here is that we have basically nothing that acts as a constant heavy drain on power. There's little upkeep cost on a base. Yes some machines can be expensive to run, but you run them so infrequently that it doesn't amount to much in terms of RF/t over their lifetime. That's why I'm thinking some nucleosynthesis recipes could be nice since they can really drain a ton of power. 

Otherwise, RS is the only thing I can even think of that actually has a constant upkeep cost. And that is pretty tame. I don't think making it more costly is the way to go, however, as that just makes it inaccessible early on.

**Comment by TemperedFool** [comment]
Tbh, reading that, I can't help but wonder why Mekanism Generators is in the pack - any pack outside of gated-in-expert really. I guess it's popular and all, but have you considered axing it rather than trying to balance it?

With it gone, it seems like you could bring the various options from Powah, Immersive, Thermal, and whatever else is there more in line with each other. I definitely agree that (especially high tier) dynamos need some help.

I know it isn't going anywhere, but I figured I'd be the one to suggest it ^_^

**Comment by MuteTiefling** [comment]
That would certainly solve a lot of issues

**Comment by TemperedFool** [comment]
Something about the baby and the bath water...

For a more reasonable idea, in addition to balancing the other mods out, maybe chuck the Mek generators below Fission/Fusion? Everything through Powah Fission seems to handle needs below that nicely, and make the lower-end Mek generators seem kinda redundant.

If you're going to keep the GBG at all, making Ethylene more of an expensive liquid battery seems like an idea, as would tossing the GBG and requiring people to burn liquid Ethylene in the newly buffed dynamos ^_^

Not knowing how configurable it is, can you nerf how much steam is produced by the reactors and boiler? Making water-cooled reactors more like a 5x bonus, with and the boiler using the reactor's thermal output 10x, my might be slightly less insane (even if still beyond anything the non-expert pack needs).

**Comment by MuteTiefling** [comment]
Chucking the gbg is something I'd like to avoid, honestly. Using it for hydrogen recycling in some of the processing chains is very handy. Although... That would also significantly increase the cost of running those chains.

I'm going to run some tests tonight to see if I can tweak the energy gains on ethylene down.

**Comment by telemenar** [comment]
You can with the configs already in the pack limit steam’s energy production:
https://github.com/NillerMedDild/Enigmatica6/blob/fd8798e56950550d24812e7109971bad6a751828/config/Mekanism/general.toml#L73

And limit the ability to make steam with the boiler - but that would have risky follow on effects with using it to cool the fission reactor. 

Limiting raw fusion potential could be done by limiting energy in the fusion fuel: 
https://github.com/NillerMedDild/Enigmatica6/blob/fd8798e56950550d24812e7109971bad6a751828/config/Mekanism/generators.toml#L7

**Comment by NillerMedDild** [comment]
After Mute's extensive rebalancing efforts I'd say we're in a much better place in 0.4.0 :)

**Comment by MuteTiefling** [comment]
Hopefully it works out well >.>

**Comment by blazingcreeperx** [comment]
I hope i'm not out of place commenting on this but could RS's constant need for power be negated by creating a powah energizing recipe that allows the controller to be crafted into its creative variant using a significant amount of FE? Just an idea...

**Comment by theboo** [comment]
that would very well negate the need to constantly power ur RS system... But why would we want to negate that?

**Comment by MuteTiefling** [comment]
> I hope i'm not out of place commenting on this but could RS's constant need for power be negated by creating a powah energizing recipe that allows the controller to be crafted into its creative variant using a significant amount of FE? Just an idea...

I'd personally love it if there were _more_ things with a constant draw, not fewer. I've always been enamored with things that have a cost to run. For instance, PNC's pipe system which requires a certain amount of air per item moved, per block. Create's belt and pipe systems as well. 

This sort of stuff encourages you to make a fully automated power system so you don't need to worry about the lights going out. It also encourages making backup systems in case the lights -do- go out for some reason. What do you do if all your fuel is locked up in an RS drive, for instance, and you just overdrew your grid? Well, if you hadn't planned ahead, you've got a little issue on your hands.
