### ISSUE TITLE
Functions to make it easier to add the same type of KubeJS recipes

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#929]
For example, we have a ton of crushers and presses that usually have the exact same inputs and outputs, we could make functions such as `function crusherRecipe(variables...)` that adds recipes for all crushers in the pack.

What do you think @MuteTiefling, would this be helpful for you?

**Comment by MuteTiefling** [comment]
I was considering that here recently, actually. There's a bit of an issue I'm not sure how to solve though.

Secondary outputs, for one. Take the recent sand recipes. For some, there are no secondaries, which is OK. But then you've got the IE crusher and the Thermal one that do, but at different rates. We can't just normalize that because thermal's pulverizer has upgrades to enhance that secondary output.


Second issue is duplicates. I really do try to avoid them where I can, even if it's just the same recipe twice. As long as I'm hand crafting the scripts, I can avoid that.

So, not opposed, but not really sure how to tackle it either. Thoughts?

**Comment by NillerMedDild** [comment]
To be honest I'm not certain this would be a time saver, just thought I'd throw it out there :P

> Secondary outputs, for one. Take the recent sand recipes. For some, there are no secondaries, which is OK. But then you've got the IE crusher and the Thermal one that do, but at different rates. We can't just normalize that because thermal's pulverizer has upgrades to enhance that secondary output.

There's nothing that says we would *have* to use them for everything, I was just thinking simple stuff like crushing flowers into dye, sandstone crushing and the like. If secondary outputs are there, we can always set a chance for thermal/ie in the script itself.

> Second issue is duplicates. I really do try to avoid them where I can, even if it's just the same recipe twice. As long as I'm hand crafting the scripts, I can avoid that.

Not sure here either tbh. Not sure it would be an issue if we don't over use it.
